### ISSUE TITLE
Details Sales Report not showing refund invoices sales. 

### ISSUE THREAD

**Issue by kamranbhutto** [nexopos/v3-issues#102]
**Username** : Kamranbhutto

**Details Sales Report not showing refund invoices sales. **

1. After refunding a sales and confirming refund, the sales status shows as partially refunded.
2. Whereas the Partial sales stop appearing in details sales report.
3, On the sales options, the refunded amount is still showing payable to the customer.  

Screen Shot enclosed.

**Expected behavior**
The Refunded amount should be paid back to the customer and the particial sales should appear on the detail sales report. 

![22](https://user-images.githubusercontent.com/3133422/46655346-cd1c1b80-cbc4-11e8-8b45-4d67bfcd78da.png)
![image](https://user-images.githubusercontent.com/3133422/46655352-d0afa280-cbc4-11e8-8cb0-5337fbcd9285.png)
![8129829d0d2e74beb10c12937a2218e3e5e2a847f03320f524 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/3133422/46655354-d311fc80-cbc4-11e8-85cd-78bd0eee4760.png)

**Environment (please complete the following information):**
 - NexoPOS  v3.13.6

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
We've added a new order management which shows more informations on refunds. https://github.com/Blair2004/nexopos/commit/a8c5be770338cd7eb39f158fe5800d128b8abd73
