### ISSUE TITLE
categories Creation  date time Issue 

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#103]
**Username** : 
*****

**Describe the bug**
After Creating categories  wrong date time format

**Environment (please complete the following information):**
- NexoPOS 3.13.8
-  Gastro v2.3.22 
 - PHP version 7.1

![capture](https://user-images.githubusercontent.com/32275898/46688754-cb317700-cc1b-11e8-9a8f-db300b9c7ecf.PNG)

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by vishalwalia1** [comment]
coupons also have  wrong date time format

![capture](https://user-images.githubusercontent.com/32275898/46689040-8eb24b00-cc1c-11e8-958c-288a63d32129.PNG)
