### ISSUE TITLE
CURRENCY EXCHANGE

### ISSUE THREAD

**Issue by mysul** [nexopos/v3-issues#104]

**Comment by mysul** [comment]
Actually, I used the second option which is -Feature Submition.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
