### ISSUE TITLE
NexoPOS/Gastro ONLINE STORE FRONT

### ISSUE THREAD

**Issue by sysman7** [nexopos/v3-issues#108]
NexoPOS/Gastro is a solid product but it's missing the ONLINE STORE FRONT that can sync with the physical store. People spend a lot of time on their mobile now days and like to pre-order stuff and pick it up or they have it COD. This would be a good addition to the software.

Thanks,
Jack
Envato email: carequeue@comcast.net

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Hi, we've planned a WordPress for a Store Front : https://nexopos.com/what-is-the-iic-and-how-to-join-it-to-earn/
