### ISSUE TITLE
Gastro issue - The table name does not exist.

### ISSUE THREAD

**Issue by ChaDye** [nexopos/v3-issues#11]
I have installed Gastro following your instructions here:
https://github.com/nexopos/v3-issues/blob/master/how-to-install-gastro.md

Lauching restaurant areas and tables list lead to following issue:

An Error Was Encountered
The request returned the following message : The table name does not exist. Please check you database and try again.
Code : 11

**Comment by Blair2004** [comment]
Thank you, your request will be reviewed.

**Comment by Blair2004** [comment]
Hi, have you checked that with the last update the issue is fixed or not ? https://codecanyon.net/item/gastro-restaurant-extension-for-nexopos/20242963
