### ISSUE TITLE
The sales reports do not break down the tax.

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#111]
**Username** : israel

**Describe the bug**
The sales reports do not break down the tax.

**To Play**
1. Go to 'imforme'
2. Click on 'detailed report'

**Expected behavior**
The sales report should break down the tax (VAT, VAT). Also enter sales by type of tax.

For example: If you have items that have 10% VAT and other items that have 21% VAT, these two types of tax would have to be broken down.

**Screenshots**
View photo: https://www.screencast.com/t/5u9oBocseq

**Environment (please complete the following information):**
  - NexoPOS: [e.g. 3.13.8]
  - PHP version [e.g. 7.1]
  - MySQL version [5.6]
  - Devise used (desktop browser, smartphone, POS system).

**Additional context**
I hope you keep it in mind and implement it.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "israelga" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by israelga** [comment]
My user is wrong?

**Comment by Blair2004** [comment]
The username as registered on Nexo Platform "israelga" doesn't exists. Please consider updating your username.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-09-20 11:58:45</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
This issue would have been a good one if you had a valid (supported licence).
https://nexopos.com/what-is-the-iic-and-how-to-join-it-to-earn/
