### ISSUE TITLE
The calculator does not work with the numbers on the keyboard.

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#112]
**Username**:
israel

** Describe the bug **
The calculator does not work with the numbers on the keyboard.

** To Play **
1. Go to 'POS control panel'

** Expected behavior **

** Screenshots **

** Environment (please complete the following information): **
  - NexoPOS: [e.g. 3.13.8]
  - PHP version [e.g. 7.1]
  - MySQL version [5.6]
  - Devise used (desktop browser, smartphone, POS system).

** Additional context **
I hope you keep it in mind and implement it.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "israelga" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-09-20 11:58:45</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
This suggestion has yet been part of the previous contest. It still pending Than you for reminding that.
