### ISSUE TITLE
grid is too big

### ISSUE THREAD

**Issue by elvessisante** [nexopos/v3-issues#116]
**Username**:  Elvessisante

**Is your feature request related to a problem? Please describe.* is too big even i upload online or any touch screen this is too big *
A clear and concise description of what the problem is. Ex. I'm always frustrated when [..is too big should save some space then the kios able to take view more category and menu.]

**Describe the solution you'd like**
Make more smaller i attach some image this squire is the good size for the kios and mobile ordering 

**Describe alternatives you've considered**
i need to make small only 
![capture](https://user-images.githubusercontent.com/28305520/47541843-80825100-d8e3-11e8-8151-eefeb10fa4b1.PNG)

**Additional context**

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by elvessisante** [comment]
my username is correct
![image](https://user-images.githubusercontent.com/28305520/47541992-07372e00-d8e4-11e8-8a73-9426485a28c3.png)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-08-15 13:00:58</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-12-07 23:49:32</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2018-08-15 13:01:49</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>
