### ISSUE TITLE
Feature : add edit button for orders displayed on the table history

### ISSUE THREAD

**Issue by Sridhar991982** [nexopos/v3-issues#118]
**Username**:  Kiblfos (Replace all this with your username)

**Is your feature request related to a problem? Please describe.**
I could not apply discount for the Dine in orders and from Table selection there is no option to go to POS with order items so that i can apply discount 

**Describe the solution you'd like**
I need edit order button in the table selection screen like checkout or add item , so that moment click the edit order button it will bring to the POS for that particular order with item loaded so that i can apply discount and view with total either i can apply discount here or pay to the order and close the order

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-01-12 13:31:19</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-10-23 00:00:00</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
What we would like to avoid, is to have an order which items is being cooked changed. usually the advice here is to cancel an item (before it's being cooked) and to add new items. We cannot provide an edit feature for orders on table history, since that might cause more unpredicatable issues.
