### ISSUE TITLE
Add Multiple Cart SameTime

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#119]
**Username**:  walia7878

Should have option to add new cart without holding or cancel the current order 

like - if current customer not decided what to order and cashier like to take new order so cashier should 
have option to add new cart without holding or cancel current order 
that way order taking will be fast -
please see the image below-- in image 1,2 in it menu can be cart number or order number 

![untitled-1](https://user-images.githubusercontent.com/32275898/47777720-571a5880-dd1b-11e8-992c-eea94003d18c.jpg)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-08-30 00:00:00</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi,
it's not a bad suggestion, we should however focus our effort on the upcoming POS UI. We'll provide more information how that works.
