### ISSUE TITLE
@Multistore 

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#120]
**Username**:  walia7878

now we have  multi-store and each store have its own inventory , customers , Suppliers , Settings and many other feature but don't have user creation for multi-store ?
how about if nexopos we add option that each store have its own user creation and permissions like - 
** Store A and Store B can create different users and set permissions  
** also create option like when user login in multi store it automatically redirect to store which store user    can access .

**Comment by Blair2004** [comment]
The module Nexo Store Advanced Manager offer a user creation for store.
