### ISSUE TITLE
cashier IN and Out

### ISSUE THREAD

**Issue by elvessisante** [nexopos/v3-issues#121]
**Username**:  elvessisante

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [NO.]

**Describe the solution you'd like**
Cashier IN and Out this use to find if the cashier is short or having more money. cashier IN is to identify how much the cash inside cash drawer  should ask how much the cash and During Cashier Out it should ask how much money inside the cash drawer and he should not able to find out how the total sales during end of the day when he make cashier out he will define how much cash in cash drawer and the system will print the cashier out report this is include beginning balance total sales, total short and item sales by category

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-08-15 13:00:58</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-12-07 23:49:32</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2018-08-15 13:01:49</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
The register is made to support cash-in and cash-out operation.
