### ISSUE TITLE
kiosk self order

### ISSUE THREAD

**Issue by elvessisante** [nexopos/v3-issues#122]
**Username** : elvessisante
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
1. type only show delivery 
2. when the pages is refresh i need to login again
3. the response for choice the menu is slow im not sure if browser issue 

**To Reproduce**
1. Go to 'select the order.'
2. Click on 'define type'
3. wait for a while like 10second or less
4. and error will show only delivery will show uo

**Environment (please complete the following information):**
this on demo system http://tendoo.org/sok/so/store

![image](https://user-images.githubusercontent.com/28305520/47905932-38da6700-de99-11e8-87d8-ea9b71d2f00a.png)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-08-15 13:00:58</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-12-07 23:49:32</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2018-08-15 13:01:49</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
The issue should have been fixed with the last update of SOK : http://tendoo.org/sok/so/store
