### ISSUE TITLE
Issue : Potential break while sending stock transfert email

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#123]
**Username** : blair2004

**Describe the bug**
We've tried to proceed to stock transfer from one location to another, but on the server response, there is a token error, which makes impossible to send the email.

**To Reproduce**
1. Go to Stock Transfer
2. Make a new transfer
3. Open the console and check the network tab to see the server response

**Expected behavior**
We should be able to receive an email after each Direct Stock Transfer or Request Stock transfer

**Screenshots**
![screenshot-nexopos go-2018 11 02-14-06-07](https://user-images.githubusercontent.com/5265663/47917431-ce7df280-dea9-11e8-821d-b0e7b03f6ed1.jpg)

**Environment (please complete the following information):**
 - NexoPOS: 3.13.10
 - PHP version 7.1
 - MySQL version 5.7
 - Devise used : Chrome Desktop Windows 10

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS Local Dev</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>Gastro Demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale - Gastro Demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS SOK</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "blair20042" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS Local Dev</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>Gastro Demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale - Gastro Demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS SOK</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
