### ISSUE TITLE
Issue : Locking stock update while transfering digital items

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#124]
**Username** : blair2004

**Describe the suggestion**
We're wondering to see that, after a stock transfert of digital items, the quantity before and after, is updated. Normally, we should not update the quantity for these items.

**What is the issue in steps**
1. Go to Stock Transfert
2. Make a stock transfert
3. See the 

**Expected behavior**
The stock shouldn't be updated.

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS Local Dev</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>Gastro Demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale - Gastro Demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS SOK</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
