### ISSUE TITLE
Users Permetion

### ISSUE THREAD

**Issue by Muhammed1980** [nexopos/v3-issues#127]
**Username** :  MUHAMMED1980
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**

**To Reproduce**
1. Go to 'my own URL
https://www.demo.alrajhisoftshop.com/Restaurant/sign-in/?notice=login-required&redirect=https%3A%2F%2Fwww.demo.alrajhisoftshop.com%2FRestaurant%2Fdashboard
And login
Ahmed
19805648
'
2. Click on 'Manage Users ->Create User ->Make any test user and add to a group button and select sub-store.manager
then try to login with the new created user and you will see the error
![screenshot_2018-11-04 https www demo alrajhisoftshop com](https://user-images.githubusercontent.com/44752367/47967759-210a0b00-e072-11e8-873e-8a552dd3fc2c.png)
'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12] 3.2.1
 - Gastro (if installed) [e.g. 2.3.10] 2.3.22
 - PHP version [e.g. 7.1] 7.0 FastCGI
 - MySQL version [5.6] 5.6
 - Devise used (desktop browser, smartphone, POS system). All

**Additional context**
When i select Shop Manager i have this error

![screenshot_2018-11-04 error](https://user-images.githubusercontent.com/44752367/47967817-a2fa3400-e072-11e8-8da3-73e9b6ac4935.png)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-03-28 22:15:58</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-09-24 13:11:22</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
