### ISSUE TITLE
Feature : Multiple Fonts for Nexo Print Server

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#128]
**Username**:  blair204

**Is your feature request related to a problem? Please describe.**
Some customers are facing issue reading the font used by Nexo Print Server. Maybe providing another solution would be more appropriated.

**Describe the solution you'd like**
The default font work good, but, having multiple fonts might improve the readability of a receipt.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "blair204" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.
