### ISSUE TITLE
Feature : Improve the stock taking workflow

### ISSUE THREAD

**Issue by nexopos** [nexopos/v3-issues#131]
**Username**:  blair2004

**Is your feature request related to a problem? Please describe.**
A Stock taking might be long if we have a repetitive and more often stock taking.

**Describe the solution you'd like**
In order to ease the stock taking process, we might need to be able to load previously saved stock taking and use provided item as reference on the new one. This will give the capacity to cancel what is not on the new stock taking and proceed more faster.

**Describe alternatives you've considered**
This could be made as async operation to load stock taking (previous) and fill up the table.

![6669cfde-9b3f-41f8-bfe8-6834e3d1cd5f](https://user-images.githubusercontent.com/40301137/48706293-1a47d000-ebfc-11e8-9950-8b8b57d9c8c2.jpg)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS Local Dev</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>Gastro Demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale - Gastro Demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS SOK</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Scheduled for NexoPOS 4
