### ISSUE TITLE
on receipt due amount is wrong

### ISSUE THREAD

**Issue by aibarfasi** [nexopos/v3-issues#135]
**Username** : 
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Provide" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by Blair2004** [comment]
The issue is not clear enough to be understood.
