### ISSUE TITLE
Sales on the POS don't display on sales menu and reports issue

### ISSUE THREAD

**Issue by Gigi237** [nexopos/v3-issues#136]
**Gigi237** : 
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**The sales on the POS don't appear on the reports and sales**

**1. Go to POS
    2. Add an item to the cart
    3. Proceed to the sale
    4. Check your operation on the sales menu
    5. Check your operation on the reports
    6. See error**

**In fact the detail of the sale would appear on the reports and on the sales menu**

**
![screenshot-api nexopos com-2018 10 18-21-46-01](https://user-images.githubusercontent.com/19439172/48998225-24fdea00-f153-11e8-8383-0524a96bd304.png)
![screenshot-tendoo org-2018 11 26-08-08-59](https://user-images.githubusercontent.com/19439172/48998226-24fdea00-f153-11e8-8fc1-58b4f117e44c.png)
![screenshot-tendoo org-2018 11 26-08-09-40](https://user-images.githubusercontent.com/19439172/48998227-25968080-f153-11e8-83a8-6b370f265fb6.png)
**

**NexoPOS  v3.13.17
   Chrome on desktop**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
The issue is not clear enough to be understood
