### ISSUE TITLE
Wrong Receipt Amount Format

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#138]
**Username** : walia7878
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
Wrong Receipt Amount Format when we use item amount 25,000.00

**Environment (please complete the following information):**
 - NexoPOS  v3.13.17
 - Gastro  v2.3.24
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]

![captusssssre](https://user-images.githubusercontent.com/32275898/49103587-c09d7080-f2a1-11e8-89ed-4d35b12dcd54.PNG)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-08-30 00:00:00</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Issue fixed.
