### ISSUE TITLE
Can't not acess to the dashboard

### ISSUE THREAD

**Issue by Gigi237** [nexopos/v3-issues#139]
**Username** : Gigi237
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug** : i have enable the gastro module and disable the nexopos module

**To Reproduce**
1. Go to 'modules'
2. Click on 'nexopos'
3. Click on 'Gastro'

**Expected behavior** : Return to dashboard

**Screenshots** : ![bug nexo](https://user-images.githubusercontent.com/19439172/49523745-a7e91800-f8aa-11e8-991d-af14ae0f7668.png)

**Environment (please complete the following information):**
 - NexoPOS 3.13.10
 - Gastro 2.3.23
 - PHP version 7.1
 - MySQL 5.6
 - Chrome

**Additional context** : No additional context

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS licence</td>
                                <td>2019-10-18 00:00:00</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Normally, Gastro depends on NexoPOS, so it can't and shouldn't be disabled. However, we'll see a workaround for this issue.

**Comment by Blair2004** [comment]
Issue fixed so far
