### ISSUE TITLE
taking new order to same table kot is not working

### ISSUE THREAD

**Issue by phanichowdary369** [nexopos/v3-issues#142]
**Username** : phani
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
if we taken order for table 1 we'll send kot to kitchen
after some he ordered new order we need to add in same table new items then to send kot to kitchen
kot was not working

**To Reproduce**

**Expected behavior**
fix it as soon as possible

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, after having reviewed your account, we've not been able catch any licences.
                Please note that, it's required to have a licence on your account, in order to receive updates and support. 
                [Click here](https://api.nexopos.com/dashboard/profile/envato-licences/add) to add a new licence to your Nexo Platform account.
                Regards.

**Comment by Blair2004** [comment]
Hi, your issue is not complete and no well described.
