### ISSUE TITLE
New Feature : Purchase by Bottle Sell by Glass

### ISSUE THREAD

**Issue by samerkamel** [nexopos/v3-issues#143]
**Username**:  samerkamel

**Is your feature request related to a problem? Please describe.**
This is a feature request as we're using with Gastro in a Bar, we purchase Juice for example in Litres but sell by Glass. 

**Describe the solution you'd like**
I would love to have some sort of unit we can define for each item, purchase unit, sell unit, and unit conversion rate ( for example : Purchase by Bottle, Sell by Glass, and Bottle has 4 Glasses ) 

**Describe alternatives you've considered**
I do understand that we can on the supply screen say instead of purchasing 4 bottles we add 16 Glasses but this is confusing for the suppliers or when adding the supply and it will be great to just have the unit show in the supply screen and just add how many bottles. 

I wouldn't mind trying to work on this myself if you give me some directions. 

**Additional context (optional)**
![screen shot 2018-12-20 at 5 27 42 pm](https://user-images.githubusercontent.com/6500550/50293574-97c16300-047c-11e9-94b4-28b9e15d317f.png)
![screen shot 2018-12-20 at 5 26 32 pm](https://user-images.githubusercontent.com/6500550/50293586-9e4fda80-047c-11e9-8fd9-867f8f115c5b.png)

**Comment by Blair2004** [comment]
This is a unit of measure improvement, and it's yet planned. However, thank you for sharing this idea.

**Comment by Blair2004** [comment]
we've moved the unit of measure to the version 4
