### ISSUE TITLE
due amount was getting wrong due to tax

### ISSUE THREAD

**Issue by phanichowdary369** [nexopos/v3-issues#144]
**Username** : phanichowdary
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
due amount was getting wrong

**To Reproduce**

1.  select table and create the order then it was showing perfect amount
2.  then please new order to same table / cancel some of ordered items 
3. then see the bug
4. i have already explained to Mr.Vishal, He said that to post issue here

 

**Expected behavior**
Due to this issue i have losted client, there is one client 
need to fix the bug in upcoming 24 hrs

**Screenshots**
https://ibb.co/VJn0qFn
https://ibb.co/qpf2zNk
https://ibb.co/44mh0xw
https://ibb.co/HGgMVVP
https://ibb.co/wYFNx8p

**Environment (please complete the following information):**
 - NexoPOS: in all versions
 - Gastro (if installed) in all versions
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
Item Purchase Code:
ea0b7fb4-a139-4329-b4fb-2a48478d4d5f

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-05 07:37:50</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-05 07:37:50</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-06-15 05:01:29</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Thank you for submitting your issue here, we'll investigate more on this.

**Comment by Blair2004** [comment]
Here is an example with a canceled item : 
![image](https://user-images.githubusercontent.com/5265663/50392142-f708c700-074b-11e9-888a-30590fc80945.png)
But the due amount remain valid : 
![image](https://user-images.githubusercontent.com/5265663/50392172-58309a80-074c-11e9-963e-07d716366f02.png)
