### ISSUE TITLE
Recreate Barcode Button generating error.

### ISSUE THREAD

**Issue by rrrajib1** [nexopos/v3-issues#145]
**Username** : 
raziba

**Describe the bug**
Under Settings menu when i am clicking on items, i found barcode recreated button. and when i am licking on this button then its generating error.

**To Reproduce**
1. Go to 'Setting'
2. Click on 'items' menu from left
3. Click on 'Recreate Barcode' Button

**Screenshots**
<img width="1485" alt="screen shot 2018-12-27 at 12 52 45 pm" src="https://user-images.githubusercontent.com/5637539/50469590-4e6e9780-09d7-11e9-9622-e8ce84f08500.png">

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.26]
 - PHP version [e.g. 5.6]
 - MySQL version [5.6]
 - Devise used (desktop browser Firefox & Chorome).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-28 22:44:50</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-11-28 22:44:51</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Thank you for submitting that issue. We'll review it.
