### ISSUE TITLE
Muhammed1980

### ISSUE THREAD

**Issue by Muhammed1980** [nexopos/v3-issues#147]
**Username**:  (Replace all this with your username)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context (optional)**

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by Blair2004** [comment]
The issue is not well formated. Please read this to know how to post an issue/improvement on Github : https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/
