### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by samerkamel** [nexopos/v3-issues#149]
**Username** : 
samerkamel
**Describe the bug**
When trying to update Gastro or NexoPOS it keeps "on going" forever, checking the network tab in developer tools reveals the following errors: 

for Gastro:
{status: "failed", message: "config-file-not-found"}
message: "config-file-not-found"
status: "failed"

for NexoPOS:
{status: "failed", message: "Unable to identify the zip file uploaded as a NexoPOS update."}
message: "Unable to identify the zip file uploaded as a NexoPOS update."
status: "failed"

**To Reproduce**
Go to updates, click on update, wait and check network tab in developers tools

**Expected behavior**
Update Successful ?

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: 3.13.18 
 - Gastro (if installed) 2.3.31
 - PHP version 7.1
 - MySQL version 5.6
 - Devise used  desktop 

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-15 13:17:03</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-06-15 13:17:04</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-06-15 13:17:04</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by samerkamel** [comment]
Issue fixed by support team
