### ISSUE TITLE
Register the number linked to central calling

### ISSUE THREAD

**Issue by krsad** [nexopos/v3-issues#15]
First, this is not a bug. That will improve the program.

When someone call us on central, program can register the number and the address', the next calling we can see who is calling and the address of person who call us. It can be done with api codes. 
So everyone can do it with their central program.
If you can't do something like that, I have to do it by myself or I will make it to a developer. 

Thanks for your help :)

**Comment by Blair2004** [comment]
Hi thanks you for your idea. Bote that a custom id module is already under development

**Comment by Blair2004** [comment]
Since the module is being developper, having that issue open is nto more needed.
