### ISSUE TITLE
Split order on Gastro and NexoPOS

### ISSUE THREAD

**Issue by samerkamel** [nexopos/v3-issues#150]
**Username** : 
samerkamel

**Describe the bug**
After creating an order for a certain table, say table X, with about 6-7 items, when splitting the order on different receipts there are a number of issues: 

1- Usability issue, the page remains open and no feedback that it was successful so the user will be confused
2- The order does get split, but if i choose to split on 4 receipts, i can only find 3 receipts when i check the table again, the last split is completely lost. 
3- The split order does not calculate VAT, if the item in Split 1 is for 50$ and the VAT is 10% the total amount is shown as 50$ and VAT is 0.  ( Although in checkout screen it does show the correct amount so probably an API issue or something )

**To Reproduce**
Create new order, 6 items on Table A, send to kitchen, then options, split order on 4 parts, add any items to each split order and then click split.

**Expected behavior**
1- Feedback if the split is successful and preferably the window for split will be closed automatically. 
2- The order should be split on the exact number of splits i choose. 
3- Any print from the system should also include any taxes or VAT in the settings. 

Latest version updated right now by support team.
Ticket is opened after support team checked the issue exists.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-15 13:17:03</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-06-15 13:17:04</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-06-15 13:17:04</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, we've indeed reviewed the script and we've discovered the issue. The fix is already ongoing.
