### ISSUE TITLE
Shipping Address Not showing on Receipts print

### ISSUE THREAD

**Issue by Noorhad** [nexopos/v3-issues#151]
**Username** : noorhad

nexopos recipts prints without showing shipping address (Open pos> add product, customer > pay > checkout > Print )  where its already been set on nexopos setting > Invoice settings > Column 2 of the default receipt > {delivery_address_1}

But the receipt comes with blank space. 

 - NexoPOS: [e.g. 3.13.25]
 - PHP version 5.6
 - MySQL version [5.6]
 - Devise used desktop , chrome,

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Actually the issue is not well formated. Here is how your upcoming issues should be formatted : https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-28 21:36:25</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
