### ISSUE TITLE
report  Inventory Tracking by Items 

### ISSUE THREAD

**Issue by jalaany** [nexopos/v3-issues#153]
Hi
My username is jalaany
We need this report  Inventory Tracking by Items how I can get it 
like this report
Inventory Tracking by Category
http://tendoo.org/gastro/dashboard/nexo/reports/stock-tracking#
Thanks

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Issue not well formated.
