### ISSUE TITLE
Quotations & Vat Reg number for Customers

### ISSUE THREAD

**Issue by DIDSMJ** [nexopos/v3-issues#154]
We are using NexoPos we have an issue with quotations and Vat registration for Customers
If you can urgently assist of these 2 issues will be greatly appreciated

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by DIDSMJ** [comment]
how can we be assisted then ???
