### ISSUE TITLE
Quotations issues

### ISSUE THREAD

**Issue by DIDSMJ** [nexopos/v3-issues#155]
We are using NexoPos we have an issue with quotations and Vat registration for Customers
If you can urgently assist of these 2 issues will be greatly appreciated.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by DIDSMJ** [comment]
how can we be assisted then ???

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).
