### ISSUE TITLE
Needs in the new update

### ISSUE THREAD

**Issue by Muhammed1980** [nexopos/v3-issues#159]
**Username :** Muhammed1980

Hello;
We just want to add a store opening and closing time or hour whatever, as you see below we open early morning and close next day early morning we close for one and half hour and we need to calculate the sells of that timeline for one day because we start for example in Saturday and close the cashier in next day in Sunday
for example like
Stores opens at 04:30 01.01.2019
Stores closes at 03:00 02.01.2019 (Next day) 

i'm sorry if i didn't tell everything understandably you can contact me at
mohamad@alrajhisoft.com
00905380266954

**Describe the solution you'd like**
If you can add this option in new update it will be Fantastic,We had over 4K costumer in KSA using our old .exe restaurant system and all of them want to  change to the web and we're buying license from you if you do this option we and you everyone will be in profit

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Muhammed1980** [comment]
it's not issue its a claim

**Comment by Muhammed1980** [comment]
something i need it in the next update not issue

**Comment by Blair2004** [comment]
Alright, note that the suggestion is however not well formated, but we'll keep this for the next update. The currrent update is almost ready.

**Comment by samerkamel** [comment]
I would like to add my vote for this request ( as discussed on whatsapp ) this will make many customers happier with the reports

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by Blair2004** [comment]
We've implemented a time support on the detailed report. That should help you to select the time range from where you want to generate the report.
