### ISSUE TITLE
Discount amount customer group not appears on receipts

### ISSUE THREAD

**Issue by harjanto-jadin** [nexopos/v3-issues#160]
**Username** : harjanto.jadin

**Describe the bug**
Customer Group discount (both percentage & fixed) amount not printed on sales receipt but it is calculated to the total.

**To Reproduce**
1. Go to 'Customer - Group'
2. Click on 'Edit User Group' on selected group
3. Choose ‘Discount Type' either Percentage or Fixed Discount
4. Enter Discount Percentage of Fixed Amount
5. Click Save when finish.
6. Make an order from POS using selected user within above customer group
7. Print Receipt

**Expected behavior**
The nominal of discount (as well percentage) should be printed in receipt.

**Screenshots**
See the receipt screenshot and Customer Group Setting

**Environment (please complete the following information):**
- NexoPOS  v3.13.23
- Gastro  v1.10.10
- PHP version  7.1
- MySQL version 5.6
- Devise used:  Desktop browser.

**Additional context**
Please print also the percentage of discount (for Percentage Discount only) next to “Discount” text. Example “Discount  (XX%)         USD 10”  
![customer-group-dsicount-amount-not-appear-on receipt](https://user-images.githubusercontent.com/43326592/50878070-72829d80-1407-11e9-969b-283d2b48e998.jpg)
![customer-group-dsicount-amount-not-appear-on receipt-1](https://user-images.githubusercontent.com/43326592/50878486-9f37b480-1409-11e9-9161-9d3d7b9c5d13.jpg)

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Provide" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "harjanto" on [Nexo Platform](https://api.nexopos.com).
                    Note that, maybe the issue is not well formatted as well, please consider reading [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/). 
                    Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "harjanto" on [Nexo Platform](https://api.nexopos.com).
                    Note that, maybe the issue is not well formatted as well, please consider reading [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/). 
                    Regards.

**Comment by Blair2004** [comment]
Thank you for submitting this issue. We'll review that.
