### ISSUE TITLE
Detailed Reports doesn't work

### ISSUE THREAD

**Issue by Muhammed1980** [nexopos/v3-issues#161]
Muhammed1980
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
The detailed reports doesn't work i click on Display results i have nothing  

**To Reproduce**
1.Go to Reports
2.Detailed Reports
3.Click on Display results

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: v3.14.0
 - Gastro (if installed)  v2.3.33
 - PHP version 7.1
 - MySQL version 5.6
 - Devise used: PC google chrome

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
