### ISSUE TITLE
orders insert zero quantity or wrong total price

### ISSUE THREAD

**Issue by kmedia2018** [nexopos/v3-issues#162]
**kaypame** : 
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
Sometimes, on ordering products,the system inserts wrong quantity or wrong total price.

**To Reproduce**
1. Go to 'point of sale'
2. Hold or pay
3. Then check the details of the order

**Expected behavior**
Normally,the quantity entered on the POS was the one supposed to be inserted in the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/38244301/51114845-35efe100-180f-11e9-9321-cd9764c29517.png)

or

![image](https://user-images.githubusercontent.com/38244301/51115837-0393b300-1812-11e9-8501-4ea91061f96d.png)

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - PHP version 5.6.31
 - MySQL version 5.7.19
 - Devise used (desktop browser).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Hi, you're using a older version of NexoPOS since this UI is depreacted. Consider updating and consider formatting well your issue : https://nexopos.com/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/
