### ISSUE TITLE
 Print alternative itemname in invoice

### ISSUE THREAD

**Issue by alsaihati** [nexopos/v3-issues#164]
**Username** :  saihati

**Describe the bug**
Can't Print alternative product name by using Nexo Print Server in Invoice (no need in kitchen receipt) only needed in invoice.

**To Reproduce**
1. Go to 'PAY after making order'
2. Click on 'Full payment'
3. See the customer invoice

**Expected behavior**
to print the invoice (only) with both names of item for example item name in English and alternative in Arabic.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-11-22 18:33:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-04-07 11:26:04</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-04-07 11:28:30</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Queued for the upcoming update.

**Comment by alsaihati** [comment]
I am Still waiting dear

**Comment by Blair2004** [comment]
The feature should be implemented so far.
