### ISSUE TITLE
Need more function on ticket

### ISSUE THREAD

**Issue by alsaihati** [nexopos/v3-issues#165]
**Username**:  saihati

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I need to reprint the invoice again any time and need to automate how many copy do I need like 2 copies automatically. Need more function on ticket like to add item to the same invoice. Some customer add some items after payment or after printing ticket.

**Describe alternatives you've considered**
reprint ticket, reopen and more functions

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-11-22 18:33:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-07-06 15:00:52</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-04-07 11:28:30</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by alsaihati** [comment]
It is lie !!!

My username is "saihati" and i have valid licence

**Comment by Blair2004** [comment]
Thank you for updating, but the thread has been udpated and the suggestion has been merged to the current ongoing update.

**Comment by alsaihati** [comment]
Great!
I will be waiting 

Thank you
