### ISSUE TITLE
bug in kitchen receipt

### ISSUE THREAD

**Issue by alsaihati** [nexopos/v3-issues#166]
**Username** :  saihati

**Describe the bug**

If I make order on pos for example 1  cheese burger as no tomato
And 1 cheese burger no onion

In kitchen receipt print as: 
Cheese burger (1)
No tomato 

Only.

The other item (if it is same item as example not printing )

**To Reproduce**
1. Go to '.pos sale..'
2. Click on '.item then choose it again...'
3. Scroll down to '..pay to print..'
4. See error in kitchen receipt

**Expected behavior**
print the item twice as in invoice

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-11-22 18:33:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-04-07 11:26:04</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-04-07 11:28:30</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
