### ISSUE TITLE
Order Again Appear in Kitchen

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#167]
**Username** :  walia7878
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
Order Again Appear in Kitchen After Payment done from Table Selection

**To Reproduce**
1. Go to 'create new dine-in order  and send order to kitchen '
2. Click on 'from kitchen screen Make Order Ready'
3. Now go back to dine-in and do checkout and after payment done order again appear in kitchen screen  

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.14.5]
 - Gastro (if installed) [e.g. 2.3.33]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-08-30 00:00:00</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by danlim26** [comment]
any updates on this issue? Can't use the kitchen feature

**Comment by tungstalker** [comment]
I have the same problem. on demo have same problem too.

**Comment by Blair2004** [comment]
Hi, i've recently tested the situation, but i haven't been able to reproduce it. Can anyone provide a database or a settings exported that we can use ?

**Comment by vishalwalia1** [comment]
Hello,
Please see the video from link below- 
https://drive.google.com/open?id=1pBeuad92ChI8vkMn-7wYhdfXp3Ah4Ycc

**Comment by Blair2004** [comment]
This video is really helpful Thank you.
