### ISSUE TITLE
Shipping information phone number 

### ISSUE THREAD

**Issue by mo3men** [nexopos/v3-issues#169]
**Username** : mo3men
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
Shipping information for delivery order showing customer phone number but in the Invoice settings > Delivery Information there is no code to show the customer number on the receipts.  

**To Reproduce**
1. Go to 'POS Screen'
2. Click on 'Shipping'
3. Scroll down to 'phone number'

**Screenshots**
![1](https://user-images.githubusercontent.com/46889122/51467922-c5047800-1d7e-11e9-8d81-123f68bbaf37.png)
![2](https://user-images.githubusercontent.com/46889122/51467930-cc2b8600-1d7e-11e9-8808-25028828b8e5.png)

**Environment (please complete the following information):**
 - NexoPOS: [e.g. v3.14.5]
 - Gastro (if installed) [e.g. 2.3.34]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by mo3men** [comment]
Hi, already select Issue format.
Please consider where is the wrong format issue?

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-24 10:02:41</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-24 10:02:41</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-10 21:36:16</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
