### ISSUE TITLE
Daily email showing 0 sales

### ISSUE THREAD

**Issue by mo3men** [nexopos/v3-issues#170]
**Username** : mo3men
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
Daily email in single and multiple store showing 0 sales. Daily email not showing any data
please find attached file
[daily-report.pdf](https://github.com/nexopos/v3-issues/files/2781607/daily-report.pdf)
  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.14.5]
 - Gastro (if installed) [e.g. 2.3.34]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-24 10:02:41</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-24 10:02:41</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-10 21:36:16</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
After having reviewed the issue on sub stores. The result was successful. Actually it might depends on the timezone defined on the settings.

**Comment by Blair2004** [comment]
We're waiting an update on this before closing the thread.

**Comment by Blair2004** [comment]
Closed because of inactivity.
