### ISSUE TITLE
table name does not appear when Split Orders

### ISSUE THREAD

**Issue by ricidelphy** [nexopos/v3-issues#172]
**Username** : maopedia
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
table name does not appear when Split Orders

**To Reproduce**
Dine in the table after that select the item and hold the order, then split, in split view there will be no customer name, table name & date of order.

**Expected behavior**
the table name, name, customer & date of order must be displayed.

**Screenshots**
I enclose the following screenshot.
![adawdawdaw](https://user-images.githubusercontent.com/10242664/51601171-3a667900-1f36-11e9-8d0c-9f7bbc6a22e4.jpg)

![splittter](https://user-images.githubusercontent.com/10242664/51606747-4c9be380-1f45-11e9-9242-f4e13d0a7133.jpg)

**Environment (please complete the following information):**
 - NexoPOS: v3.14.5
 - Gastro (if installed) [v2.3.34]
 - PHP version [5.6.3]
 - MySQL version [5.6]
 - Devise used (Chrome).

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "ricidelphy" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by ricidelphy** [comment]
opps..sorry sir, my username is: maopedia

Pada tanggal Rab, 23 Jan 2019 17.43 NexoPOS Solutions <
notifications@github.com menulis:

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-07-14 10:18:51</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-07-14 10:18:52</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by ricidelphy** [comment]
yes sir..

Pada tanggal Rab, 23 Jan 2019 18.08 NexoPOS Solutions <
notifications@github.com menulis:

**Comment by Blair2004** [comment]
We'll review your issue and update the thread accordingly, thank you for your time.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-07-14 10:18:51</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-07-14 10:18:52</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, we've been reviewing the error, and that works pretty good from our end. We would like to get in touch with you so that we can take a look in realtime to your system. 

Thanks.

**Comment by ricidelphy** [comment]
okay ready
