### ISSUE TITLE
Kitchen view sorting the orders as newest it should be oldest 

### ISSUE THREAD

**Issue by mo3men** [nexopos/v3-issues#176]
**Username** : mo3men
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
Kitchen view sorting the orders as newest it should be oldest, the priorities should be for oldest orders. as per the screenshots there is 4 test orders this means the order number 4 is the last order was created from POS. In the kitchen view should showing the orders for example order number 001,002,003,004 this is correct but now showing 004,003,002,001 and this is wrong because the chef should start cooking from order number 001 (this is the first order booked from POS).

**To Reproduce**
1. Go to 'Create orders from POS screen'
2. Click on 'Kitchen view'
3. Scroll down to 'look to the order numbers'
4. See error 004, 003, 002, 001 this wrong and should be 001, 002, 003, 004

**Expected behavior**
The priorities should be for oldest orders to start cooking

**Screenshots**
![1](https://user-images.githubusercontent.com/46889122/51672334-4e64b600-1fdc-11e9-8b1c-a8f4e9373bd0.png)
![2](https://user-images.githubusercontent.com/46889122/51672341-51f83d00-1fdc-11e9-9446-6e89eecad4f5.png)

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.14.5]
 - Gastro (if installed) [e.g. 2.3.34]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
I hope to be fixed ASAP.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-24 10:02:41</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-24 10:02:41</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-10 21:36:16</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
this is how your issue should be formatted for the name 
![screenshot-github com-2019 01 24-21-12-15](https://user-images.githubusercontent.com/5265663/51705768-c783fd80-201c-11e9-835f-ed8a2c45c0be.jpg)

**Comment by mo3men** [comment]
Hello Blair

are there any new on this ticket?

**Comment by Blair2004** [comment]
Hi, the ticket is now ongoing, we'll add an option to set the sorting order on Gastro.

**Comment by Blair2004** [comment]
https://github.com/Blair2004/gastro/commit/2f0a342381d26e7a7ad21a8a259afbc1baa0085b
