### ISSUE TITLE
problem when the splitter and merge order, the moved table icon changes to empty & the duration is also lost,

### ISSUE THREAD

**Issue by ricidelphy** [nexopos/v3-issues#177]
**Username** : maopedia
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**

problem when the splitter and merge order, the moved table icon changes to empty & the duration is also lost,

**To Reproduce**
example: table B has 2 items, 1 item is moved to table A which has 1 item, the remaining 1 item in table B, the problem is the table icon moved it turns blank & the duration also disappears,

**Expected behavior**
it should be table B in the condition is being used with the order of 1 more item and the duration is also there.

**Screenshots**
![1](https://user-images.githubusercontent.com/10242664/51790677-31420a00-21cb-11e9-8cea-ddc88da8bd0f.jpg)
![2](https://user-images.githubusercontent.com/10242664/51790678-31420a00-21cb-11e9-9cbf-96040ee655f5.jpg)
![3](https://user-images.githubusercontent.com/10242664/51790679-31daa080-21cb-11e9-8fa1-ce8a7d18002f.jpg)
![4](https://user-images.githubusercontent.com/10242664/51790682-31daa080-21cb-11e9-9239-bbdf5327e79c.jpg)

**Environment (please complete the following information):**
 - NexoPOS: [v3.14.5]
 - Gastro (if installed) [ v2.3.34]
 - PHP version [7.1]
 - MySQL version [5.6]
 - Devise used (Chrome, Firefox).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-07-14 10:18:51</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-07-14 10:18:52</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Thank you for that. We're proceeding to a review. Sorry for the late reply.

**Comment by Blair2004** [comment]
We're currently handly the ticket
Do you know it's possibel to move one item from one table to another, without using the Split & Merge feature ?
