### ISSUE TITLE
Suggestion : Alerte avant expiration du produit

### ISSUE THREAD

**Issue by ismaeladarka** [nexopos/v3-issues#178]
**Username**:  ADARKA
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Possibilité de mettre en place une nouvelle fonctionnalité d'alerte email/notification pour les produits qui expirent bientôt.

**Additional context (optional)**
Nous savons tous que de nos jours les commerçants perdent beaucoup d'argent car souvent la date d'expiration de leurs produits n'est pas consulté.
je pense que cette nouvelle fonctionnalité vas non seulement vous attirer de nouveau acheteurs mais aussi plaire a tous les utilisateur de NEXOPOS.
je vous prie de prendre en charge ma suggestion.
Merci

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-07-18 09:07:55</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Merci pour votre suggestion. Nous allons l'examiner et l'intégrer selon sa pertinence.

**Comment by ismaeladarka** [comment]
Bonjour
D’accord
Je vous remercie pour votre qualité de service et considération irréprochable des clients.





dimanche 3 février 2019 à 19:13 +0100 de notifications@github.com <notifications@github.com>:

Merci pour votre suggestion. Nous allons l'examiner et l'intégrer selon sa pertinence.
