### ISSUE TITLE
Bulk Item Update

### ISSUE THREAD

**Issue by samerkamel** [nexopos/v3-issues#179]
**Username**:  Samerkamel

**Is your feature request related to a problem? Please describe.**
Trying to update multiple items price can be a hassle, as the user must edit each item separately and update the price, also going through importing the items again can cause some issues with inventory. 

**Describe the solution you'd like**
I would suggest in the table of items ( all items list ) the editable fields such as price, category, State, Tax etc... would be clickable and then editable with AJAX save. Also there could be a button that enables editing with that way. 

This will make sure editing items is done easily and efficiently if i only want to update the price for say 15-20 items. 

**Describe alternatives you've considered**
I understand that a new import can be done, but i am worried about messing up stock levels and/or taxes. 

**Additional context (optional)**
You can check https://yithemes.com/themes/plugins/yith-woocommerce-bulk-product-editing/ for an example on how this can be handled. 
<img width="751" alt="screen shot 2019-02-03 at 2 12 03 pm" src="https://user-images.githubusercontent.com/6500550/52176637-16205d00-27be-11e9-9461-e38f8d5bda62.png">

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-15 13:17:03</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-06-15 13:17:04</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-06-15 13:17:04</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Thanks you for your suggestion. We're about to review that and integrate it according to how handy it is.
