### ISSUE TITLE
Gastro module:

### ISSUE THREAD

**Issue by ChaDye** [nexopos/v3-issues#18]
Hello, I am facing a bug when trying to pay an ordre when it's been taken from kitchenette.
I can't pay from register because it's written that the order is already ready.
Waiter can't pay from ready screen, pay button doesn't work.

**Comment by Blair2004** [comment]
Please when you submit your issue, we would like to have more information like all the details of your environment. Consider creating a new issue with all theses details here : https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md
