### ISSUE TITLE
PIN Code Access

### ISSUE THREAD

**Issue by mralexwild** [nexopos/v3-issues#180]
**Username** : mralexwild

**Is your feature request related to a problem? Please describe.**
It takes too long for users to login by email as standard.

**Describe the solution you'd like**
I would like the option for a person to login to the POS screen, Waiter Screen, Kitchen Screen with a (numeric keypad ) Pin Code up to 5 digits. 

When you create a user giving them access you are also given the opportunity to either generate a 4 digit code or create a code (better to generate so it can check if the number is already in use)

**Describe alternatives you've considered**
Fingerprint access

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "mralexwild" on [Nexo Platform](https://api.nexopos.com).
                    Note that, maybe the issue is not well formatted as well, please consider reading [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/). 
                    Regards.
