### ISSUE TITLE
POS PIN Code

### ISSUE THREAD

**Issue by mralexwild** [nexopos/v3-issues#181]
**Username**:  mralexwild

**Is your feature request related to a problem? Please describe.**
It takes too long for users to login by email as standard.

**Describe the solution you'd like**
I would like the option for a person to login to the POS screen, Waiter Screen, Kitchen Screen with a (numeric keypad ) Pin Code up to 5 digits. 

When you create a user giving them access you are also given the opportunity to either generate a 4 digit code or create a code (better to generate so it can check if the number is already in use)

**Describe alternatives you've considered**
Fingerprint access

**Comment by nexopos** [comment]
Hi, after having reviewed your account, we've not been able catch any licences.
                Please note that, it's required to have a licence on your account, in order to receive updates and support. 
                [Click here](https://api.nexopos.com/dashboard/profile/envato-licences/add) to add a new licence to your Nexo Platform account.
                Regards.

**Comment by mralexwild** [comment]
Hi I am not prepared to purchase anything until the software satisfies both me and my client, it doesn't state that I have to purchase a licence if I am enquiring about a feature on your site or in the whatsapp group.

**Comment by Blair2004** [comment]
Hi, i've your read well the message, it's asked to have a licence in order to receive updates and support. By update, we mean from the dashboard and the support is for those facing issues with NexoPOS. This information doesn't apply to you since you're submitting a suggestion.

Thank you.

**Comment by Blair2004** [comment]
Hi, this has been fixed with a module we've recently released.
