### ISSUE TITLE
Importing items doesn't add items to list

### ISSUE THREAD

**Issue by KiahTolliver** [nexopos/v3-issues#183]
**Username** :  CTraxKiah
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
When I import items from a csv file, the items and categories are not added properly to the respective lists

**To Reproduce**
1. Import items via csv
2. Map fields
3. Navigate to Items/category list

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: 3.1.4
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version 7.1
 - MySQL version 5.6
 - Devise used: desktop browser

**Additional context**
![image](https://user-images.githubusercontent.com/4640020/52610214-431fe000-2e4e-11e9-9e7d-ffbf5113601c.png)
![image](https://user-images.githubusercontent.com/4640020/52610221-4e730b80-2e4e-11e9-87a9-8370d6edd7cb.png)
![image](https://user-images.githubusercontent.com/4640020/52610231-592da080-2e4e-11e9-8184-a6264b01ca3a.png)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-07-26 16:48:08</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
hi, can you please provide the file you've attempted to upload ?

**Comment by Blair2004** [comment]
We're still waiting to the file you've used to import the items.

**Comment by KiahTolliver** [comment]
Looks like .csv files aren't supported. I have sent the file to you directly via WhatsApp

**Comment by Blair2004** [comment]
Received. Thank you.

**Comment by Blair2004** [comment]
After having importe the file you've share we've been able to see the product on the POS.
Now the problem might be a PHP error which occur or the confugration of the import.

![image](https://user-images.githubusercontent.com/5265663/52897684-a061bb80-31d7-11e9-8f9b-f3c315f1ee7d.png)
