### ISSUE TITLE
Order Not Printing

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#184]
**Username** : walia7878
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**

**To Reproduce**
create new order 
after add payment order not printing 

**Screenshots**
please see screenshot below

**Environment (please complete the following information):**
 -  NexoPOS v3.14.7 
 -  Gastro v2.3.34 

 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

![capture](https://user-images.githubusercontent.com/32275898/52704897-a3766500-2fa7-11e9-8593-8067e935894c.PNG)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-08-30 00:00:00</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Can you share the file which throw the error ?
application\modules\nexo\inc\models\NexoRewardSystemModel.php
