### ISSUE TITLE
Unit Price in not editable in Nexopos

### ISSUE THREAD

**Issue by Developer-pro** [nexopos/v3-issues#185]
Noman Laghari

I need editable Unit Price 

![image](https://user-images.githubusercontent.com/38200781/53013429-9eae2700-3467-11e9-956b-384da7f5b465.png)

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
hi, your issue doesn't follo the required format in order for us to handle your query. If you need help understand how to post issue, please read this tutorial : 

https://nexopos.com/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/

This thread will be closed. you're invited to create a new one with a valid format.
