### ISSUE TITLE
The program should allow to approve the orders

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#186]
**Username** : israel
Provide username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
The option to approve an order that is made from a store has disappeared

**To Play**

1. Import items via csv
2. Map fields
3. Navigate to Items / category list

** Expected behavior **
The program should allow to approve the orders that are made to warehouse, to be able to discount the warehouse stock and add it to the store.

** Screenshots **
![5a32f272-57ea-4e60-ab97-7a97116b0705](https://user-images.githubusercontent.com/39987937/53326098-04c20080-38e5-11e9-9831-f42fd5a52c33.jpg)

** Environment (please complete the following information): **

* NexoPOS: 3.1.4
* Gastro (if installed) [e.g. 2.3.10]
* PHP version 7.1
* MySQL version 5.6
* Devise used: desktop browser

** Additional context **

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by israelga** [comment]
As it does not have the correct format?

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "israelga" on [Nexo Platform](https://api.nexopos.com).
                    Note that, maybe the issue is not well formatted as well, please consider reading [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/). 
                    Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-22 10:49:30</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by israelga** [comment]
I updated the username of nexopos

**Comment by Blair2004** [comment]
Starting reviewing the issue.

**Comment by Blair2004** [comment]
Hi, we've reviewed the issue and it seems like there is an error from your side. In fact, you've requested a stock from the main warehouse to a substore. In such condition, the main warehouse could'nt allow the stock request he has performed. Here is your steps : 
- From warehouse
- request stock to substore
- from warehouse, try to approve request from warehouse (not possible)

The suggested steps
- From sub store
- request stock to warehouse
- from warehouse, try to approve request (allowed)

Hope that will help you.

Regards.

**Comment by israelga** [comment]
Well, no, the steps that I follow are the same ones that you indicate to me.
