### ISSUE TITLE
permission_manager problem

### ISSUE THREAD

**Issue by giurubino** [nexopos/v3-issues#187]
**Username** : makelink
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug** : using permission manager is imppossible to hide (disallow) invertory menu items. Disallowing one of them disappear all inventory menu. Same thing with report menu item

**To Reproduce**
1. Go to permission manager
2. disable on item of inventory menu
3. all invetory menu disappear
4. no error cant disallow some single items of invetory menu, same thing to report menu

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-07-27 18:40:37</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-07-28 01:44:56</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-08-01 15:09:03</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Note, we'll see what we can do for that.
