### ISSUE TITLE
SOK Modifiers issues

### ISSUE THREAD

**Issue by sysman7** [nexopos/v3-issues#190]
**Username** : sysadmin2
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
There is an issue when adding modifiers into orders made from SOK. First modifiers item images do not display on the SOK pop up screen and second the added modifiers do not add up in the total. The other issue is if customers decide they no longer want a selected modifier it cannot be deselected from the screen. Can you please try to resolve this issue. Thanks

**To Reproduce**
SOK
Item with modifiers
no
no error just images not displaying

**Expected behavior**
This is all on SOK screen
- If a selected item contains modifiers the pop up screen is expected to show the image of a Top In or Add-ons.
- Also once selected if not needed I should be able to remove it.
- The added modifier price should be added to the total  

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.1.4
 - Gastro (if installed) [e.g. 2.3.36]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).
Google Chrome
**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-12-06 15:22:56</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-12-06 15:22:56</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-07-20 02:48:47</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>22714330</td>
                                <td>Self Order Kiosk for NexoPOS</td>
                                <td>2019-06-06 23:25:44</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-06-06 23:25:44</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-07-20 02:48:47</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-12-06 15:22:56</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Thank you for reporting this issue. 
We're reviewing that now.
