### ISSUE TITLE
Combine all items if they are the same in same line in Bill print

### ISSUE THREAD

**Issue by samerkamel** [nexopos/v3-issues#191]
**Username** : SamerKamel

**Describe the bug**
If a client orders the same item multiple times ( on separate orders on Gastro ), when i print the bill each order gets its separate line, even if the item is the same

**To Reproduce**
1- Open POS, and order a water Bottle, Send to kitchen
2- Open same table and order water Bottle, Send to kitchen
3- Print Bill. 

**Expected behavior**
The bill should combine all same items ( if they all have the same price and same discount ) into the same line in the bill to avoid long and lengthy bills.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-15 13:17:03</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-06-15 13:17:04</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-06-15 13:17:04</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi,

Thank you for your interest.

The print cannot combine same item. However, if you want an item to be combined, you can use the "+" button on the item row (on the cart), which increase the quantity instead of adding a new entry. 

The main reason why items can't be combined, it's because of the modifiers. Every similar items should be displayed separated to avoid collusion with modifiers.
