### ISSUE TITLE
Issue in sales report and cash collected

### ISSUE THREAD

**Issue by AUDevz** [nexopos/v3-issues#192]
**Username** : AUDev
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
When you create a sale where the customer pays advance (half of the money from total amount), It save the sale and amount is added to daily sales, but when the customer returns after a day to collect the item and completes the payment, you add the the amount in that sale, that payment is not added on today's cash collected.  So the system is showing less cash then the total cash collected.

**To Reproduce**
1. Go to 'POS'.
2. Add items for 'Sale'.
3. Click on 'Payment'.
4. Click on 'add amount' i.e less than total. 
5. Click on 'save'.
6. Next day add more amount on that sale.
7. Generate report, see error cash not added.

**Expected behavior**
Report should show the amount received from the previous sales and show it like balance received. 

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.14.2]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser Firefox).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-03-08 16:24:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-03-08 16:24:34</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by AUDevz** [comment]
ok i will buy the support, but kindly look at the issue once its genuine,

**Comment by Blair2004** [comment]
Hi, do you target any specific report on your issue ?

**Comment by AUDevz** [comment]
Daily sales and detail report

**Comment by Blair2004** [comment]
I think, we need to create another report which will display the payment made. Because, if we change the order placed at the first time the order has paid half, that will after the data of that day. because the amount will be reflected on a more recent day.  Instead, we can have a report which compute the payment made a specific day. With that it will be more accurate to know when a payment has been made and how many has been made during a day.

**Comment by AUDevz** [comment]
Yes another report  will be fine, which should show how much cash was total
collected, how much was advance taken, how much was complete payment.

When can we expect this update?
