### ISSUE TITLE
daily report but it dosn't send automatically

### ISSUE THREAD

**Issue by alsaihati** [nexopos/v3-issues#193]
**Username** : saihati

**Describe the bug**
In this link in NEXOPOS: /pos/dashboard/stores/7/nexo/settings/reports
It should be send daily report but it dosn't send automatically!!

**To Reproduce**
1. Go to 'Store Setting'
2. Click on 'Reports'
3. Scroll down to 'Admin Email'
4. Will NOT send email!!

**Expected behavior**
I suggest to let send report automatically daily by more configuration. Will be great if it have like detailed report configuration. So I can choose the time (start and end) and select the Format of report like: Detailed or Condensed.

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: v3.14.25
 - Gastro v2.3.37
 - PHP version
 - MySQL version 
 - Devise used: desktop browser.

**Additional context**
It is very important to followup the sales for administration.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-11-22 18:33:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-07-06 15:00:52</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-04-07 11:28:30</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-07-06 15:00:52</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-09-07 12:39:48</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Base on the test that we've made it's working.
Please contact us on WhatsApp so that we can check it on your environement.
![screenshot-mail google com-2019 04 16-10-06-58](https://user-images.githubusercontent.com/5265663/56196791-70943000-602f-11e9-898e-3f5d667d9412.jpg)

**Comment by Blair2004** [comment]
We've made a slight change on the cache. This could affect the issue. We're expecting more details on this. The update will close the issue. But you'll be able to reopen it.

**Comment by alsaihati** [comment]
Actually there is change, first email is received but with zero total. Then after editing on Cron Job it came total amount but it is wrong total. I can't understand how to make it from 10 AM to next day 01 AM??

Can you help in corn setting?
