### ISSUE TITLE
Auto daily report not working

### ISSUE THREAD

**Issue by alsaihati** [nexopos/v3-issues#194]
Username : saihati

Describe the bug
In this link in NEXOPOS: /pos/dashboard/stores/7/nexo/settings/reports
It should be send daily report but it dosn't send automatically!!

To Reproduce

Go to 'Store Setting'
Click on 'Reports'
Scroll down to 'Admin Email'
Will NOT send email!!
Expected behavior
I suggest to let send report automatically daily by more configuration. Will be great if it have like detailed report configuration. So I can choose the time (start and end) and select the Format of report like: Detailed or Condensed.

Screenshots

Environment (please complete the following information):

NexoPOS: v3.14.25
Gastro v2.3.37
PHP version
MySQL version
Devise used: desktop browser.
Additional context
It is very important to followup the sales for administration.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
dupliated of https://github.com/nexopos/v3-issues/issues/193
