### ISSUE TITLE
Kitchen Printer Issue - Printing after disabling kitchen printer

### ISSUE THREAD

**Issue by masthan8** [nexopos/v3-issues#197]
**Username** : masthan
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
I tried to disable the kitchen printer from the gastro features settings and even after that the printer is printing receipts with amount due. For every order its creating 2 receipts now, one while sending to kitchen and other during checkout. 
**To Reproduce**

**Expected behavior**
I tried to disable the kitchen printer from the gastro features settings and even after that the printer is printing receipts with amount due. For every order its creating 2 receipts now, one while sending to kitchen and other during checkout. 
**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12] latest
 - Gastro (if installed) [e.g. 2.3.10]2.3.36
 - PHP version [e.g. 7.1]7.1
 - MySQL version [5.6]5.6
 - Devise used (desktop browser, smartphone, POS system). POS

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-14 08:36:01</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-06-14 08:36:03</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, are you talking about the kitchen print or the sales receipt ?

**Comment by Blair2004** [comment]
Because, from the test i've made, after disabling the print on Gastro settings, nothing was gone to the kitchen (as printing)

**Comment by masthan8** [comment]
Hi Bro,
Sorry, i should have been more precise, yes it's receipt printer, Every time I place an order I am getting 2 receipts, one with amount due and the other during checkout with paid details. change due and all. I just need only one receipt after payment, not after placing the order. How do i do that?

**Comment by Blair2004** [comment]
We've added an option on Gastro to make it possible. The issue will be closed once  the update published.
