### ISSUE TITLE
When i want a detailed report its shows very slow over 2 minutes

### ISSUE THREAD

**Issue by Muhammed1980** [nexopos/v3-issues#198]
**Username** : Abifaisal
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
When i want to see detailed report it tokes over 2 minutes notice that the database size is 13MB and i have totally almost 9000 sale but its doesn't that huge database i think and i contact my hosting firstly and they reply like that 

***************************************************************************************************
Thanks for contacting tech support and I'm sorry to hear about the issue.
 I've checked the error log and it shows your site has been exhausting the PHP memory and time out limit.  For example:

[Thu Apr 11 03:37:31 2019] [warn] [client 85.106.127.0] mod_fcgid: read data timeout in 120 seconds, referer:
http://www.falafl.alrajhisoftshop.com/dashboard/nexo/reports/detailed-sales
[Thu Apr 11 03:37:31 2019] [error] [client 85.106.127.0] Premature end of script headers: index.php, referer:
http://www.falafl.alrajhisoftshop.com/dashboard/nexo/reports/detailed-sale

I've gone ahead and increased the default PHP memory and max execution time limit to help optimize your site. 

memory_limit = 256M
max_execution_time = 500

For instructions on how to configure PHP limits on our system please
***************************************************************************************************
Please help  me solve this problem its very annoying 

**To Reproduce**
1.Got to  http://www.falafl.alrajhisoftshop.com/dashboard/nexo/reports/detailed-sales
Username : admin
Password : 102491
please try to get an  report for 3 month like from 2/01/2019 to 4/14/2019

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]    3.14.25 
 - Gastro (if installed) [e.g. 2.3.10]   2.3.37 
 - PHP version [e.g. 7.1]  7.2
 - MySQL version [5.6]   5.6
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Abifaisal" on [Nexo Platform](https://api.nexopos.com).
                    Note that, maybe the issue is not well formatted as well, please consider reading [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/). 
                    Regards.
