### ISSUE TITLE
Delivery Type Order reflecting as Take Away in Sales List

### ISSUE THREAD

**Issue by masthan8** [nexopos/v3-issues#199]
**Username** : masthan
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
The delivery type order is also reflecting as take away in the sales page list. 

**To Reproduce**
1. Go to '...' Open POS and place an order as delivery type and complete the order.
2. Click on '....'Now click on the sales page in Dashboard and check the sales list.
4. See error - You can see that order listed as take away order. 

**Expected behavior**
Delivery type order should be shown as delivery type in the sales list, 

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12] Latest
 - Gastro (if installed) [e.g. 2.3.10] 2.3.37
 - PHP version [e.g. 7.1] 7.1
 - MySQL version [5.6]5.6
 - Devise used (desktop browser, smartphone, POS system). Desktop, POS

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-14 08:36:01</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-06-14 08:36:03</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
