### ISSUE TITLE
Gastro module - Ready order can't be paid

### ISSUE THREAD

**Issue by ChaDye** [nexopos/v3-issues#20]
**Username**
ChaDy

**Describe the bug**
I am facing a bug when trying to pay an order when it's been already taken from kitchen
- I can't pay from register because it's written that the order is already ready.
- I can't pay from ready screen for the same reason

**To Reproduce**
1. Send order to kitchen
2. Waiter screen - Take order 
3. Go to ' ready orders screen'
4. Click on 'pay that order'
5. See error
![cag](https://user-images.githubusercontent.com/20532812/42738001-4976c6ec-8874-11e8-813f-db76498a558e.jpg)
**Expected behavior**
Pay screen - Success of payment - Ticket printing

**Environment:**
 - NexoPOS: [3.12.14]
 - Gastro [2.3.14]
 - PHP version [7.1]
 - MySQL version [5.6]
 - Device used (desktop browser)

**Comment by Blair2004** [comment]
Thank you for submitting this issue. We'll be reviewing that.

**Comment by Blair2004** [comment]
Here is the test have made.
1 - Send to the kitchen placed on table B
2 - Cook and ready state updated for the item
3 - Come back to the ready orders
4 - Pay the order
![record2](https://user-images.githubusercontent.com/5265663/42961822-dbfacef8-8b87-11e8-9f35-40d85098ffad.gif)

Maybe we've used differents steps.

**Comment by Blair2004** [comment]
Closed due to inactivity.
