### ISSUE TITLE
Licence error

### ISSUE THREAD

**Issue by ibrahimzakzouk** [nexopos/v3-issues#202]
**Username** : 
ibrahim_zakzouk

**Describe the bug**
I need to change server for system .. when I log into 
https://api.nexopos.com/dashboard/
to edit the licence It till me to deactivate it first .. so I go to the last link and removed Licence and unlink it but no I couldn't edit it to make It for the new domain also I couldn't log into the previous one !!!

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-12-14 17:46:41</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2018-12-14 17:46:42</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-12-14 17:46:43</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by ibrahimzakzouk** [comment]
ok , All I need to change main domain, but I couldn't access

**Comment by ibrahimzakzouk** [comment]
When I edit I see this : 
You're not allowed to edit an Activated licence. Please deactivate it first. If the problem persist contact the administrators.

**Comment by Blair2004** [comment]
Alright, we're aware of that issue. We'll review your licence. However note that, deactivating a licence from our ends is limited, because it has to be made from your side : https://nexopos.com/support-terms-licence-policy/

**Comment by ibrahimzakzouk** [comment]
I deactivate It from my previous server and unlink it to use It again with new server .. but It didn't deactivated !! 
so I couldn't edit it

**Comment by ibrahimzakzouk** [comment]
??

**Comment by ibrahimzakzouk** [comment]
All I need to change website domain, Please it still active after I deactivated it , If you can check it or just change main domain It will be good

**Comment by nexopos** [comment]
Hi does the main domain still active ?

**Comment by nexopos** [comment]
I've just noticed that the website remain active. We cannot deactivate the licence on this if it's still active. You can proceed by your own on that active installation as described on : https://nexopos.com/item/nexo-updater/

**Comment by ibrahimzakzouk** [comment]
I do and you can check now with details It deactivated 
http://system.tamaragrill.com
user/pass: shopmanager
but in Licences it still active !! what should I do ???

**Comment by ibrahimzakzouk** [comment]
Now nothing I can do from my side !! waiting for you ..

**Comment by Blair2004** [comment]
Alright, i've deactivated your licence. But you should note that, you should not share credentials here.

**Comment by ibrahimzakzouk** [comment]
Yes but this is demo because I deactivated It so nothing to hide ... Thank you

**Comment by Blair2004** [comment]
Alright. Closing now if your issue is sorted.
