### ISSUE TITLE
Responsive Mode Cart count Bug

### ISSUE THREAD

**Issue by knikolou** [nexopos/v3-issues#204]
I have started to make an APP with  android webview because i need this for waiters .There is a small bug when use POS in responsive mode .When you close an order and returns to main screen the cart count doesnt refresh the number of items .It happens only you use it in a smartphone .Thanks

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
