### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by knikolou** [nexopos/v3-issues#205]
Dear Author There is a good feature to select if you want or not to have a notification that item added to cart .In Pos you can see the left area which the items added but in responsive mode (mobile use) is difficult to check if an item is added .I think is easy but very usefull

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
