### ISSUE TITLE
Cart Count issue when in responsive mode

### ISSUE THREAD

**Issue by knikolou** [nexopos/v3-issues#207]
**Username** : kostasnik
**Describe the bug**
Hello Author .I have started to make an APP with  android webview because i need this for waiters .There is a small bug when use POS in responsive mode .When you close an order and returns to main screen the cart count doesnt refresh the number of items .It happens only you use it in a smartphone .Thanks
**To Reproduce**

**Expected behavior**
When the order is cleared and send to kitchen or paid the cart count must refresh

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: 
 - Gastro 
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used smartphone
![Screenshot 2019-05-01 10 04 27](https://user-images.githubusercontent.com/41227557/57011597-1b4d4680-6c0b-11e9-9d7d-3711bdd50c4c.png)

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-10-29 07:57:49</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
