### ISSUE TITLE
Notification when item added in responsive mode

### ISSUE THREAD

**Issue by knikolou** [nexopos/v3-issues#208]
**Username**:  kostasnik
**Is your feature request related to a problem? Please describe.**
Dear Author There is a good feature to select if you want or not to have a notification that item added to cart .In Pos you can see the left area which the items added but in responsive mode (mobile use) is difficult to check if an item is added .I think is easy but very usefull
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context (optional)**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-10-29 07:57:49</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
