### ISSUE TITLE
Employee schedule control 

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#21]
An interesting function to implement would be a function of entry and exit times for each employee. Think that you do not always have to create an ATM for each employee, maybe you use an ATM for 4 or 5 employees.

So you could implement a schedule control of each employee.

The way to make it simple would be with a record of an individual code and different from each one.

Then have a summary of the entries and exits of each employee.

I hope you understand.

**Comment by Blair2004** [comment]
That will be really easier for us to understand you if your query match the feature format.
https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md

**Comment by israelga** [comment]
I do not understand what you mean by the format, I followed your link and recreated the application.

**Comment by Blair2004** [comment]
When you click on the link, the textarea is populated, you just have to replace the corresponding place.

**Is your feature request related to a problem? Please describe.**
[write here]

**Describe the solution you'd like**
[write here]

**Describe alternatives you've considered**
[write here]

**Additional context**
[write here]

**Comment by nexopos** [comment]
The idea has been stored on the projet https://github.com/nexopos/v3-issues/projects/2
