### ISSUE TITLE
Back Button from subcategories in Self Order POS

### ISSUE THREAD

**Issue by knikolou** [nexopos/v3-issues#210]
**Username** : kostasnik

**Describe the bug**
In self order if you have  for items  Category >subcategory1 >subcategory2
and you go to subcategory2 for example the back button-icon
doesnt work and returns error.
**To Reproduce**

**Expected behavior**
A small fix bug because the user stucks if select subcategory
**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
![Screenshot 2019-05-03 08 59 30](https://user-images.githubusercontent.com/41227557/57121822-8e2cfd80-6d82-11e9-89f2-057c6db73a67.png)

 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-10-29 07:57:49</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-10-29 19:38:18</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>22714330</td>
                                <td>Self Order Kiosk for NexoPOS</td>
                                <td>2019-10-30 12:05:14</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
