### ISSUE TITLE
Table view when working in mobile devices

### ISSUE THREAD

**Issue by knikolou** [nexopos/v3-issues#211]
**Username** :kostasnik
**Describe the bug**
(Gastro) There is an operational problem when working in mobile devices .When you put  a dine in order and you start to select table the layout of the view is a)in left area the  "areas" of the store and in the right area the tables.This design makes very difficult this operation because the images of the tables are very small and "zoom in" because the left area covers almost the 50% of the screen .

**Expected behavior**
The design must be changed so the areas will be in horizontal menu or in other case must be dropdown menu so it will easier to work for example in a mobile phone as a waiter

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-10-29 07:57:49</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-10-29 19:38:18</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>22714330</td>
                                <td>Self Order Kiosk for NexoPOS</td>
                                <td>2019-10-30 12:05:14</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-11-03 14:22:52</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
