### ISSUE TITLE
Order send to kitchen 2 times (before and after payment made)

### ISSUE THREAD

**Issue by tungstalker** [nexopos/v3-issues#216]
**Username** : TungStalker
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
When I send order to kitchen. Kitchen cook & order come to ready orders. When I pay that order. That order come back to kitchen again

**To Reproduce**
1. Go to POS on Store (multistore enabled)
2, Select product to order
3. Click on To Kitchen 
4. Choose Delivery
5. Order to kitchen (Cook, Ready)
6. Pay that Order (Full payment or Choose money to add)
ERROR: 7. Order Appear Again as new order on Kitchen Screen

**Expected behavior**
After payment. Order have to complete after payment. On demo has same problem.

**Screenshots**

**Environment (please complete the following information):**
Nexo Premium  v2.7.8
NexoPOS  v3.14.40
Gastro  v2.3.45
 - PHP version 7.1]
 - MySQL version 5.6
 - Devise used Desktop & Smartphone

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-12-06 11:25:27</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-05-17 08:04:17</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by tungstalker** [comment]
another. The Dine in Order Always come with title is Take Away. That's not right.

**Comment by Blair2004** [comment]
Noted, thank you we'll proceed to a review
