### ISSUE TITLE
Tax Report not working

### ISSUE THREAD

**Issue by tshidisod** [nexopos/v3-issues#217]
Taxes Report on Nexopos not working latest version. When you have tax on products it is calculated on checkout but when you draw a report it does not appear. Secondly the Tax inclusive feature does not work on report to calculate your taxes as deducted on each product your have sold. Please Assist urgently 

**Username** : 
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by Blair2004** [comment]
We'll review the system, meanwhile what is your Nexo Platform username ?

**Comment by Blair2004** [comment]
Looks like it has been solve since the time. Let us know.
