### ISSUE TITLE
Suggestion for notice board on Nexopos

### ISSUE THREAD

**Issue by tshidisod** [nexopos/v3-issues#218]
**Username**: Tshidiso
Solution i would like is to have a Notice board for specific groups of people on Nexopos, like if i need to send notices to all cashiers then they can get that through their notifications area, and that be also visible on the dashboard

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-12-08 18:27:02</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Could you provide a sample of how it could looks like ?

**Comment by Blair2004** [comment]
Closed for inactivity
