### ISSUE TITLE
Tax by product does not appear into invoice.

### ISSUE THREAD

**Issue by NightZpy** [nexopos/v3-issues#219]
**Username** : Nightzpy

**Describe the bug**
When I select product tax in checking tax options, the product tax cannot appear into invoice.

**Expected behavior**
In the invoice should appear the total price for product (price without tax + price with tax) and the tax percent from price without tax.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-01-01 01:50:04</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-01-01 01:50:05</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Your setup informations aren't described on your issue. We cannot proceed. Consider reopening another issue filling out these informations and the issue you're facing.

Thanks.
