### ISSUE TITLE
Product Tax does not appear into invoice

### ISSUE THREAD

**Issue by NightZpy** [nexopos/v3-issues#220]
**Username** : Nightzpy

**Describe the bug**
When I select product tax in checking tax options, the product tax cannot appear into invoice.

**To Reproduce**
1. Go to Checking
2. Click on Iva
3. Select product tax
4. Create a tax into inventary.
5. Create a product.
6. Assign new tax to new product.
7. Go to POS.
8. Print a invoice.

**Expected behavior**
In the invoice should appear the total price for product (price without tax + price with tax) and the tax percent from price without tax.

**Environment (please complete the following information):**
 - NexoPOS: 3.14.41
 - Gastro 2.3.46
 - PHP version 7.1
 - MySQL version 5.7
 - Devise used desktop browser

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-01-01 01:50:04</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-01-01 01:50:05</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
