### ISSUE TITLE
Stock Issue for "Hold" Oder after change Status but the Stock is not Reduce.

### ISSUE THREAD

**Issue by symonpum** [nexopos/v3-issues#221]
**Username**: symonpum

**Describe the bug**
When the I make the Order on POS, and put it into "Hold" status. 
Then, go to Dashboard => Sales => Change the Status of the "Hold" order to "Delivered". I reality, the stock on POS (show remaining quantity) should be reduced (be cause the goods is already "Delivered". 

However, i my case, after i update the status to "Delivered" the remaining amount on POS is not reduce.

**To Reproduce**
1. Go to 'POS'
2. Make a Sales
3. Click on "Hold" and put order Title
4. Click on "Put on Hold"
5. Go go "Sales"
6. see the "hold order" just made, =>  go to " Option drop down menu"
7. choose  "Option"
8. Click on "Details"
9. Change Status: "Delivered"
10. Click "OK"
11. Back to "POS" 
12. See the "Remaining Quantity"  

**Expected behavior**
After Status is updated to Shipped ( Delivered or Done) the Remaining Quantity should be reduce from POS (because the goods is already out from stock, even we not yet the payment).

**Screenshots**
  Pls see the video: https://youtu.be/FFd_UOxRWOc

**Environment (please complete the following information):**
 - NexoPOS: v3.14.47
 - PHP version 7.1
 - MySQL v5.7.23
 - Devise used : desktop browser, smartphone.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-17 11:40:52</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-11-17 11:55:45</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-20 03:25:23</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-12-16 16:52:48</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-12-24 02:47:40</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-12-24 13:51:41</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by symonpum** [comment]
Hello!!any  update sir!!

**Comment by Blair2004** [comment]
Hi, 
Thank you for submitting this issue. We've reviewed the case and it's true. The reason why we won't allow the "status" change to affect the stock, it's because it's just an indicative mention. It can then be changed over and over again, an in such case, we don't want the stock to move from the store and going in according to that change. We, however, believe the stock should be out if the order has been paid. That's what we're gonna commit on the upcoming release and it will close the issue automatically.

Thank you.
