### ISSUE TITLE
Improve Feature to Add Manual Sales in the System

### ISSUE THREAD

**Issue by symonpum** [nexopos/v3-issues#222]
**Username**:  symonpum

**Is your feature request related to a problem? Please describe.**

**1. Add Manual Sales** 

**Describe the solution you'd like**

In my Region, We let the Salesman to go sales the product outside the province, however, those salesman and delivery guys are not able to use any system or understand English. So, we let them sales and write invoices in paper. 

Then, the Accountant, will input that Sales in the System on the Next day, or late more than 2 or 3 days in case salesman went to other provinces in the long distance. 

But, the NexoPOS is not enable above mentioned options yet.

**Describe alternatives you've considered**

So, what i suggest is:( as the following steps)
1.1. When go to Sales => Drop down menu:
1.1.1 New Sales ( that we can put manual sales from the invoice that Salesman wrote from the specific Date, Code (auto) , Product name, Qty, Unit Price, Total Amount....) (if possible can import from *.csv the previous Sales Data in to the System)

1.2.2 POS Sales ( will Directly to POS page for current date)

**2. Inventory Tracking by Each individual Products** 

**Describe the solution you'd like**

2.1. Currently, NexoPOS provide the Inventory Tracking Sheet which can track the inventory by Category only. And also, in this tracking sheet, only provided:
- Incoming Stock (QTY & Value)
- Outgoing Stock (QTY & Value)
=> No "**Balanced Stock**" which i suggest to have that on the Tracking Sheet.

2.2. Inventory Tracking by Each Products (in 1 category  has more than 1 product)

**Describe alternatives you've considered**
So, what i suggest is:( as the following steps)
When open Inventory Tracking Sheet:
=> Option to Choose (Drop down menu or radio button)
 - Stock Tracker by (1. Category, 2. Each Products....)
 - Custom Date Range to Track the Inventory
 - Print/Export that Inventory Tracking report.

**3. Expenses ** 

**Describe the solution you'd like**

3.1. Now nexoPOS is already provided this function to add the expense in to the system. However, the expense is not be able to put customer date of expense.

**Describe alternatives you've considered**
So, what i suggest is:
- When add new expenses, should have the Manual picking up the Date of expenses.

**Additional context (optional)**
If i request both 3 features above, how much I need to pay to upgrade my Nexo system to be better and use able in my case?

I am looking forward to hearing from you asap. 
Thanks

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-17 11:40:52</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-11-17 11:55:45</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-20 03:25:23</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-12-16 16:52:48</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-12-24 02:47:40</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-12-24 13:51:41</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Will be added on NexoPOS 4
