### ISSUE TITLE
Issue : the barcode doesn't appear when the order is being printed (web)

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#228]
**Username** : blair2004

**Describe the bug**
After having placed an order, it looks like the order barcode doesn't appear on web receipt.

**To Reproduce**
1. Place an order
2. Check the receipt
3. See error

**Expected behavior**
We should be able to see the barcode. We do suspect it has something to do with the timing. Needs to make some test to be sure.

**Environment (please complete the following information):**
 - NexoPOS: 3.14.50
 - Gastro : 2.3.51
 - PHP version 7.1
 - MySQL version 5.7

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS Local Dev</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale - Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS SOK</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Multi Online</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Brice Setup</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by vishalwalia1** [comment]
I check the issue , Barcode printed on receipt 

![Capture](https://user-images.githubusercontent.com/32275898/61700968-faecde00-ad5a-11e9-9949-8dcad97516ef.PNG)
