### ISSUE TITLE
Printing Invoice issue on arabic language

### ISSUE THREAD

**Issue by elvessisante024** [nexopos/v3-issues#23]
I try already the system using arabic language but this printing is english character. should be in arabic .

Anyone know how to solve this printing issue for arabic

**Comment by Blair2004** [comment]
The easier way is to convert your tables collations. Here is how id did it using Laragon. The proceess might be the same with PHPmyadmin.
![record3](https://user-images.githubusercontent.com/5265663/42962914-aa188b48-8b8a-11e8-87d2-ea9307f2427a.gif)

**Comment by nexopos** [comment]
Since we didin't get if the issue has been solved so far. The thread will be closed. It can be opened at any time.
