### ISSUE TITLE
disabling dashboard for some users

### ISSUE THREAD

**Issue by kevinrowe333** [nexopos/v3-issues#230]
**Username**:  KEvinrowe333

this is a simple request to have the option for administrator disabling dashboard view for cashiers or other users, they will not see their total sales or any of the information displayed on the dashboard as to prevent them from pocketing any extra funds collected from customer

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-30 18:50:40</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-05-30 18:50:41</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-11-07 04:04:09</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-11-07 04:04:09</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
