### ISSUE TITLE
Kitchen Print not coming out on NPS 2.5.1

### ISSUE THREAD

**Issue by araufqazi** [nexopos/v3-issues#231]
**Username** : arauf.qazi@gmail.com
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
After selecting YES under "ConvertPrinting to Image," the main receipt comes out but the kitchen receipt doesn't.
However, when I select NO under "ConvertPrinting to Image," the kitchen print works. BUT, the main receipt gets weird characters in place of ARABIC text.
So im stuck!
Also, there is no way to add logo to the receipt or change the text size in the settings. Also, I cannot add next paragraph indentations, for example, the order number and date are mentioned together in one line which looks very confusing

**To Reproduce**

**Expected behavior**
I want arabic and english to work seamlessly together on the receipt and to be able to add logos and format the receipts

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: v3.14.49
 - Gastro: v2.3.47
 - PHP version: 7.1
 - MySQL version: 5.6
 - Devise used: Desktop PC, Compostech Model 80300 Thermal Printer

**Additional context**

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "arauf" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by Blair2004** [comment]
Fixed with https://github.com/Blair2004/gastro/commit/4cdb1c5382d3e52bc42357285532a616262276cf
