### ISSUE TITLE
No Sale Receipt 

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#232]
**walia7878** : 

**Describe the bug**
Set option ( YES ) - Convert Printing to Image and also set  ( YES ) - Print Unpaid Receipt from Gastro 

**To Reproduce**
1. Go to 'Invoice settings ' Set option ( YES ) - Convert Printing
2. Go to Gastro Setting - 'Features Control Setting ' then set  ( YES ) - Print Unpaid Receipt 
3. Now send order to Kitchen 
4. you will notice only sale Receipt  no Kitchen Receipt 
5. now set  'Invoice settings ' Set option ( NO) - Convert Printing
6.  Now send order to Kitchen 
7. you will notice o  Kitchen Receipt  and  sale Receipt both print

**Environment (please complete the following information):**
 -  NexoPOS v3.14.51 
 -  Gastro v2.3.52 
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
Explanation for point *4 - you will notice only sale Receipt no Kitchen Receipt but if you set Cash receipts theme (default print out not good please see attachment .
if you select Cash receipts theme (light ) print out really bad too hard too read . please see the attachment 

![22](https://user-images.githubusercontent.com/32275898/62049610-39880a00-b22d-11e9-9f07-d0bc83f4312f.jpeg)
![23](https://user-images.githubusercontent.com/32275898/62049613-3bea6400-b22d-11e9-9e86-85f9a664d1ca.jpeg)

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
