### ISSUE TITLE
 Stock Request Issue

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#233]
Username: walia7878

**Describe the bug**
Stock Request not working from CSV File 

**To Reproduce**
1. Go to Stock Tranfert  then New Request .
2. search the product and select that but it wont selected .
3. now try with CSV after click import Error Occured while adding the item. The item might be missing.

**Expected behavior**

**Screenshots**
please see video below

**Environment (please complete the following information):**
 - NexoPOS v3.14.51
 - Gastro v2.3.52
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

https://drive.google.com/open?id=12zHQKGI6K2ma4Ns1WFfw34IjO3F5PzNF

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).
