### ISSUE TITLE
left menu item USERS LIST (inside store) with BIG BUG

### ISSUE THREAD

**Issue by lrp2019** [nexopos/v3-issues#234]
PEOPLE:  I FOUND A BIG PROBLEM on NEXOPOS:

When enter on a store we have the left menu item USERS LIST and the problem is that after create an user on this page, the user doesnt appears on users page of this USERS LIST left item and when i try to login with this user created nexopos dont recogize like this user dont exist.

The solution is create user on MANAGE USERS left menu item outside a store (only admin access) and assign this use to the store.

The solution is NOT GOOD because when i create a manager for some store, when this managar enter on his store he will see the left menu item USERS LIST and will use it to create a cashier for example anf in this way the manager will discover that NEXOPOS has a BUG.

Please fix it, that in my opinion couldnt ha…
[14:30, 29/7/2019] -: 👁 👀 ☝ ‼‼‼ ☝ 👀 👁
[14:50, 29/7/2019] -: OTHER PROBLEM CAUSED by this problem:

After i tried create an user in the left menu item USERS LIST (inside store) the username stays registered on nexopos.

I discovered this because after try create an user using my name as username on left menu item USERS LIST, i tried create the same user with my name as username in the MANAGE USERS left menu item (outside store) and i received this error message:

"Account already exists on the system with that username. Please enter a different username, or if you forgot your password, please click the link below."
[14:50, 29/7/2019] -: 👁 👀 ☝ ‼‼‼ ☝ 👀 👁
[14:50, 29/7/2019] -: 👁 👀 ☝ ‼‼‼ ☝ 👀 👁
[14:53, 29/7/2019] -: In other words, the left menu item USERS LIST causes 2 PROBLEMS on nexo pos:

1 - the user created doesnt works
2 - the username used before (with no success to create a new user) cant be used again for other user even nexopos telling that the user doesnt exists.

**Username** : 
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Provide" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by lrp2019** [comment]
closed
