### ISSUE TITLE
left menu item USERS LIST (inside store) with BIG BUG

### ISSUE THREAD

**Issue by lrp2019** [nexopos/v3-issues#235]
**Username** :
LEORP

**Describe the bug**
When enter on a store we have the left menu item USERS LIST and the problem is that after create an user on this page, nexopos show message telling that was successfully registered on database and show a EDIT USERT button that if ai click on it go to a page with the same registtration page fields (username, email and pass) but bellow these fields show this php error message:

Um erro do PHP foi encontrado
Gravidade: aviso

Mensagem: propriedade indefinida: stdClass :: $ type

Nome do arquivo: views / edit.php

Número da linha: 136

Backtrace:

Arquivo: /home/pdv/public_html/application/modules/grocerycrud/views/edit.php 
Linha: 136 
Função: _error_handler

File: /home/pdv/public_html/public/modules/grocerycrud/grocery_crud/themes/bootstrap/views/edit.php 
Line: 1 
Função: include_once

Arquivo: /home/pdv/public_html/application/libraries/Grocery_CRUD.php 
Linha: 2782 
Função: incluir

Arquivo: /home/pdv/public_html/application/libraries/Grocery_CRUD.php 
Linha: 1787 
Função: _theme_view

Arquivo: /home/pdv/public_html/application/libraries/Grocery_CRUD.php 
Linha: 4496 
Função: showEditForm

Arquivo: /home/pdv/public_html/application/modules/nsam/controllers/NsamController.php 
Linha: 107 
Função: render

Arquivo: /home/pdv/public_html/application/modules/nsam/controllers/NsamController.php 
Linha: 126 
Função: crud_header

Arquivo: /home/pdv/public_html/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Route/Route.php 
Linha: 119 
Função: call_user_func_array

Arquivo: /home/pdv/public_html/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php 
Linha: 267 
Função: renderRoute

Arquivo: /home/pdv/public_html/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php 
Linha: 52 
Função: routeRequest

Arquivo: /home/pdv/public_html/application/modules/nexo/controllers/stores.php 
Linha: 232 
Função: start

Arquivo: /home/pdv/public_html/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Route/Route.php 
Linha: 119 
Função: call_user_func_array

Arquivo: /home/pdv/public_html/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php 
Linha: 267 
Função: renderRoute

Arquivo: /home/pdv/public_html/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php 
Linha: 52 
Função: routeRequest

Arquivo: /home/pdv/public_html/application/controllers/Dashboard.php 
Linha: 280 
Função: start

Arquivo: /home/pdv/public_html/index.php 
Linha: 283 
Função: require_once

AND IF I go to USERS LIST PAGE, the user doesnt appears on that page like there was no user registerd.

OTHER PROBLEM IS IF I TRY TO LOGIN USING THIS USERNANME AND PASS, nexo pos tells that there is no user with this email or user name. 

The solution to create user is on MANAGE USERS left menu item outside a store (only admin access) and assign this use to the store.

The solution is NOT GOOD because when i create a manager for some store, when this managar enter on his store he will see the left menu item USERS LIST and will use it to create a cashier for example anf in this way the manager will discover that NEXOPOS has a BUG.

OTHER PROBLEM CAUSED by this problem:

After i tried create an user in the left menu item USERS LIST (inside store) the username stays registered on nexopos.

I discovered this because after try create an user using my name as username on left menu item USERS LIST, i tried create the same user with my name as username in the MANAGE USERS left menu item (outside store) and i received this error message:

"Account already exists on the system with that username. Please enter a different username, or if you forgot your password, please click the link below."

In other words, the left menu item USERS LIST causes 2 PROBLEMS on nexo pos:

1 - the user created doesnt works
2 - the username used before (with no success to create a new user) cant be used again for other user even nexopos telling that the user doesnt exists.

**To Reproduce**
When enter on a store we have the left menu item USERS LIST and the problem is that after create an user on this page, the user doesnt appears on users page of this USERS LIST left item and when i try to login with this user created nexopos dont recogize like this user dont exist.

**Expected behavior**
The creation of user must work

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS:  latest version updated inside nexopos update page on 29july2019
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version 7.1
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-06 22:11:05</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-06 22:11:05</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
