### ISSUE TITLE
POS bug when using on mobile device smartphone

### ISSUE THREAD

**Issue by lrp2019** [nexopos/v3-issues#237]
**Username** : 
LEORP

**Describe the bug**
When open the POS screen on mobile device smartphone, the page is turned to a page with 2 tabs (cart tab and products tab) and the problem is: The produsts tab works well but the cart tab, when i click on customer selectable field, the system send me automatically to the product tab again AND in this way i cant use the POS screen on mobile device.

**To Reproduce**
1. Go to ' POS screen using a mobile device smartphone'
2. Click on 'cart tab and on customer selectable field'

**Expected behavior**
The correct should be: after click on customer field continue on cart tab.

**Environment (please complete the following information):**
 - NexoPOS: latest version of 02 august 2019
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used: smartphone.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-06 22:11:05</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-06 22:11:05</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
