### ISSUE TITLE
Logo AND Shop Name Not Being Printed on NPS 2.5.2

### ISSUE THREAD

**Issue by araufqazi** [nexopos/v3-issues#239]
**arauf.qazi@gmail.com** : 
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
The logo in NPS or through URL is not being printed on the receipt being generated through NPS. Also, if i select Store Name, even that doesnt get printed

**To Reproduce**
1. Go to '>>>'

**Expected behavior**
I want the logo to appear on the receipt and the store name to be printed as well

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by vishalwalia1** [comment]
You need to use .png logo file not .jpg file , please check which file you using

**Comment by araufqazi** [comment]
Hi. Do you mean logo for nps or url? in either case, im using png in both

**Comment by Blair2004** [comment]
Hi, i would like to know : 
- Are you using NPS to print a receipt as an image?
- Have you saved your image from NPS (with the first question is "no") and used hashtag ?
- Do you know how to configure logo on NPS (if both previous answers is no)

**Comment by araufqazi** [comment]
Hi,
1. Yes, I'm using NPS to print receipt as an image.
2. I've tried both url logo and shortcode logo through nps. Both don't work
3. Yes, I know how to configure logo for nps

**Comment by vishalwalia1** [comment]
Logo Issue has been Fix
