### ISSUE TITLE
The images are not visible

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#24]
The images are not seen once uploaded
https://www.screencast.com/t/yOqWmX1g1e1k

**Comment by Blair2004** [comment]
We've not yet been able to know why the software behave like so. But, short fix, is to reset the card while opening the POS.
![record3](https://user-images.githubusercontent.com/5265663/42963046-11cb1170-8b8b-11e8-80c9-2d853ad11a62.gif)

**Comment by israelga** [comment]
If that works, but it's not a solution.
