### ISSUE TITLE
"Pay that Order" button prints to both Kitchen & Cashier

### ISSUE THREAD

**Issue by araufqazi** [nexopos/v3-issues#241]
**Username** : 
arauf.qazi@gmail.com

**Describe the bug**
When I select a Ready Order and click "Pay that Order" button, i get prints to both Kitchen & Cashier. Technically it should only print to the cashier printer.

**To Reproduce**
1. Go to 'Ready Orders'
2. Click on 'Pay that Order'
3. See error

**Expected behavior**
Technically "Pay that Order" should only print to the cashier printer.

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [v3.14.56 ]
 - Gastro (if installed) [ v2.3.56 ]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser).

**Additional context**
I just want the POS to work as intended

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "arauf" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by araufqazi** [comment]
Hi,
I dont know why i have to clarify my credentials every single time.
my username is NOT arauf. It's arauf.qazi@gmail.com
I have 2 nexo platform licenses, 1 gastro, 1 nps, and 1 kiosk license.
If this is not enough, let me know.

Thanks.

**Comment by Blair2004** [comment]
No worry we'll handle that.

**Comment by Blair2004** [comment]
With Gastro 2.3.57 (new update), the issue doesn't occur. Consider updating.
