### ISSUE TITLE
Issue in NPS Print

### ISSUE THREAD

**Issue by AUDevz** [nexopos/v3-issues#243]
**Username** : 
AUDev
**Describe the bug**
while printing the NPS there is no option of discount there, there is dine in system waiter punch the menu, its goes in kitchen, it will process and cook, after that waiter come to cashier for bill, cashier give NPS Print to waiter, then waiter goes to client and given the bill and take cash return to the cashier, and then final bill will be print while entering the cash amount given by client and there is option of discount also and on bill its show the discount, but problem is while printing the NPS there is no option of discount and on NPS print receipt there in 0 Discount show, there must be option while printing NPS recepit to show the client how much discount is given before giving the bill

![4883a074-5513-4d4a-b026-c24ce25a3769](https://user-images.githubusercontent.com/49590737/64112066-b7e14a00-cd9f-11e9-92d7-3c36dc2db7a5.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-03-08 16:24:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-03-08 16:24:34</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-02-16 17:35:27</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-16 17:35:27</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, i've read your explanation, but i'm not really sure to understand. Do you mean, the discount doesn't displays well on the receipt ?

**Comment by AUDevz** [comment]
if we click on dine in, we select table, which is busy now cilents want bill there in button NPS Print we click on it a recpit print in which all due amount is shown, but at that time no discount option is there to show in that recpit that we have given how much discount, in that recpiet 0 discount is shown, i am attaching a pic also, discount option is only there show when we pay the bill while entering the amount or full amount
![4883a074-5513-4d4a-b026-c24ce25a3769](https://user-images.githubusercontent.com/49590737/64166951-a6607680-ce61-11e9-8fcc-94904e122fa7.jpg)

**Comment by Blair2004** [comment]
Do you mean that after clicking on "Checkout" from the table history, we cannot apply a discount ?

![image](https://user-images.githubusercontent.com/5265663/64408762-71316f80-d07f-11e9-8ba3-bf412d7518d2.png)

Or do you mean, the Discount displays only when we proceed to a payment ?

**Comment by AUDevz** [comment]
The Discount displays only when we proceed to a payment, so we can not
show the customer, the bill with discount, so he can pay.

Also if you edit the order from hold it does not get edit it gives error
payment not processed or something,

we are now printing the due bill and writing discount by hand which looks
very bad.

Also if

**Comment by Blair2004** [comment]
I think i understand... you would like to apply a discount on an order before the payment and want it to be shown so that the customer could pay the final due. Here is the solution, if you would like to do that, Open that order from the hold order (you can search the order using the code), then apply the discount and click on "send to the kitchen", but it won't work if the cooking process has yet started. I

Normally we would have added that feature, but we're no more adding new features to NexoPOS 3.x as improving that delay the development of the version 4.x, you can, however, be sure that this feature will be added on the next generation (4.x)

**Comment by AUDevz** [comment]
So when might 4.x be released.
