### ISSUE TITLE
Issue : Customer Credit Numpad disappearing 

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#244]
**Username** : blair2004

**Describe the bug**
It looks like if you open a discount popup while being at the Customer Credit payment tabs, closing the discount popup makes the customer credit Numpad to disappear as well at the same time.
![image](https://user-images.githubusercontent.com/5265663/64166044-2e348980-ce3e-11e9-9ef4-494ce88a5418.png)

**To Reproduce**
Process an order and open the payment box. Select the customer account, open and then close the discount popup.

**Expected behavior**
The discount popup shouldn't have any effect on the customer account Numpad.

**Environment (please complete the following information):**
 - NexoPOS: 3.14.62
 - PHP version 7.1
 - MySQL version 5.7
 - Devise used (desktop browser, smartphone, POS system).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS Local Dev</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale - Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS SOK</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Multi Online</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Brice Setup</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS Local Dev</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale - Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS SOK</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Multi Online</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Brice Setup</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
