### ISSUE TITLE
Ready to Order 

### ISSUE THREAD

**Issue by Johnmk** [nexopos/v3-issues#246]
User Name : Muhammad khan
Issue: 
When i add item in order through Dine in Option so in the ready to Order Panel the Order Invisible this happened just when we add new item by Dine in please resolve it this issue facing since 1 week

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
