### ISSUE TITLE
Item add in order Issue

### ISSUE THREAD

**Issue by Johnmk** [nexopos/v3-issues#247]
Username : Muhammad khan
Issue:
When i add item in order through Dine in Option so in the ready to Order Panel the Order Invisible this happened just when we add new item by Dine in please resolve it this issue facing since 1 week

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Johnmk** [comment]
I selected  Correct format i have issue so i select Issue option

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by Blair2004** [comment]
When a new items is added to an order which was ready the status change from ready to ongoing or pending. This order couldn't then appear on the *Ready orders* popup because it's not more ready when a new item is added.
