### ISSUE TITLE
Bugs in Sale List and System Slow 

### ISSUE THREAD

**Issue by Johnmk** [nexopos/v3-issues#248]
Username: Muhammadkhan

Issue: 
1: In Sale List Title Showing Wrong Record i Placed order Dine in but in Sale list Showing Take away
2: After update System and print option getting so slow 
3: New bugs after update when i pay order from ready to order so after checkout before print option table option window is opened

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
