### ISSUE TITLE
Issue Sale List and Check out

### ISSUE THREAD

**Issue by Johnmk** [nexopos/v3-issues#249]
**Username** : MUHAMMADKHAN

**Describe the bug**
1.Issue in Sale List Title i m taking all order Dine In But in Sale list Title showing Take away
2. After Update When i do check out from ready to order option so after Check out the table option Opened before Print  

**To Reproduce**
Go to Sale list Check a Tile Col 
Go To ready to Order Click in Pay to Order then Click in Full Payment 

**Expected behavior**
Title Issue in Dine In and Take away at Sale List 
Table option open during check out order

**Environment (please complete the following information):**
 - NexoPOS: v3.14.63
 - Gastro (if installed) v2.3.59
 - PHP version: 7.1
 - MySQL version: 5.6
 - Devise used (desktop browser, smartphone, POS system).

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Muhammad" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by Johnmk** [comment]
User Name : MUHAMMADKHAN

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-01-19 09:50:03</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-01-04 13:06:37</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Johnmk** [comment]
Any Update Regard my query

**Comment by Blair2004** [comment]
fix https://github.com/Blair2004/gastro/commit/09d85c8a167dc4b4e45f381c4ed04d72cd087e8b
