### ISSUE TITLE
Issue : Printing receipt as image doesn't show modifiers

### ISSUE THREAD

**Issue by xmarios** [nexopos/v3-issues#250]
**Username**: xmarios

**Describe a bug**
If you choose to print a receipt as an image it doesn't show the chosen modifiers

**Environment**
NexoPOS: 3.14.61
Gastro: 2.3.57
PHP: 7.1
Browser: Chrome
Using Nexo Print Server

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by Blair2004** [comment]
Fixed https://github.com/Blair2004/nexopos/commit/1cf7c2b3fda5cd2e6e5e629a5b21d5474b433f8f
