### ISSUE TITLE
Send each product ready to the waiter screen

### ISSUE THREAD

**Issue by Miguelin96** [nexopos/v3-issues#253]
**Username**:  Miguelin_96
**Is your feature request related to a problem?** NO

**Describe the solution you'd like**
How could it be done to send each product ready to the waiter screen, because in this way until all the products are not ready it is not sent to the  waiter screen

**Describe alternatives you've considered**
In addition, if there are 3 hamburgers and you have prepared 2, just let them prepare all 3 at the same time, so until 3 are not ready, it does not appear on the waiter screen

**Additional context (optional)**

![WhatsApp Image 2019-09-25 at 17 47 25](https://user-images.githubusercontent.com/54648539/66589902-de10bb80-eb8f-11e9-894e-54ef89fe5bf4.jpeg)

Thanks to the whole team and congratulations for the support shown in the problems

**Comment by Blair2004** [comment]
Thank you. We'll consider this as one of the latest things on Gastro. Meanwhile, we have ongoing stuff but we'll be back once we're ready to handle this.

**Comment by Blair2004** [comment]
With the modification we did, now each single product even similar are handled separately. They can then be send individually to the waiter once ready.
