### ISSUE TITLE
Unwanted code in the first line of receipt printed by NPS

### ISSUE THREAD

**Issue by abdulsamad544** [nexopos/v3-issues#254]
Username: arrozypk

**Describe the bug**
NexoPOS Print server prints strange code in the first line of the receipt. The random unwanted code "H00" comes when the orders are punched rapidly but doesn't comes in the day start or if the receipt is printed after a while e.g 30mins. It also only comes when the order is printed via NPS.

**To Reproduce**
1. Open 'Register or POS'
2. Click on 'Items'
3. Click Pay and then Full payment
4. Observe receipt payment

**Expected behavior**
First line of the printer is displaced by random code 'H00'

**Screenshots**
![IMG-20191017-WA0012](https://user-images.githubusercontent.com/44818072/67038257-7ed71c00-f138-11e9-98e5-ad8117483f71.jpeg)
![20191017_153812](https://user-images.githubusercontent.com/44818072/67038297-8b5b7480-f138-11e9-8f78-ed3213fb5bce.jpg)

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.70]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.5]
 - Devise used (Chrome on HP ap5000 POS).
 - Printer: Epson TM-20 Receipt

**Additional context**
NexoPOS Print Server doesn't works on Windows 10.

**Comment by Blair2004** [comment]
Hi, which printer are you currently using ?

**Comment by Blair2004** [comment]
Can you send the image you've used on your receipt ?

**Comment by abdulsamad544** [comment]
Yes I can send the image,
https://accounts.arrozy.com.pk/images/arrozy-logo300.png

I am using Epson TM-20 Receipt printer

Thanks and Best Regards,
Abdul Samad

________________________________

**Comment by vishalwalia1** [comment]
Issue With Customer Printer Not With NexoPOS or NPS . Mark Issue **Close**

**Comment by abdulsamad544** [comment]
Thanks for diagnosing the problem @vishalwalia1
