### ISSUE TITLE
Error calculation value in SOK 

### ISSUE THREAD

**Issue by oraiox** [nexopos/v3-issues#256]
**Username** : 
raiox

**Describe the bug**
When choose some product in SOK frontend and put some modifiers with additional value to the product when the order is complete the final receipt and order will be with an error in value calculation to more.

**To Reproduce**
1. Go to SOK frontend and take some product with modifier with additional value
2. Just finalize the order
3. Go to "Sales" screen on nexo and take the same order
4. See error on value.

**Expected behavior**
The correct value of the order.

**Environment (please complete the following information):**
 - NexoPOS: [last version]
 - Gastro (if installed) [last version]
 - PHP version [7.1]
 - MySQL version [5.6]

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-05-27 16:54:26</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-03-27 19:18:00</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>22714330</td>
                                <td>Self Order Kiosk for NexoPOS</td>
                                <td>2020-05-20 23:44:12</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-05-27 16:56:44</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Thank you for having submitted we'll review.
