### ISSUE TITLE
With register Number of NPS print copies doesn’t work with Convert Printing to Image

### ISSUE THREAD

**Issue by shafigz** [nexopos/v3-issues#259]
**Username** : Digitalstyle
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
With register Number of NPS print copies doesn’t work with Convert Printing to Image

**To Reproduce**
1. Go to ''select Number of NPS print copies'
2. Click on '2'
3. Convert Printing to Image > yes
4. Use cash registers > yes
5. add registers 
6. use register 
4. See error no more one copy of reciept 

**Expected behavior**
print 2 copies

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [v3.14.77 ]
 - Gastro (if installed) [v2.3.73 ]
 - PHP version [ 7.2.10 ]
 - MySQL version [10.1.43-MariaDB]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-05-09 14:22:14</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-08 09:08:14</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-05-09 14:22:15</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-25 09:02:23</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Thanks for submitting we'll take a look

**Comment by shafigz** [comment]
register not print at all with new update

**Comment by Blair2004** [comment]
Hi, based on our test it works. Consider sharing your setup credentials privately at contact@nexopos.com we'll take a look.
