### ISSUE TITLE
Ready order can't be paid

### ISSUE THREAD

**Issue by ibrahimzakzouk** [nexopos/v3-issues#26]
**Username**
 ibrahim_zakzouk

**Describe the bug**
hello, when trying to pay an order when it's been already taken from kitchen

I can't pay from register because it's written that the order is already ready.
I can't pay from ready screen for the same reason

To Reproduce

1- Send order to kitchen
2- Waiter screen - Take order
3- Go to ' ready orders screen' or from 'dine in table'
4-Click on 'pay that order'
5- for the first time message said that processing but the order didn't complete and still be in 'Quotation' statue
6- when I try to pay the same order again error message said that order is empty but still in 'Quotation' statue and couldn't be complete

Environment:

-NexoPOS: [3.12.14]
-Gastro [2.3.14]
-PHP version [7.0]
-MySQL version [5.6]
-Device used (desktop browser(chrome and safari , mobile browser )

Please respond quickly because the I couldn't run the script until this issue and this issue done success 
..With my Thanks for great efforts

**Comment by Blair2004** [comment]
![record3](https://user-images.githubusercontent.com/5265663/42963393-056a1de4-8b8c-11e8-9a12-298226500404.gif)
Here is what happen, when i'm trying to reproduce the issue.

**Comment by ibrahimzakzouk** [comment]
if you sell grouped product is (STOCK_ENABLED = 1) you will see the issue

**Comment by Blair2004** [comment]
Oh okay.

**Comment by Blair2004** [comment]
Even with grouped item, the sale can be proceeded.

**Comment by Blair2004** [comment]
![record3](https://user-images.githubusercontent.com/5265663/42963732-fe72fa6e-8b8c-11e8-8ce0-e3c403b63107.gif)

**Comment by ibrahimzakzouk** [comment]
all run success unless the stock_enabled in grouped item = 1 in database ... so I couldn't make the grouped item use the stock because in this case it doesn't accept payment in ready orders ... you can check

**Comment by ibrahimzakzouk** [comment]
insure that stock_enabled= 1 in database because if you make stock enable from the system it probably still not done and still = 2 in database

**Comment by Blair2004** [comment]
OK, let me try that.

**Comment by Blair2004** [comment]
It seems like it wasn't possible to edit a grouped item. The issue has been fixed.

**Comment by ibrahimzakzouk** [comment]
I don't understand that ?!

**Comment by Blair2004** [comment]
Check if you can edit a grouped item, and let me know.

**Comment by Blair2004** [comment]
I'm testing with the stock enabled set to 1
![image](https://user-images.githubusercontent.com/5265663/42964410-d6c17cb4-8b8e-11e8-8451-b160842f0e0f.png)

**Comment by Blair2004** [comment]
issue found

![record3](https://user-images.githubusercontent.com/5265663/42964464-065a7d86-8b8f-11e8-9df0-287494e820cf.gif)

**Comment by ibrahimzakzouk** [comment]
from link like this : http://yourdomin/dashboard/stores/1/nexo/grouped-items//edit/ID_of-product

**Comment by Blair2004** [comment]
now, when you'll click on edit, if the item is a grouped item, you'll be redirected to the correct UI

**Comment by ibrahimzakzouk** [comment]
yes ..thats what I talking about

**Comment by Blair2004** [comment]
Issue fixed, the next update will offer the fix.
