### ISSUE TITLE
Issue : Incomplete order after clicking on Full Payment

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#260]
**Username** : blair2004
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug** : this doesn't occur quite often. A proper cause needed to be found. Having Gastro disable and clicking on Full Payment, makes the order incomplete. Maybe this is related to third-party module. An investigation is required.

**Expected behavior**
The Full Payment button should make a full payment on the current order

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.15.0
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS Local Dev</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale - Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS SOK</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Multi Online</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Brice Setup</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro Local Dev</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Remote Dev</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
