### ISSUE TITLE
Register print doesn't work with the new update

### ISSUE THREAD

**Issue by shafigz** [nexopos/v3-issues#262]
**Username** : Digitalstyle
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**

Register print doesn't work with the new update

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [v3.15.0  ]
 - Gastro (if installed) [v2.3.75 ]
 - PHP version [ 7.2.10 ]
 - MySQL version [10.1.43-MariaDB]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-05-09 14:22:14</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-08 09:08:14</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-05-09 14:22:15</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-25 09:02:23</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, have you checked that your printing option is set to registers printers ?

![screenshot-nexopos go-2019 12 10-15_11_01](https://user-images.githubusercontent.com/5265663/70536598-50d1ef00-1b5f-11ea-9002-e0e6936bf577.jpg)
