### ISSUE TITLE
 I suggest to make it as button or change the register name as opening register link

### ISSUE THREAD

**Issue by shafigz** [nexopos/v3-issues#264]
**Username**:  Digitalstyle

**Is your feature request related to a problem? Please describe.**
It is not easy to open or click choosing register from drop down list of options , I suggest to make it as button or change the register name as opening register link

**Describe the solution you'd like**
 I suggest to make it as button or change the register name as opening register link
![1](https://user-images.githubusercontent.com/28713984/70611563-71a94b80-1c16-11ea-8291-c4570753292c.png)

**Describe alternatives you've considered**

**Additional context (optional)**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-05-09 14:22:14</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-08 09:08:14</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-05-09 14:22:15</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-25 09:02:23</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Thank you for the suggestion. However, this modification doesn't look handy. The purpose of a dropdown is to group similar feature. It's pointless to have those features separated that much. Could change our minds of this according to the community thoughts.
