### ISSUE TITLE
Ready order Screen Not Showing Takeaway And Delivery Order 

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#265]
**walia7878** : 

**Describe the bug**
After order ready from kitchen screen only dine-in order show in Ready orders  in POS , 

**To Reproduce**
1. Go to 'Pos and send order to kitchen as takeaway order'
2. now make 'order ready'
3. go to 'POS screen and click Ready orders'
4. you will see there is no order

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.15.1]
 - Gastro (if installed) [e.g. 2.3.75]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
What is the status sof ar ?
