### ISSUE TITLE
Apply Coupon Code Doesn't Work - Payment Failed

### ISSUE THREAD

**Issue by adikuntz** [nexopos/v3-issues#268]
We use the latest version of Nexopos and Gastro.
When we use the voucher code at the cashier, the transaction amount was discounted. But during the payment, the transaction cannot be processed, the receipt does not come out. we attach an error in the following image. 
![mlyd-vchr](https://user-images.githubusercontent.com/59351743/71568433-cba47f00-2af9-11ea-872f-5d77f63971e6.jpeg)

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Hi, this issue is not well-formatted, please consider creating a new one where we can have : 
- Your username
- Your NexoPOS version.
