### ISSUE TITLE
The sales graph is not displayed.

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#27]
When you make a sale the chart on the control panel does not show the sales on the chart.

This video shows you https://www.screencast.com/t/BKR4QPoDqE

**Comment by ibrahimzakzouk** [comment]
Hello Thats may help you ....You can check location of this file in your script files: http://yourdomin.com/public/modules/nexo/bower_components/chart.js/dist/Chart.min.js
as the folder "Chart.js/" may start with capital ..change it in small form to be "chart.js/"

**Comment by israelga** [comment]
Ok, I modified the folder and now it works. Thank you.

**Comment by Blair2004** [comment]
The issue has been fixed on the core.
