### ISSUE TITLE
Modifier price not update when open from hold order

### ISSUE THREAD

**Issue by kxygol** [nexopos/v3-issues#270]
**Username** :  kxygol
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
When add menu with modifier, POS show normal price.
base price + modifier price = menu price with modifier
but when this order put on hold. and open again.
it shows only base price without modifier price

**Expected behavior**
show base price + modifier price = menu price with modifier

**Screenshots**
![1](https://user-images.githubusercontent.com/12599903/71983545-9d414500-3259-11ea-9230-7d00f03ce457.jpg)
Order with modifier before put on hold

![2](https://user-images.githubusercontent.com/12599903/71983601-bba74080-3259-11ea-87c3-d0eda234812b.jpg)
order in hold still normal.

![3](https://user-images.githubusercontent.com/12599903/71983686-e5606780-3259-11ea-95d3-34603ec09b44.jpg)
but when i open it, the price show wrong.

**Environment (please complete the following information):**
 - NexoPOS: 3.15.6
 - Gastro 2.3.76
 - PHP version 7.1
 - MySQL version 5.7
 - Devise used - desktop browser

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-06-18 00:38:39</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-02-05 14:51:13</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-06-17 07:51:57</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Verification in progress.
