### ISSUE TITLE
Discount re-added when order getting paid 

### ISSUE THREAD

**Issue by xmarios** [nexopos/v3-issues#271]
**Username** : 
xmarios

**Describe the bug**
When you add discount to an order then it was re-added when the order got paid

**To Reproduce**
1. Add items on cart
2. Add discount (for example 50%)
3. Send order to kitchen 
4. Get paid for the order
5. Discount re-added 

**Environment (please complete the following information):**
 - NexoPOS: 3.15.7
 - Gastro (if installed) 2.3.75
 - PHP version 7.2
 - MySQL version 5.6

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-07-10 17:51:27</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-12-06 11:37:42</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-12-06 11:37:41</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, thank you for having submitted your issue here.
When you add a discount on an order and pay that directly this issue occurs?
Or the order is saved first on hold?

**Comment by Blair2004** [comment]
Hi, could you please provide more information as requested above?

**Comment by xmarios** [comment]
> Hi, thank you for having submitted your issue here.
> When you add a discount on an order and pay that directly this issue occurs?
> Or the order is saved first on hold?

Hello, this happens when the order gets on hold, not when it gets paid directly.

Also, when we add the discount on the item it works fine, but when we add the discount on cart (the button next to "hold") it is not calculated correctly.

**Comment by Blair2004** [comment]
Thank you for the clarification. We're proceeding the review.

**Comment by Blair2004** [comment]
![screenshot-70 38 66 76-2020 01 15-11_59_48](https://user-images.githubusercontent.com/5265663/72428867-df551400-378e-11ea-8d3c-c455b1e3bc0a.jpg)
Based on the first test we did... it's working properly for that order that has been saved (hold) with a discount.

Could please let us know : 
- Which type of discount have you applied
- Does your system is modified by you anyhow? 
- Are you using a customized module made by us or anyone else?
- We might need to take a look at your system

**Comment by Blair2004** [comment]
Closing the issue for inactivity.
