### ISSUE TITLE
cancel any item from dine in tables is not working  

### ISSUE THREAD

**Issue by haysamelmasry** [nexopos/v3-issues#273]
**Username** : 
haysamelmasry

**Describe the bug**
About gastro , I can't cancel any item if i send it to the kitchen for the dine in option every time i press cancel and then yes it didn't react and the item is still there
**To Reproduce**
1. Go to 'registers and Register list and open register  '
2. Click on 'add any item to the cart and to kitchen '
3. open the 'dine in and open the table number and try to cancel any item '
4. nothing deleted 

**Expected behavior**

**Screenshots**
[https://streamable.com/s/9mpug/wrsayn](url)

**Environment (please complete the following information):**
 - NexoPOS: [3.15.7]
 - Gastro : [2.3.79]
 - PHP version [7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser).

*Additional context**
i have the same issue on waiter screen collect didn't react as well ,

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-06-29 16:26:26</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-06-27 23:54:57</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-06-27 23:54:58</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
