### ISSUE TITLE
Partially pay order

### ISSUE THREAD

**Issue by xmarios** [nexopos/v3-issues#277]
**Username** : 
xmarios
**Describe the bug**
Checkboxes should be added next to each item on table popup, in order to allow partial payment of an order. Also, when an order get paid partially, the balance remains the original and not the original minus the payment(s) that have already been done.

**To Reproduce**
1. Go to POS
2. Click on Dine In
3. Go to an open table
4. There should be checkboxes next to each item
5. Also when click checkout the balance should be the original minus any payments that have been done

**Screenshots**
Sent whatsApp a video

**Environment (please complete the following information):**
 - NexoPOS: 3.15.7
 - Gastro (if installed) 2.3.75
 - PHP version 7.2
 - MySQL version 5.6

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-07-10 17:51:27</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-12-06 11:37:42</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-12-06 11:37:41</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
We won't apply this change to the core regarding the checkboxes. However, regarding the balance not updated could you provide a screenshot?

**Comment by Blair2004** [comment]
Closed for inactivity.
