### ISSUE TITLE
Add Item to an order sends the whole order again to the kitchen

### ISSUE THREAD

**Issue by xmarios** [nexopos/v3-issues#278]
**Username** : 
xmarios

**Describe the bug**
Sending an additional Item to the kitchen should not send the whole order again to the kitchen, but only the new items.

**To Reproduce**
1. Go to POS
2. Click on Dine In
3. Click on an open table
4. Click on Add Item
5. Select an item and send it to the kitchen

**Expected behavior**
Only the new item(s) should be sent to the kitchen. Also the kitchen timing should start from the beginning.

**Screenshots**
Have sent to WhatsApp

**Environment (please complete the following information):**
 - NexoPOS: 3.15.7
 - Gastro (if installed) 2.3.75
 - PHP version 7.2
 - MySQL version 5.5

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-07-10 17:51:27</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-12-06 11:37:42</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-12-06 11:37:41</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>
