### ISSUE TITLE
After update my waiter screen and  Ready Orders are not working

### ISSUE THREAD

**Issue by mayswe** [nexopos/v3-issues#279]
**Username** : 
mayswe

**Describe the bug**
After version update my waiter screen and  Ready Orders are not working

**To Reproduce**
1. I order 2 items at pos screen
2. and click to kitchen and select one table and done
3. I go to kitchen screen and cook 
4. two ready item are not appear at waiter screen popup at pos page
5. so I click ready orders button at pos page, I can see waiter screen have ready meals. so I collect this two meals and click again ready orders button to pay money. this waiter screen have two meals again appear. pls fix me this issue.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS  v3.15.7
 - Gastro  v2.3.80
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (laptop browser safari, chrome).

**Additional context**
previously waiter screen and ready orders is working but after update your new version this two thing are not working. so I cannot do anything.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-02-10 18:23:52</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-02-09 07:33:08</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by mayswe** [comment]
I'm using gastro restaurant. Why I have Not used? What should I change?

**Comment by Blair2004** [comment]
Don't worry about that.

**Comment by mayswe** [comment]
Hello pls reply me. now my restaurant cannot use software.

**Comment by Blair2004** [comment]
Hi, please contact me on WhatsApp, i'll review your installation.
