### ISSUE TITLE
Checkout translate "To Kitchen" button

### ISSUE THREAD

**Issue by kxygol** [nexopos/v3-issues#28]
**Username**
Kxygol

**Need to change**
Translate not working in gastro checkout "To Kitchen"

**Solution**
1. File application\modules\gastro\views\checkout\pay_button.php, line 4 change 'nexo' to 'gastro'

**Screenshots**
![fix-translate-gastro-kasir-tokitchen1](https://user-images.githubusercontent.com/12599903/42925094-809a7cc0-8b5f-11e8-9818-7ff6aecefb1a.jpg)

![fix-translate-gastro-kasir-tokitchen](https://user-images.githubusercontent.com/12599903/42924661-d413e906-8b5d-11e8-89fc-843b50173118.jpg)

**Environment (please complete the following information):**
 - NexoPOS: 3.12.14
 - Gastro: 2.3.14
 - PHP version 7.1.18
 - MySQL version: mariaDB 10.1.33
 - Devise used: desktop browser, android smartphone

**Comment by Blair2004** [comment]
Thank you for the suggestion. The issue has been solved.
