### ISSUE TITLE
Order Code Not Genrated when using Register 

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#280]
**Username** : 
walia7878

**Describe the bug**
cant create new order code with register 

**To Reproduce**
1. enable register and create 2 register 
2. set order Code Types (date coded)
3. now open both register same time and send 2 order to kitchen from one register 
4. now open second register and try to send order to kitchen and you will see error 

**Expected behavior**
order code not created 

**Screenshots**
check screenshot below
![3](https://user-images.githubusercontent.com/32275898/72791438-55f58400-3c5d-11ea-8147-bb3a36c754b5.jpg)
![2](https://user-images.githubusercontent.com/32275898/72791460-5db52880-3c5d-11ea-98b0-b6c042ecd621.jpg)

**Environment (please complete the following information):**

 - NexoPOS v3.15.7
 - Gastro v2.3.80
 - PHP version 7.1
 - MySQL version 5.6
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-08-30 00:00:00</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2017-12-28 10:37:47</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
![screenshot-nexopos go-2020 01 24-00_42_03](https://user-images.githubusercontent.com/5265663/73033483-6d419680-3e42-11ea-99db-f33a6a34e74a.jpg)
Unable to reproduce the issue following the steps.

**Comment by Blair2004** [comment]
Does that occur on a plain NexoPOS installation with no customs modules ?

**Comment by vishalwalia1** [comment]
Issue has been fix , there was few file missing in customer installation, after upload those files issue fix.
