### ISSUE TITLE
Coupons aren't working

### ISSUE THREAD

**Issue by mahmoud-Elshahawy** [nexopos/v3-issues#281]
**Username** : bridge
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
when i am trying to make any payment including coupon it says that payment couldn't be done

**To Reproduce**
1. Go to 'pos'
2. Click on 'pay'
4. See error 'payment couldn't be done'

**Expected behavior**
it should remove the amount of coupon from the total amount to be paid and the remaining amount should be paid by any other method
**Environment**
 - NexoPOS: [3.15.7]
 - Gastro (if installed) [2.3.80]
 - PHP version [7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, POS system).

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-03-25 15:22:03</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-03-25 15:22:03</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-04-06 12:08:15</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
