### ISSUE TITLE
permission CREATE SUPPLIERS also give permission to WAREHOUSE SETTINGS

### ISSUE THREAD

**Issue by lrp2019** [nexopos/v3-issues#282]
**Username** : leorp
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
WHY when i give this permission Create suppliers (nexo.create.providers) to a role, the users in this role can see the left menu item WAREHOUSE SETTINGS if on these settings nothing is about SUPPLIERS ?
I made several tests enabling permission per permission of permissions list in the admin page dashboard/users/permissions and only when i enable this permission Create suppliers (nexo.create.providers) for some role this left menu WAREHOUSE SETTINGS appears for this role users.

**To Reproduce**
1. Creates an user with any role
2. Go to .../dashboard/users/permissions
3. Click on MANAGE PERMISSION
4. Check the option "nexo.create.providers"
5. Login this user and see on dashboard page that this user can access the option WAREHOUSE SETTINGS on left menu 

**Expected behavior**
I have certain the user shouldnt have access to this WAREHOUSE SETTINGS option just because he has access to creates supplier.

**Screenshots**
no applicable

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP 7.1
 - MySQL version 5.6
 - chrome firefox, edge

**Additional context**
no applicable.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-06 22:11:05</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-06 22:11:05</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-06 22:11:05</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-06 22:11:05</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by nexopos** [comment]
Hi, i've reviewed your account on [Nexo Platform](https://platform.nexopos.com), it seems like you no longer have valid licences. 
                Please note that in order to receive support and updates, your licences (purchase code) need to be renewed on CodeCanyon.

**Comment by Blair2004** [comment]
review pending @nexopos
