### ISSUE TITLE
Pin Login can't work

### ISSUE THREAD

**Issue by doitcoid** [nexopos/v3-issues#286]
**Username** : andhyreeza
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
Pin login can't use, only stuck

**To Reproduce**
1. Go to 'login'
2. Click on 'Pin login --> Insert pin --> Submit'
3. See error

**Expected behavior**
The program can use Pin login too.

**Screenshots**
http://prntscr.com/qter2l (Pin login stuck)

**Environment (please complete the following information):**
 - NexoPOS: [v3.15.10]
 - Gastro (if installed) [v2.3.80]
 - PHP version [e.g. 7.1.30]
 - MySQL version [5.7]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
Please ASAP, please repair this bug.

**Comment by Blair2004** [comment]
Can you check whether the Frontend is disabled in your settings?
![screenshot-nexopos go-2020 01 28-22_42_14](https://user-images.githubusercontent.com/5265663/73307950-81f5a400-421f-11ea-8d8e-39397843ce3e.jpg)

**Comment by Blair2004** [comment]
If it's set to "Yes" set it to "No".

**Comment by doitcoid** [comment]
Great, solved
