### ISSUE TITLE
Selecting the item from POS again adds the item as a new item ; not increasing the item in the cart.

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#290]
**Username** : 
sanjuwdr

**Describe the bug**
If I select the same item that is already in the cart, it is showing as a new item, not adding the quantity of the existing item. Also when I add a new item to a table in use, it is added as a new item as such.

**To Reproduce**
1. Go to Open POS.
2. Click on Some Item.
3. Select the same item again.
4. See that the same item is added two times, not increased the item quantity.

**Expected behavior**
It should have increased the quantity of the item in the cart, not adding a new item.

**Screenshots**
https://snipboard.io/GgSQF7.jpg
https://snipboard.io/tfDyR1.jpg

**Environment (please complete the following information):**
 - NexoPOS: 3.15.10
 - Gastro (if installed) : 2.3.80
 - PHP version : 7.1
 - MySQL version : 5.6
 - Devise used : Desktop, Google Chrome

**Additional context**

**Comment by Blair2004** [comment]
Hi, 
this is not a bug, but it's intentional, the idea is if you would like to increase the quantity, instead of clicking on the grid, cilck on the + or - sign on the item to adjust the quantity.
