### ISSUE TITLE
Increasing size of items with modifier doesn't work

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#291]
**Username** : 
sanjuwdr

**Describe the bug**
If I increase the quantity of an item with modifier, it doesn't increase. It opens the modifier window again.

**To Reproduce**
1. Go to Open POS.
2. Click on an item with modifier,
3. Try to increase the quantity.

**Expected behavior**
Should increase the quantity as any other item.

**Screenshots**
https://streamable.com/6wrw9

**Environment (please complete the following information):**
 - NexoPOS: 3.15.10
 - Gastro (if installed) : 2.3.80
 - PHP version : 7.1
 - MySQL version : 5.6
 - Devise used : Desktop, Google Chrome

**Additional context**
The feature is working perfectly in the demo @ nexopos.com

**Comment by Blair2004** [comment]
Okay we'll review.
