### ISSUE TITLE
Adding a new item to a table, showing as a new item

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#292]
**Username**:  
sanjuwdr

**Is your feature request related to a problem? Please describe.**
I had requested this feature: https://github.com/nexopos/v3-issues/issues/290
As you said it is intentional, I had also mentioned this issue there.
https://snipboard.io/o2Pphi.jpg

**Describe the solution you'd like**
This should be shown as a single item. And also if it is like this, when we print, the same item is repeated every time we add it. It can be confusing too.

**Describe alternatives you've considered**
When we add a new item to an existing table, please check if the table itself has that item id, if yes, just increase the item quantity instead of adding a new item. I know there are more things to be taken care of. But this will be helpful for many.

**Additional context (optional)**

**Comment by Blair2004** [comment]
Hi,
Thank you for having submitted this issue. As we have been mentioned, we're not about to implement this as for us. If you really want to have an item added in a single row with 3 quantities, you could use the + and - signs. This has been made to ensure items get to the kitchen as a single entity and can be cooked as that. A concrete example is, 

- 3 Products at the kitchen

When you start cooking, all the items are being cooked, and when you click "Ready" all are ready so no way for the waiter to serve gradually each items as they are ready. This has caused a lot of confusion and we're not planning to roll this back. If yous till want this as a feature, you should request a customization instead.

For reference it has been discussed here and further on the Community : https://github.com/nexopos/v3-issues/issues/253
