### ISSUE TITLE
If Splitted order, Multitax loss and incorrect grandtotal on Receipt & And icorrect value in taxes report

### ISSUE THREAD

**Issue by doitcoid** [nexopos/v3-issues#293]
**Username** : andhyreeza
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
The multitax customization module is missing and inccorect calculate value/grandtotal on the receipt and incorrect value too in the multitax report when making a splitted order.

**To Reproduce**
1. Go to 'Options --> Split order '

**Expected behavior**
Please fixed bugs quickly, because the receipt incorrect grandtotal, tax report becomes incorrect

**Screenshots**
BEFORE THE SPLITTED ORDER
http://prntscr.com/qxffez (Receipt before Splitted, still display PPn/tax)
http://prntscr.com/qxfkq7 (Multitax report before splitted, still correct calculation too)

AFTER THE SPLITTED ORDER
http://prntscr.com/qxfmzl (Tax 10% / PPn Loss, and grandtotal incorrect after the splitted order)
http://prntscr.com/qxfo1c (Multitax report after splitted, incorrect calculate, PPn/Tax 10% display 0)

**Environment (please complete the following information):**
 - NexoPOS: [v3.15.11]
 - Gastro (if installed) [v2.3.83]
 - PHP version [e.g. 7.1.30]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
Please fixed bugs quickly, because i'm use for real transaction.

**Comment by Blair2004** [comment]
Work in progress.
