### ISSUE TITLE
Subtotal on Bill incorrect (only NPS Print) after add new items on table history

### ISSUE THREAD

**Issue by doitcoid** [nexopos/v3-issues#294]
**Username** : andhyreeza
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
Bill Incorrect subtotal when adding items to an order that is already on the table.

**To Reproduce**
1. Go to 'dine in'
2. Click on 'table on going --> add new items --> select items --> print to kitchen'
3. and then Click on 'dine in --> select on going table --> NPS Print --> subtotal on bill incorrect'

**Expected behavior**
Please fixed that, because this features very important for me and another restaurant i think.

**Screenshots**
http://prntscr.com/qxtxm9
Receipt check on Group Whatsapp Nexopos

**Environment (please complete the following information):**
 - NexoPOS: [e.g. v3.15.11]
 - Gastro (if installed) [e.g. v2.3.83]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
Please ASAP to fixed this bugs, because very important for my transaction restaurant.

**Comment by nexopos** [comment]
The request is being reviewed.
