### ISSUE TITLE
The audio message is not read when a new command arrives

### ISSUE THREAD

**Issue by bendiro** [nexopos/v3-issues#295]
**Username** :  Roberto

**Describe the bug**
The audio message is not read when a new command arrives

**To Reproduce**
1. verify that the option for audio messages is turned on
2. Make a new order
3. Open kitchen view
4. when the new command appears, the voice message is not played

**Expected behavior**
when a new order arrives you should hear a message like "A new take away order has been placed"

**Environment :**
 - NexoPOS: v3.15.13
 - Gastro:  v2.3.86
 - PHP version: 7.2
 - MySQL version: 5.7
 - Devise used: desktop browser, smartphone, tablet.

**Additional context**
by editing the file /application/modules/gastro/views/watch-kitchen-script.php on line 538

if (returned.data [0] .REAL_TYPE == 'takeaway') {
                                $ scope.synthesizer ('<? php echo _s (' A new take away order has been placed. ',' gastro ');?>');
                            } else if (returned.data [0] .REAL_TYPE == 'delivery') {
                                $ scope.synthesizer ('<? php echo _s (' A new delivery order has been placed. ',' gastro ');?>');
                            } else if (returned.data [0] .REAL_TYPE == 'dinein') {
                                $ scope.synthesizer ('<? php echo _s (' A new dine in order has been placed, at the table% s. ',' gastro ');?>'. replace ('% s', returned.data [ 0] .TABLE_NAME));
                            } else if (returned.data [0] .REAL_TYPE == 'booking') {
                                $ scope.synthesizer ('<? php echo _s (' A new booking order has been placed, at the table% s. ',' gastro ');?>'. replace ('% s', returned.data [0 ] .TABLE_NAME));
                            }

with

if (newOrders [0] .RESTAURANT_ORDER_TYPE == 'takeaway') {
                                $ scope.synthesizer ('<? php echo _s (' A new take away order has been placed. ',' gastro ');?>');
                            } else if (newOrders [0] .RESTAURANT_ORDER_TYPE == 'delivery') {
                                $ scope.synthesizer ('<? php echo _s (' A new delivery order has been placed. ',' gastro ');?>');
                            } else if (newOrders [0] .RESTAURANT_ORDER_TYPE == 'dinein') {
                                $ scope.synthesizer ('<? php echo _s (' A new dine in order has been placed, at the table% s. ',' gastro ');?>'. replace ('% s', returned.data [ 0] .TABLE_NAME));
                            } else if (newOrders [0] .RESTAURANT_ORDER_TYPE == 'booking') {
                                $ scope.synthesizer ('<? php echo _s (' A new booking order has been placed, at the table% s. ',' gastro ');?>'. replace ('% s', returned.data [0 ] .TABLE_NAME));
                            }
audio is heard

**Comment by nexopos** [comment]
Which language are you using ?

**Comment by bendiro** [comment]
italian

**Comment by bendiro** [comment]
changed:
 msg.lang = 'en-us';
with:
  msg.lang = '<?php echo @$Options[ 'site_language' ];?>';
