### ISSUE TITLE
Partial Payments on POS

### ISSUE THREAD

**Issue by ideoptima** [nexopos/v3-issues#296]
**Username** : 
NexoConnektoras

**Describe the bug**
If i proceeded to a partial payment of an order, there is no indication on pos that an amount is already paid.Due to the order status is still "unpaid" instead of "partial paid", the user will believe that the 1st(partial) was not stored and will try to make it again.
Or to make one for the full amount. 
Note that the partial payment amount is stored in db and if the total of partial payments exceed the order total, the order is getting marked as paid.

**To Reproduce**
1. Just proceed with 1-2 small payments of a specific order.

**Expected behavior**
The same as the one on dashboard where you can see the already paid amount.

**Screenshots**
https://prnt.sc/qyukb8
https://prnt.sc/qyukgq

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.15.13]
 - Gastro (if installed) [e.g. 2.3.86]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by sanjuwdr** [comment]
The same is happening for me.

**Comment by Blair2004** [comment]
Work in progress
