### ISSUE TITLE
Paid orders still in hold; hold orders does not show prices

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#297]
**Username** : 
sanjuwdr

**Describe the bug**
The orders which is already paid is still present in the hold. Sometimes even if I checkout, it does not free the table and table is still staying as UNPAID. And the amount is showing as 0 in the hold screen. 

**To Reproduce**
Try to pay some orders.

**Expected behavior**
Paid Orders should be removed from Hold. See https://snipboard.io/FlyR2J.jpg which should show the item price.

**Screenshots**
https://snipboard.io/FlyR2J.jpg
https://snipboard.io/1RPzQV.jpg

**Environment (please complete the following information):**
 - NexoPOS: 3.15.13
 - Gastro : 2.3.86
 - PHP version 7.1
 - MySQL version :5.6
 - Devise used : Desktop 

**Additional context**

**Comment by sanjuwdr** [comment]
Also, some orders are automatically checked out and it does not show in table history ; but it will be present in Hold orders. It happens randomly and when there are many orders.

**Comment by Blair2004** [comment]
Processing a review

**Comment by Blair2004** [comment]
Unable to reproduce the issue.

**Comment by sanjuwdr** [comment]
This issue is appearing randomly. Not always.

**Comment by Blair2004** [comment]
Without a proper exact case, we cannot help out. Please feel free to reopen once you find our the exact steps to reproduce it.
