### ISSUE TITLE
Issue : Changing decimal precision is not effective NexoPOS

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#299]
**Username** :  blair2004
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug** 
It looks like while defining a new price precision, it's not effective on the system no mater how the cache is refreshed.

**To Reproduce**
1. Go to change the float precision to 3 or 1
2. Save the settings
3. See how it doesn't work.

**Expected behavior** 
The price should be updated accordingly.

**Screenshots**
![error2](https://user-images.githubusercontent.com/5265663/74256430-9e034600-4cf3-11ea-8830-ae9f46dd0312.PNG)

**Environment (please complete the following information):**
 - NexoPOS: 3.15.15
 - PHP version 7.2
 - MySQL version 5.7

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS Local Dev</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS demo</td>
                                <td>2019-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale - Gastro Demo</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS SOK</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Multi Online</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Brice Setup</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro Local Dev</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS Remote Dev</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>22714330</td>
                                <td>Self Ordering Kiosk</td>
                                <td>2030-05-31 17:44:59</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Not proven
