### ISSUE TITLE
The tax stays at zero when you edit the amount.

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#30]
**Username**
israelga

**Describe the bug**
When you enter a product in POS and edit the amount the tax stays at zero. When the system would have to calculate the Tax with the new amount.

**To Reproduce**
1. Go to POS and enter a product.
2. Modify the net price of the product
3. The Tax is not recalculated with the new amount

**Expected behavior**
The system has to recalculate the tax with the new amount

**Screenshots**
https://www.screencast.com/t/MWyZnUiTX

**Environment (please complete the following information):**
 - NexoPOS: 3.12.12
 - PHP version 7.1
 - MySQL version [5.6]
 - Devise used (desktop browser,POS system).

**Comment by Blair2004** [comment]
This time the issue is well posted. Thank you.

**Comment by israelga** [comment]
I already want to solve it.

**Comment by Blair2004** [comment]
Have you seen how i've reproduced the error, but i wasn't able to see the bug. Have you tried that on a fresh installation ?

**Comment by Blair2004** [comment]
![record3](https://user-images.githubusercontent.com/5265663/42967107-1ff95660-8b97-11e8-90c3-e7722624fff3.gif)

**Comment by israelga** [comment]
What do you mean by a new installation? Do you want me to install the software on another site?

**Comment by israelga** [comment]
Hello, I need a solution on the tax claim in the POS.
