### ISSUE TITLE
Ready order not showing in pos screen

### ISSUE THREAD

**Issue by earlyit** [nexopos/v3-issues#300]
**Username** : Jalaany

**Describe the bug**
After update gastro to version v.2.3.88 Nexopos v.3.15.16 
And make migration.
I change status the order to ready from kitchen page. Then the ready order not showing in pos screen pop-up . to make payment..

Also I tried it on a fresh copy without any old data the same problem
https://youtu.be/tGK8cJlrY88

**To Reproduce**
1-Go to 'pos.'
2-Click on 'ready order's
3-The issue no order are ready showing

**Expected behavior**
Showing the ready order in pop-up in screen pos

**Screenshots**
https://youtu.be/tGK8cJlrY88

**Environment (please complete the following information):**
 - NexoPOS: [v. 3.15.16]
Gastro (if installed) [v. 2.3.88]
PHP version [e.g. 7.1]
MySQL version [5.6]
Devise used (desktop browser, smartphone, POS system).
**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by earlyit** [comment]
Hi Can you watch the video u  will understand me
https://youtu.be/tGK8cJlrY88

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-02-17 10:50:42</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-10-26 22:38:01</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-03-18 22:32:10</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-03-18 22:32:10</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-03-18 22:32:10</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by earlyit** [comment]
Also I tried it on domo the same issue
http://gastro.tendoo.org/dashboard/nexo/pos
👇
https://youtu.be/-o8KodlVLDs
