### ISSUE TITLE
Issue the ready order not showing in screen pos

### ISSUE THREAD

**Issue by earlyit** [nexopos/v3-issues#301]
**Username** : Jalaany

**Describe the bug**
After update gastro to version v.2.3.88 Nexopos v.3.15.16 
And make migration.
I change status the order to ready from kitchen page. Then the ready order not showing in pos screen pop-up . to make payment..

Also I tried it on a fresh copy without any old data the same problem
https://youtu.be/tGK8cJlrY88

**To Reproduce**
1-Go to 'pos.'
2-Click on 'ready order's
3-The issue no order are ready showing

**Expected behavior**
Showing the ready order in pop-up in screen pos

**Screenshots**
https://youtu.be/tGK8cJlrY88

**Environment (please complete the following information):**
 - NexoPOS: [v. 3.15.16]
Gastro (if installed) [v. 2.3.88]
PHP version [e.g. 7.1]
MySQL version [5.6]
Devise used (desktop browser, smartphone, POS system).
**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-02-17 10:50:42</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-10-26 22:38:01</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-03-18 22:32:10</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-03-18 22:32:10</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-03-18 22:32:10</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-02-17 10:50:42</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-05-29 13:11:09</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-10-26 22:38:01</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-03-18 22:32:10</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-03-18 22:32:10</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-03-18 22:32:10</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by abdulsamad544** [comment]
Facing the same issue in our kitchen due to this. Its an old issue, maybe 2 or 3 months old. But not solved. I have also informed the dev (Vishal) about this one.

**Comment by earlyit** [comment]
Also I tried it on domo the same issue
http://gastro.tendoo.org/dashboard/nexo/pos
point_down
https://youtu.be/-o8KodlVLDs
