### ISSUE TITLE
Logo image not show

### ISSUE THREAD

**Issue by bendiro** [nexopos/v3-issues#302]
Username : Roberto 

Describe the bug:
multi store: in the shop settings -> general settings -> brand, if you set an image as a logo, the image is not shown and the writing logo remains visible. it seems as if the "Logo type" selector is not registered

<img width="1134" alt="Schermata 2020-02-16 alle 10 57" src="https://user-images.githubusercontent.com/35408482/74603204-66a8e680-50b1-11ea-9fb4-3bb2f60810fc.png">

Environment:
 - NexoPOS: 3.15.17
 - Gastro: v2.3.88
 - PHP version: 7.3
 - MySQL version: 5.7
 - Devise used: desktop browser, smartphone, tablet

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
