### ISSUE TITLE
Issue: logo image is not displayed on the site

### ISSUE THREAD

**Issue by bendiro** [nexopos/v3-issues#303]
**Username:** Roberto 

**Describe the bug:**
multi store: in the shop settings -> general settings -> brand, if you set an image as a logo, the image is not shown and the writing logo remains visible. it seems as if the "Logo type" selector is not registered

**Screenshots:**
<img width="1134" alt="Schermata 2020-02-16 alle 10 57" src="https://user-images.githubusercontent.com/35408482/74603204-66a8e680-50b1-11ea-9fb4-3bb2f60810fc.png">

**Environment:**
 - NexoPOS: [3.15.17]
 - Gastro: [v2.3.88]
 - PHP version: [7.3]
 - MySQL version: [5.7]
 - Devise used: [desktop browser, smartphone, tablet]

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Sorry, this thread has exceeded the maximum modification allowed. This thread will now be closed, but you still have the capacity to create a new one.

**Comment by Blair2004** [comment]
The logo is mean to appear when the menu is collapsed.
