### ISSUE TITLE
Arabic language issue with cash registers

### ISSUE THREAD

**Issue by muhammedalkahlan** [nexopos/v3-issues#304]
**Username** :  Muhammed1980
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
we have issue with arabic language with cash registers
**To Reproduce**
1. Go to 'registers'
2. Click on 'edit'
3. Scroll down to 'you will not found open register button after creating an new register that State is closed'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [.v3.15.16]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.2]
![WhatsApp Image 2020-02-18 at 6 22 49 PM](https://user-images.githubusercontent.com/53022134/74750619-0d8dae00-527d-11ea-87c7-2557ad5ddf8e.jpeg)
![WhatsApp Image 2020-02-18 at 6 22 49 PM (1)](https://user-images.githubusercontent.com/53022134/74750626-0ff00800-527d-11ea-872f-e7a7827b629a.jpeg)

]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
Also i cant

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Hairsareus" on [Nexo Platform](https://platform.nexopos.com).
                    Note that, maybe the issue is not well formatted as well, please consider reading [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/). 
                    Regards.

**Comment by Blair2004** [comment]
Hi, does "Hairsareus" is your actual name on Nexo Platform ?

**Comment by muhammedalkahlan** [comment]
Hello, I don’t remember what exactly the username was but it was something like this but my codecanyon username is : Muhammed1980
And the license place at
pos.hairs-are-us.com

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Blair2004** [comment]
Your username is "Muhammed1980". But all your support has expired. Meanwhile, as proof of good faith, we'll proceed with the support this time, but you should consider renewing your support.

**Comment by nexopos** [comment]
Hi, i've reviewed your account on [Nexo Platform](https://platform.nexopos.com), it seems like you no longer have valid licences. 
                Please note that in order to receive support and updates, your licences (purchase code) need to be renewed on CodeCanyon.

**Comment by Blair2004** [comment]
First of all, we'll proceed from our end.

**Comment by muhammedalkahlan** [comment]
Hi,
As you can see i always buying your script and for the last one i purcheased i have 5 month of support but its okay no problem i will renew but please for this time solve the problem with the arabic language it was working and everything fine and i didnot do any update it just gone the open register button from the arabic language.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by muhammedalkahlan** [comment]
Hi,
Did you solved the problem ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Blair2004** [comment]
The work is in progress.

**Comment by muhammedalkahlan** [comment]
okay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by vishalwalia1** [comment]
Issue Fix ,

**Comment by muhammedalkahlan** [comment]
Hello
Firstly thank you for response
We need some new custimaztons on the system please tell me when you can be available so lets talk by phone because it will be easier for me to let you know what exatly we want
Best regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Blair2004** [comment]
Please for the customization, contact us from contact@nexopos.com.
