### ISSUE TITLE
Problem in the checkout in Self Order Kiosk for NexoPOS Front module

### ISSUE THREAD

**Issue by cartalink** [nexopos/v3-issues#306]
**Username** : 
cartapos

**Describe the bug**
Hi, I have a strange behavior with the SOK module.

When I proceed to the checkout, a window appears “Would you like to confirm ? The order is ready to be send to the kitchen. Would you like to proceed ?”. When I said yes, the window diseappear and nothing happens. 
I don’t see the 2nd window “Proceed Another Order ? Would you like to order something else ? If not you’ll be automatically disconnected… Closing within 4 second(s)” 
The cart is not resetted. 
When I verify in the order commands menu SOK, nothing appears in the nexoPOS. 
Could you help me with this issue ? Thanks !

**To Reproduce**
1. Go to 'http://cartapos.cartalink.com/so/store'
2. Add stuff in the cart
3. Click on Checkout
4. Login as Guest
5. Choose 'Take Away'
6. Nothing Happens

**Expected behavior**
When we checkout, the order must be sent to he kitchen and the cart resetted.

**Screenshots**

During the checkout
![image](https://user-images.githubusercontent.com/55022374/74885055-891a5880-536c-11ea-8459-0ea0d04cf9fc.png)

After the checkout
![image](https://user-images.githubusercontent.com/55022374/74885113-b535d980-536c-11ea-93c2-e3d28a2220c8.png)

Window missing 
![image](https://user-images.githubusercontent.com/55022374/74885622-f24e9b80-536d-11ea-889e-0ee56c6991cf.png)

**Environment (please complete the following information):**
 - NexoPOS v3.15.18
 - Gastro v2.3.88
 - Self Order Kiosk - Gastro Extension v1.12.2
 - PHP version 7.3.14
 - MariaDB - 10.4.11
 - Devise used (desktop browser Chrome).

**Additional context**

**Comment by cartalink** [comment]
I have the same behavior on your demo website : http://sok-nexopos.tendoo.org/so/store
You can check the video in the zip file.
[sok-oreder-issue.zip](https://github.com/nexopos/v3-issues/files/4232333/sok-oreder-issue.zip)

**Comment by Blair2004** [comment]
Hi, we've updated Self Ordering Kiosk since the time, please check whether the problem is solved. Make your test with the latest NexoPOS version.

**Comment by Blair2004** [comment]
Reopen the thread if the issue persists.
