### ISSUE TITLE
Same products to be merged as single in the receipt

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#309]
**Username**:  sanjuwdr

**Is your feature request related to a problem? Please describe.**
When we add a new item to the existing table, it shows as a different product in the table order list, that is fine as the new items should be sent as separate to the kitchen. But in the last, the print also comes that way. If a table has product 1, and if I add it again, it will be shown as two products in the receipt as well which is confusing and annoying for the customers. They need to count the product numbers and has to calculate the bill.
Please refer to this: https://snipboard.io/3Svwat.jpg

**Describe the solution you'd like**
It will be good if they same products are merged together in the bill. All that customer knows is he ordered the product 1 two times. So it is better to show the product 1 as single product with two quantity. As we think in the customer perspective, it will be the they want.

**Describe alternatives you've considered**

**Additional context (optional)**

**Comment by Blair2004** [comment]
We're not planning to merge items that are similar but might have different modifiers. In such situation, that will bring more confusion.
