### ISSUE TITLE
Not able to pay using customer credit

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#310]
**Username** : 
sanjuwdr

**Describe the bug**
Not able to pay using customer credit. It shows credit exceeds the limit. I set the limit to 0 for unlimited credit. But it still shows the error popup.

**To Reproduce**
1. Try to add a credit for a customer.
2. Pay using customer credit  and this error occurs.

**Expected behavior**
The amount should deduct from the credit balance.

**Screenshots**
https://snipboard.io/vNK7kT.jpg
When credit limit is set to 0 : https://snipboard.io/atRDY3.jpg

**Environment (please complete the following information):**
 - NexoPOS: v3.15.22
 - Gastro (if installed) v2.3.92
 - PHP version 7.2
 - MySQL version 5.6
 - Devise used :desktop browser

**Additional context**
It might be a bug or some documentation issue. The documentation on this credit feature is not completely explained.

**Comment by Blair2004** [comment]
Under review
