### ISSUE TITLE
Dashboard stats not working

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#311]
**Username** : 
sanjuwdr

**Describe the bug**
The statistics in the dashboard is always shown as 0. Also the sale of today always show 0, sale of yesterday shows correctly. 

**To Reproduce**
1. Go to Dashboard.
2. Check the stats.

**Expected behavior**
Concise and exact display of all statistics.

**Screenshots**
https://snipboard.io/UisXj4.jpg
These stats are working in cashier login: https://snipboard.io/uHtDp8.jpg

**Environment (please complete the following information):**
 - NexoPOS: v3.15.22
 - Gastro (if installed) v2.3.92
 - PHP version 7.2
 - MySQL version 5.6
 - Devise used :desktop browser

**Additional context**
 I checked the demo and got to know that it works the same in the demo too.

**Comment by vishalwalia1** [comment]
Week stats working fine  and  Sale chart working as well. Mark issue close

**Comment by sanjuwdr** [comment]
As Vishal said, I checked the cache folder permission. But the issue still exist.

**Comment by Blair2004** [comment]
This is related to the dashboard cache. You might either need to clear the cache or to check the file permission, NexoPOS needs to be able to write down data.
