### ISSUE TITLE
Gastro Split Order Issues

### ISSUE THREAD

**Issue by ideoptima** [nexopos/v3-issues#312]
**Username** : 
NexoConnektoras

**Describe the bug**
On split order submission it returns a white screen with loader(1st img).
Then if you checkout all sub-orders the table is not got set as available.(2nd img).

**To Reproduce**
1. Split a table order in 2-3 parts.
2. Proceed to individual payment of each part of the split order.

**Expected behavior**
Same as with non split orders.

**Screenshots**
.![gastro-split-2](https://user-images.githubusercontent.com/59666201/76400005-46a2d500-6388-11ea-986d-404665d0c7e2.png)
![gastro-split-4](https://user-images.githubusercontent.com/59666201/76400103-72be5600-6388-11ea-92cd-e29d13b03e6d.png)

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.15.23]
 - Gastro (if installed) [e.g. 2.3.92]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Chrome, Firefox

**Additional context**

**Comment by Blair2004** [comment]
Not proven on Gastro 2.3.94 and NexoPOS 3.15.24+
