### ISSUE TITLE
Expiration Date

### ISSUE THREAD

**Issue by rsidhaarth** [nexopos/v3-issues#313]
**Username** : rsidhaarth

**Describe the bug**

I have created the product by mentioning the expiry date which is 5 days from now. And then added the stock on 1st day and also on the 2nd day. But till now I am able to add the product to the POS and there is no alert about expiry.

**Comment by vishalwalia1** [comment]
Hello, I cant reproduce the issue , In latest version of NexoPOS and Gastro expiration date option working fine - see screenshot Below 

![Capture111](https://user-images.githubusercontent.com/32275898/76629901-1bc1a800-6565-11ea-8c20-419d40b47202.PNG)
