### ISSUE TITLE
Expiry Date and Manufacturer (Own)

### ISSUE THREAD

**Issue by rsidhaarth** [nexopos/v3-issues#314]
**Username**:  rsidhaarth

To make you understand better, we are going to use your product for our bakery with own kitchen.

So we will be preparing our own cookies and then sell it. As of now I did the same through the Gastro.

I added a new supply as our store name and added product to stock through our own kitchen. It will be better if you integrate the recipe management with the gastro and nexpos and so when ever  a new supply is adding from our own supply, we can reduce it from the stock.

Do note that, some product needs to be manufactured and stored as a stock ( cookies ), in this case when we are adding to stock you can reduce from the recipe stock.

Some products can be instantly prepared and served to the customer ( coffee, sandwich etc ), in this case we will mention who is the supply , if it is own supply, then we will reduce it from stock when the product is added to pos and move to kitchen and once it is started cooking.

This is the improvement you can do along with recipe management which is yet to release.

Another improve is, you are asking to mention the expiry date as date, which will be confusing when we edit the product as it shows the past date. Rather, make it to no of days and alert the customer through notification.

Please try to add waste management as well for the expired products.

**Comment by Blair2004** [comment]
Some products can be instantly prepared and served to the customer => implemented already
Recipe management is ongoing.
