### ISSUE TITLE
Split Screen Bug

### ISSUE THREAD

**Issue by ideoptima** [nexopos/v3-issues#315]
**Username** : 
NexoConnektoras

**Describe the bug**
The button marked on screenshot should not be able to set the qty below zero otherwise each time you press it, adds items to the initial order.

**To Reproduce**

**Expected behavior**

**Screenshots**
![nexo-split-7](https://user-images.githubusercontent.com/59666201/76619007-945b4100-6532-11ea-8ae9-b323cc9370a8.png)

**Environment (please complete the following information):**
    NexoPOS: [e.g. 3.15.23]
    Gastro (if installed) [e.g. 2.3.92]
    PHP version [e.g. 7.1]
    MySQL version [5.6]
    Chrome, Firefox

**Additional context**

**Comment by vishalwalia1** [comment]
Hello, Can you confirm Your NexoPOS and Gastro version because in latest version of NexoPOS 3.15.23 and  Gastro v2.3.92  cant see that issue , also confirm did you using any custom module as well ?

**Comment by ideoptima** [comment]
Please check the video.
https://streamable.com/iep68

No custom module activated.
NexoPOS 3.15.23 and Gastro v2.3.92

**Comment by ideoptima** [comment]
I think i found the reason.

At function $scope.returnToSelectedOrder  on the bottom:
  if ( order.selected ) {
          order.items.splice( index, 1 );
  }

User can press the minus button even if the specific order part(split) is not selected.
So the splice won't take place because the order.selected will become true after the if statement above.

As a quick workaround i have placed the ng-show check to the following element.
<span ng-show="order.selected" ng-click="returnToSelectedOrder( item, $index )" class="item-button"><i class="fa fa-minus"></i></span>

That way user has to select  the order part before being able to remove item qty.

**Comment by ideoptima** [comment]
A Better approach to the possible solution.
Sending also the order obj to function.
`<span  ng-click="returnToSelectedOrder( item, $index, order )" class="item-button"><i class="fa fa-minus"></i></span>`

Then inside that function:

`$scope.returnToSelectedOrder    =   function( item, index, order ) {
       $scope.selectIncludedOrder( order ); // added this line`
