### ISSUE TITLE
Unable to offer/do discount from while making payment from Order List screen

### ISSUE THREAD

**Issue by WaseemAkbar2772** [nexopos/v3-issues#316]
![scrren-1](https://user-images.githubusercontent.com/59607552/76684430-d74e0f00-662d-11ea-9fc9-9a3d559c059e.png)

While doing paymnet from Dashboard -> Sales -> Options -> payments , system does not allow us to add discount like as can do form POS screen.
Please add this functionality here(Sales Screen) too, thanks.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
