### ISSUE TITLE
Improve reporting

### ISSUE THREAD

**Issue by paverneuil** [nexopos/v3-issues#318]
**Username**:  paverneuil

**Is your feature request related to a problem? Please describe.**
It is not practical to export reports detailing, or to remove the number of products sold from a particular SKU.

**Describe the solution you'd like**
- Allow export of reports in csv or xls
- Add a new report to exit sales by SKU

thank you :)

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "pa_verneuil" on [Nexo Platform](https://platform.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by paverneuil** [comment]
Hello,
Thanks I just made the correction.

Cordially:)

**Comment by Blair2004** [comment]
What do you mean by exit sales by SKU ?

**Comment by Blair2004** [comment]
No further improvements planned for 3.x
