### ISSUE TITLE
Tax number

### ISSUE THREAD

**Issue by alsaihati** [nexopos/v3-issues#319]
**Username** : saihati

**Describe the bug**
if you add item price include tax for example
item price= 5
then tax= 0.25 but because decimal precision setting is 0 then tax will= 0.
Total is correct is 5 but in sale receipt tax is Zero.

If decimal precision setting is 2 then price in cart will be:
item price= 4.75
tax=0.24 (it should be 0.25)
total amount= 4.99

**To Reproduce**
check same example with item price and proceed in POS

**Expected behavior**
correct calculation if the item price is 5 then in detail is 4.75 + 0.25 tax = 5

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: 3.15.29
 - Gastro 2.3.97

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-11-22 18:33:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-08-30 13:48:09</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2021-03-01 06:20:31</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-08-30 13:48:09</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-09-07 12:39:48</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-25 09:24:52</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-02-25 09:25:52</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-25 09:24:52</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-25 09:24:52</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-25 05:16:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-25 05:16:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-07-26 13:30:14</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2021-03-01 06:20:31</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-11-07 01:37:55</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, what is the rate of the tax ?

**Comment by alsaihati** [comment]
5%

في الخميس، ٤ يونيو ٢٠٢٠ ١:٥٤ م Blair Jersyer <notifications@github.com> كتب:

**Comment by vishalwalia1** [comment]
I review the issue and as i can see Tax calculation is right with decimal precision set ( 2 )
Item Price - Tax Inclusive = 5.00
Tax (5%) = 0.25
Sub-Total = 4.75
Total =  5.00
also same print on sale receipt as well -- see the image Below 

![index](https://user-images.githubusercontent.com/32275898/83947784-d268b800-a836-11ea-9e47-1b530b12be5c.jpg)

@Blair2004 @alsaihati

**Comment by alsaihati** [comment]
It is not in my side ?!!

See attached please

في السبت، ٦ يونيو ٢٠٢٠ ٦:١٨ م vishalwalia1 <notifications@github.com> كتب:

**Comment by vishalwalia1** [comment]
Issue Fix , Some settings not set properly

**Comment by alsaihati** [comment]
Fixed

Thank you

في السبت، ٦ يونيو ٢٠٢٠ ٦:٤٢ م vishalwalia1 <notifications@github.com> كتب:
