### ISSUE TITLE
Please add customer name on receipt kitchen

### ISSUE THREAD

**Issue by kxygol** [nexopos/v3-issues#320]
**Username**:  kxygol

**Describe the solution you'd like**
Please add customer name above table on receipt kitchen.

for now I look at the cashier's receipt.
or I see on a computer screen.

if the customer's name is on the kitchen receipt.
then the order from the kitchen is finish and my crew can immediately know that order for which customer

![2](https://user-images.githubusercontent.com/12599903/83938900-bfd48b80-a802-11ea-8225-a617a985e32a.jpg)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2020-06-18 00:38:39</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-02-05 14:51:13</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-06-17 07:51:57</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-09-17 11:29:40</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Awaiting Testing Confirmation
https://github.com/Blair2004/gastro/commit/f0ce44a7c56c7ebfe54ce9e756eee9d6135358d3

**Comment by Blair2004** [comment]
Should be implemented otherwise let us know.
