### ISSUE TITLE
Error while paying an order from hold

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#321]
**Username** : 
sanjuwdr

**Describe the bug**
Error while paying an order from hold list. I can pay the the hold orders on the same day sometimes. 

**To Reproduce**
1. Go to Hold orders in POS.
2. Try to pay some orders that are put on hold.

**Expected behavior**
Payment should be done and the hold order should be removed from the list.

**Screenshots**
https://kapwi.ng/c/eoeE7ASx
attaching a video of the same.

**Environment (please complete the following information):**
 - NexoPOS: 3.15.31
 - Gastro : 2.3.97
 - PHP version : 7.2
 - MySQL version [5.6]
 - Devise used : Desktop browser

**Additional context**

**Comment by Blair2004** [comment]
Should be fixed on NexoPOS 3.15.37
