### ISSUE TITLE
I can’t upload item photo. Pls let me know how to fix?

### ISSUE THREAD

**Issue by mayswe** [nexopos/v3-issues#323]
![Screen Shot 2020-06-10 at 11 32 42 PM](https://user-images.githubusercontent.com/40296233/84356706-98a70100-abea-11ea-92da-24051b1e9038.png)

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Your issue is not well formated. Consider creating a new one following the instruction provided here : https://nexopos.com/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/
