### ISSUE TITLE
I cannot upload item image.

### ISSUE THREAD

**Issue by mayswe** [nexopos/v3-issues#324]
**Username** : mayswe
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**I cannot upload item image.**

**To Reproduce**
1. Go to 'Inventory'
2. Click on 'Add item'
3. Click on 'Features'
4. Click on 'Upload Files'
5. See error

**Expected behavior**

**Screenshots**
![Screen Shot 2020-06-10 at 11 05 24 PM](https://user-images.githubusercontent.com/40296233/84357896-5aaadc80-abec-11ea-8431-79f3679bd2a7.png)

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by mayswe** [comment]
I already correct to correct format. pls check again.

**Comment by nexopos** [comment]
Hi, i've reviewed your account on [Nexo Platform](https://platform.nexopos.com), it seems like you no longer have valid licences. 
                Please note that in order to receive support and updates, your licences (purchase code) need to be renewed on CodeCanyon.

**Comment by Blair2004** [comment]
While your support has expired, we cannot take a look at your system. But if you can provide the server response when you're uploading the image, we'll advise better. 

Kind Regards.

**Comment by mayswe** [comment]
Many Thanks Sir, now I cannot buy for support licenses. so please help me. 
server réponse screenshot 
![Screen Shot 2020-06-11 at 2 18 07 PM](https://user-images.githubusercontent.com/40296233/84359367-87f88a00-abee-11ea-87ff-913637ff6b9e.png)

**Comment by Blair2004** [comment]
Hi,
Are you still facing that issue ?

**Comment by mayswe** [comment]
No. Now I’m ok. 
Thanks for your email.
