### ISSUE TITLE
Item added from POS has price 0 when edited from Hold

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#325]
**Username** : 
sanjuwdr

**Describe the bug**
The item added from the POS screen is showing price 0 when edited from Hold. Also Payment cannot be made as I mentioned in #321 and someone also reported it on #322 .
Also the print popup is not coming when sending order to kitchen. I used 2-3 devices, same result.

**To Reproduce**
1. Open POS
2. Add a new item from POS
3. Send to kitchen in Take Away
4. Try to edit the order and pay.

**Expected behavior**
The edited order should have the item price and print popup should open while sending order to kitchen.

**Screenshots**
https://snipboard.io/IHSUrh.jpg ; I have enabled this option and still it doesn't show print popup for take away.
https://www.kapwing.com/videos/5ee5ff02bfd48100159fa7c8

**Environment (please complete the following information):**
 - NexoPOS: 3.15.31
 - Gastro : 2.3.97
 - PHP version : 7.2
 - MySQL version [5.6]
 - Devise used : Desktop browser

**Additional context**

**Comment by Blair2004** [comment]
Thank you we're investigating.

**Comment by Blair2004** [comment]
We've not been able to reproduce it. Please contact me via WhatsApp so that I can have a look at your installation.

**Comment by sanjuwdr** [comment]
Already texted you.
