### ISSUE TITLE
Condensed report not available on Print

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#327]
**Username** : 
sanjuwdr

**Describe the bug**
In the reports, detailed report is showing for both condensed and detailed reports while printed.

**To Reproduce**
1. Go to Reports -> Detailed Report
2. Select any date
3. Choose Format "Condensed"
4. Try Printing, You will get Detailed Report.

**Expected behavior**
Condensed Report should be printed.

**Screenshots**
https://snipboard.io/Pf1Kha.jpg

**Environment (please complete the following information):**
 - NexoPOS: v3.15.34
 - Gastro : v2.3.99
 - PHP version : 7.2
 - MySQL version :5.6
 - Devise used : Desktop browser

**Additional context**

**Comment by Blair2004** [comment]
Unable to reproduce : https://nimb.ws/f9AkDj
If the issue is occurring reopen this.
