### ISSUE TITLE
NExoPOS  to NExoStore Woocommerce SYNC information

### ISSUE THREAD

**Issue by webtech09** [nexopos/v3-issues#328]
**Username** : TECH9

**Describe the bug**
Customer Order online to nexostore and she/he receive a code. which is different code that has been shown in the dashboard of the nexoPOS. Also status of order is not sync in the woocommerce

**Issue**
**Feature Submition**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by Blair2004** [comment]
Consider registering your Nexo Store license in order to receive support for NexoStore.

**Comment by Blair2004** [comment]
Closed for inactivity
