### ISSUE TITLE
Products added from POS doesn't reflect on Reports

### ISSUE THREAD

**Issue by sanjuwdr** [nexopos/v3-issues#332]
**Username** : 
sanjuwdr

**Describe the bug**
The products added from the POS screen does reflect on the sales list but the amount is not added in reports. 

**To Reproduce**
1. Go to POS Screen
2. Add an item from POS
3. Pay and complete the order. You can see the order in Sales List.
4. Check Reports, the order is not showing!

**Expected behavior**
The order amount should be reflected in reports as well.

**Screenshots**
Product added from POS: https://snipboard.io/zSnoY2.jpg 
Reports : https://snipboard.io/3n4PRx.jpg

**Environment (please complete the following information):**
 - NexoPOS: 3.15.37
 - Gastro : 2.3.99
 - PHP version : 7.1
 - MySQL version : 5.6
 - Devise used : Desktop browser

**Additional context**

**Comment by Blair2004** [comment]
Unable to reproduce the issue. Further tests are required from the customer end.

**Comment by Blair2004** [comment]
The thread should be reopened if the issue is proven.

**Comment by Blair2004** [comment]
After some clarification on the steps to reproduce we'll work over the issue again.
For clarification, the issue occurs for products added from the POS (Quick Items).
