### ISSUE TITLE
Issue with the Woocommerce Order Printing & Kitchview

### ISSUE THREAD

**Issue by nasirqureshiofficial** [nexopos/v3-issues#334]
**username**
nasirqureshiofficial

**Issue**
1. When ordering from website i.e. it doesnt print anything, what I need is an sale reciept along with kitchen reciept, if we disable kitchen screen, no kitchen reciept comes out if using POS. https://www.pizzanio.com

2. Modifiers & Modifiers Group does not import if sync from NexoPOS to Woocommerce in WordPress admin, even with latest update. 

3. Detailed daily report should have back & forward button or a drop down date field to check report for any respective day, this is not availble on report section ![2020-07-07_021757](https://user-images.githubusercontent.com/67840185/86646077-62e21600-bff8-11ea-8e2f-619bfa77428e.png)

4. The products on woocommerce if having modifiers having price either sale / retail does not update once modifier selected, it should be automatically update if any or all modifier selected, currently it is adding modifier price + retail price and add into cart.

To Reproduce

Go to 'any product / category page'
Click on 'modifier and check no price will update

**Expected behavior**
1. As earlier described the issue we need it should print sale reciept + kitchen reciept even if not using kitchen screen and order coming through Woocommerce.

2. Modifiers and their group should import to Woocommerce.

3. Daily report should have previous next button.

4. Price update on woocommerce product page if we click on any modifier right now its mixing with retail price + modifier price.

 - NexoPOS: [e.g. 3.15.37 ]
 - Gastro (if installed) [e.g. 2.3.95]
 - PHP version [e.g. 7.2]
 - MySQL version [5.6]
 - Devise used (Laptop).

**Comment by nasirqureshiofficial** [comment]
1. Modifiers & Modifiers are also not import from NexoPOS to Woocommerce, updated to v3.15.39, please.
2. Detailed daily report should have back & forward button or a drop down date field to check report for any respective day, this is not availble on report section ![2020-07-07_021757](https://user-images.githubusercontent.com/67840185/86646077-62e21600-bff8-11ea-8e2f-619bfa77428e.png)

**Comment by nasirqureshiofficial** [comment]
I just updated this issue please update if you get it or please mention something in comments so it can be corrected.

**Comment by Blair2004** [comment]
Hi, the 1 and 2 points won't be worked on right now. But 3 and 4 will.

**Comment by nasirqureshiofficial** [comment]
any ETA ?
