### ISSUE TITLE
Customized Tax Calc not working proffsionally

### ISSUE THREAD

**Issue by alsaihati** [nexopos/v3-issues#336]
**Username** : 
saihati

**Describe the bug**
I requested customized tax calculation to use it as item price tax included. But the calculation sometimes not give exactly as item price. For example: as per items prices total is 46 (means tax included). Then it gives 45.99 or 46.01 which is not correct.

**Expected behavior**
Give correct total calculation as you have in NexoPOS

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-11-22 18:33:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-08-30 13:48:09</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2021-03-01 06:20:31</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-08-30 13:48:09</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-09-07 12:39:48</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-25 09:24:52</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-02-25 09:25:52</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-25 09:24:52</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-25 09:24:52</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-25 05:16:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-25 05:16:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-07-26 13:30:14</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2021-03-01 06:20:31</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-11-07 01:37:55</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-12-09 19:53:35</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by alsaihati** [comment]
still waiting to fix the issue

**Comment by Blair2004** [comment]
We have been working on a tax improvement https://github.com/nexopos/v3-issues/issues/358
We believe it should have fixed this issue.

**Comment by alsaihati** [comment]
Unfortunately not fixed !!

See attached please:

![image](https://user-images.githubusercontent.com/40363522/94202881-24594a80-fec7-11ea-8486-35aea1a16702.png)

**Comment by Blair2004** [comment]
Update not yet releases thanks

On Sep 24, 2020 10:37 PM, "alsaihati" <notifications@github.com> wrote:

Unfortunately not fixed !!

See attached please:

[image: image]
<https://user-images.githubusercontent.com/40363522/94202881-24594a80-fec7-11ea-8486-35aea1a16702.png>

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/nexopos/v3-issues/issues/336#issuecomment-698601904>,
or unsubscribe
