### ISSUE TITLE
NexoStore Modifier Pricing Update

### ISSUE THREAD

**Issue by nasirqureshiofficial** [nexopos/v3-issues#337]
**Username** :  nasirqureshiofficial

**Describe the bug**
The products on woocommerce if having modifiers having price either sale / retail does not update once modifier selected, it should be automatically update if any or all modifier selected, currently it is adding modifier price + retail price and add into cart.

This should be also done while adding product into cart on category pages.

**To Reproduce**
1. Go to 'any product / category page'
2. Click on 'modifier and check no price will update'

Thanks

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
