### ISSUE TITLE
SOK price is double count for item with Modifier

### ISSUE THREAD

**Issue by cheing** [nexopos/v3-issues#341]
**Username** : cheing
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
SOK price is double count for item with Modifier

**To Reproduce**
1. Go Self Order Kiosk order page
1. Go to Category 'Hot Sub'
2. Click on 'Laksa' ($5)
3. Select Size 'Medium' +$2
4. Screen total amount is $7 (correct price)
5. Print and system show is $9 (total amount + modifier )

if order via Open POS it work fine, will get $7
 
**Screenshots**
![WhatsApp Image 2020-07-20 at 19 22 29](https://user-images.githubusercontent.com/3164019/87938858-c163c580-cac9-11ea-814c-d6aa31d1a5ed.jpeg)
![WhatsApp Image 2020-07-20 at 19 22 47](https://user-images.githubusercontent.com/3164019/87938875-c58fe300-cac9-11ea-962a-889745d4ed7a.jpeg)
![WhatsApp Image 2020-07-20 at 19 18 09](https://user-images.githubusercontent.com/3164019/87938903-d2143b80-cac9-11ea-9a45-50224a2dd3da.jpeg)

**Environment (please complete the following information):**
 - NexoPOS: [3.15.40]
 - Gastro [2.3.102]
 - Self Order Kiosk - Gastro Extension v1.12.5
 - PHP version [e.g. 7.1.33]
 - MySQL version [5.0.12]
 - Devise used (desktop browser,  kiosk).

**Comment by Blair2004** [comment]
ongoing

**Comment by cheing** [comment]
?
