### ISSUE TITLE
Warehouse setting : cant able to see at main dashboard, 

### ISSUE THREAD

**Issue by santoshroshan** [nexopos/v3-issues#342]
i wanna change currency symbol at nexo 
![a8d31d92-aebd-4f53-bf80-e7aa68e04290](https://user-images.githubusercontent.com/7972320/88389689-941e5c80-cdd4-11ea-81c3-1e1be7443741.jpg)
main dashboard , 
but cannot see setting for that , 
see attachment

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
You need to disable the multi-store and change the settings while on single store mode and re-enable the multistore.
