### ISSUE TITLE
Orders are doubled when they are splited or merged

### ISSUE THREAD

**Issue by mahmoud-Elshahawy** [nexopos/v3-issues#343]
**Username** : Penta
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
When order on table is splitted or 2 orders are merged when the new order is cashed it is printed again to the kitchen if the order is not cooked as we didn't use kitchen screen so no order is cooked.

**To Reproduce**
1. Go to 'spliting'
2. SPLIT ANY ORDER
3. Try to cash any of splited orders

**Expected behavior**
When order is splited or merged or any normal order on table when it cashed it shouldn't be depending on order status as in v 2.3.95  the normal order isn't printed again the splited and merged only
Also if new item is send to table after spliting or merging the whole order is printed to kitchen.

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [3.15.34]
 - Gastro  [ 2.3.95]
 - PHP version [7.1]
 - MySQL version [5.6]
 - Devise used [Desktop browser]

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hi, i've reviewed your account on [Nexo Platform](https://platform.nexopos.com), it seems like you no longer have valid licences. 
                Please note that in order to receive support and updates, your licences (purchase code) need to be renewed on CodeCanyon.

**Comment by nexopos** [comment]
Hi, i've reviewed your account on [Nexo Platform](https://platform.nexopos.com), it seems like you no longer have valid licences. 
                Please note that in order to receive support and updates, your licences (purchase code) need to be renewed on CodeCanyon.

**Comment by Blair2004** [comment]
Alright, ongoing.
