### ISSUE TITLE
pin login is not working 

### ISSUE THREAD

**Issue by waris85** [nexopos/v3-issues#345]
**Username** : waris85
Provide a username as created on the Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
after creating in for users in the setting. I tried to log in on the front end and the screen just goes unresponsive

**To Reproduce**
create login pin for user and go to front end and logout and login again with pin

**Expected behavior**
it should loin to pos screen but doing nothing 
**Screenshots**
https://www.loom.com/share/61883a32c3de4e27a2bedc8c2d091c81

**Environment (please complete the following information):**
 - NexoPOS:  3.15.41
 - Gastro (if installed) 2.3.102
 - PHP version [e.g. 7.2
 - MySQL version 5.6
 - Devise used (desktop browser, smartphone, POS system).  windows 10 chrome browser

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Hi, make sure to enable the frontend.
![screenshot-nexopos std-2020 08 11-11_39_52](https://user-images.githubusercontent.com/5265663/89888190-74a27480-dbc7-11ea-9f70-ffa5c02b35d8.jpg)

**Comment by Blair2004** [comment]
Note that, your system might display a blank page, as NexoPOS 3.x doesn't have a frontend. Just bookmark https://yourdomain.com/dashboard to reach the dashboard.

**Comment by waris85** [comment]
I tried that but no luck. I also have problem updating Nexo from
auto-updater

**Comment by Blair2004** [comment]
Another issue needs to have another ticket. Regarding the Pin Login Module issue, please reach us in the community and mention this issue : https://nexopos.com/join-the-community/

**Comment by waris85** [comment]
I alreday posted there. And someone from your team ask me to post on git
hub. Now back to same place.
Thanks

**Comment by Blair2004** [comment]
Actually, please just reference this issue on the community so that an agent can reach you privately as setup detail can't be shared here.

**Comment by Blair2004** [comment]
Solved

**Comment by kochdigits** [comment]
Hi, Having this exact issue. The PIN doesn't login. On click of Print, it does nothing. No error, nothing. 
The frontend is enabled.

**Comment by nexopos** [comment]
NexoPOS 3.x is not longer supported. Consider using NexoPOS 4.x instead : https://github.com/Blair2004/NexoPOS-4x

**Comment by kochdigits** [comment]
> NexoPOS 3.x is not longer supported. Consider using NexoPOS 4.x instead : https://github.com/Blair2004/NexoPOS-4x

Yes, we have purchased this and still testing it. As we cannot be able to use 4x now. Recipe Management is top priority for us. If we can get the 3x fully working as we wait for the features we want on 4x to be available.
