### ISSUE TITLE
Stock Transfer not work correctly

### ISSUE THREAD

**Issue by nuwansampath94** [nexopos/v3-issues#346]
**NEXOPOS Version**: V3.15.40

**Explain**:

Now in nexopos when we transfer stock one to other store we have to face issue:

* Item name changed
* categories changed in item
* barcode and all details not correctly move
* automatically create same categories.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by Blair2004** [comment]
Wrong issue format
