### ISSUE TITLE
Issue: Stock Transfer not working correctly

### ISSUE THREAD

**Issue by nuwansampath94** [nexopos/v3-issues#347]
**Username** : nuwansampath
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
When transfer stock, one shop to other shop, Stock transfer done correctly but transferred item details has been changed. some details not in correct field (ex: SKU code show in barcode field).
When stock transfer transferred shop item same categories create every transfer and item categories also changed.   

**To Reproduce**
1. Go to shop 1 'Stock Transfer'
2. Make new stock transfer to shop 2
3. Accept Stock transfer in shop 2
4. Go to shop 2 Item list and categories list you can see errors
5. Do 2 stock transfer shop 1 to shop 2 then you can see same categories creating issue.

**Environment (please complete the following information):**
 - NexoPOS: V3.15.40
 - Gastro (if installed) : NO
 - PHP version : 7
 - MySQL version : 5.6
 - Devise used : Desktop Google Chrome

**Additional context**
After fix this issue I need to get only change files. How can I do it.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "nuwansampath94" on [Nexo Platform](https://platform.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-05-23 21:21:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-06-02 04:56:41</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2021-01-06 08:33:37</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>
