### ISSUE TITLE
Item Import Function nOt working Correctly

### ISSUE THREAD

**Issue by waris85** [nexopos/v3-issues#348]
**Username** : waris85@gmail.com
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**

when I try the Bulk Import Function. it importing the items but not importing the category. whether the category Exist or not.  when Category Don't Exist, it creating the category but not adding to items.

when i exporting the prdct list it give me coloums like tax and tax types and item types but when i import the items there is not options to add those coloums when we map out the CSV File . 

it is very hard to go edit one item at a time specially when item is very last we have to go to those items by clicking Next Page and when We Edit that itme and go back to the list . it show first tems not where we left . now we have to navigate to those items 

there should be option of quick edit form item list screen itself  . 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Provide" on [Nexo Platform](https://platform.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Provide" on [Nexo Platform](https://platform.nexopos.com).
                    Note that, maybe the issue is not well formatted as well, please consider reading [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/). 
                    Regards.

**Comment by Blair2004** [comment]
Hi, please consider providing a sample CSV you've been using.

**Comment by Blair2004** [comment]
Hi, please consider sharing your CSV file so that we can proceed. otherwise the issue will be closed for inactivity.

**Comment by Blair2004** [comment]
Closed for inactivity.
