### ISSUE TITLE
doesn't works  Warehouse › Sales List Delete Selected option 

### ISSUE THREAD

**Issue by kamranbhutto** [nexopos/v3-issues#349]
**username** : kamranbhutto
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
doesn't works  Warehouse › Sales List Delete Selected option 
pos/dashboard/stores/1/nexo/orders
Item ID: 16195010

**To Reproduce**
1. Go to pos/dashboard/stores/1/nexo/orders
2. Click on : Delete Sale , Delete Selected

**Expected behavior**

**Screenshots**
![WhatsApp Image 2020-09-02 at 10 22 26 PM](https://user-images.githubusercontent.com/3133422/92017758-aa252280-ed6d-11ea-9fa2-00e6bc797b16.jpeg)
![WhatsApp Image 2020-09-02 at 10 25 24 PM](https://user-images.githubusercontent.com/3133422/92017764-ac877c80-ed6d-11ea-9d41-daf0e38e35a1.jpeg)

**Environment (please complete the following information):**
 - NexoPOS: update new 
 - PHP version 7.1 (ea-php71) 
 - Version information: 4.9.5
 - Devise used (desktop Firefox,Google Chrome, POS system,laptop,).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by kamranbhutto** [comment]
> 
> 
> Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).
why cannot you understand  i share you screenshot with

**Comment by kamranbhutto** [comment]
pos/dashboard/stores/1/nexo/orders
![Screenshot_13](https://user-images.githubusercontent.com/3133422/92018423-962df080-ed6e-11ea-9df6-4097dabcd215.jpg)

**Comment by nexopos** [comment]
Hi, i've reviewed your account on [Nexo Platform](https://platform.nexopos.com), it seems like you no longer have valid licences. 
                Please note that in order to receive support and updates, your licences (purchase code) need to be renewed on CodeCanyon.

**Comment by kamranbhutto** [comment]
Item Purchase Code:
0dfae282-54d4-4ba1-869f-29fcec7b1bc6

**Comment by kamranbhutto** [comment]
> 
> 
> Hi, i've reviewed your account on [Nexo Platform](https://platform.nexopos.com), it seems like you no longer have valid licences.
> Please note that in order to receive support and updates, your licences (purchase code) need to be renewed on CodeCanyon.

Item Purchase Code:
0dfae282-54d4-4ba1-869f-29fcec7b1bc6

**Comment by Blair2004** [comment]
Hi, the support on that purchase code has expired. Please consider renewing your support on CodeCanyon.

**Comment by kamranbhutto** [comment]
this is not support problem , i code download update this is not fair Really i am upset

**Comment by Blair2004** [comment]
Being deleted on the online demo it works : 
![image](https://user-images.githubusercontent.com/5265663/92126211-cbcaec00-edf7-11ea-884c-b96487f95bc0.png)

As you can notice.
![image](https://user-images.githubusercontent.com/5265663/92126136-b48bfe80-edf7-11ea-9a60-5d0e496330e5.png)

In order for us to take a closer look at your installation, consider renewing your support. Feel free to reopen this thread anytime when it will happen.

Kind Regards.

**Comment by kamranbhutto** [comment]
> 
> 
> Being deleted on the online demo it works :
> ![image](https://user-images.githubusercontent.com/5265663/92126211-cbcaec00-edf7-11ea-884c-b96487f95bc0.png)
> 
> As you can notice.
> ![image](https://user-images.githubusercontent.com/5265663/92126136-b48bfe80-edf7-11ea-9a60-5d0e496330e5.png)
> 
> In order for us to take a closer look at your installation, consider renewing your support. Feel free to reopen this thread anytime when it will happen.
> 
> Kind Regards.

okay today i download your code update after i check and see whats new and i send you later updates OK

**Comment by kamranbhutto** [comment]
> 
> 
> > Being deleted on the online demo it works :
> > ![image](https://user-images.githubusercontent.com/5265663/92126211-cbcaec00-edf7-11ea-884c-b96487f95bc0.png)
> > As you can notice.
> > ![image](https://user-images.githubusercontent.com/5265663/92126136-b48bfe80-edf7-11ea-9a60-5d0e496330e5.png)
> > In order for us to take a closer look at your installation, consider renewing your support. Feel free to reopen this thread anytime when it will happen.
> > Kind Regards.
> 
> okay today i download your code update after i check and see whats new and i send you later updates OK

![Screenshot_3](https://user-images.githubusercontent.com/3133422/92233353-91ca1a80-eec9-11ea-907b-ea94b93f9308.jpg)
today i download update NexoPOS 3.x  same i see problem Delete is not working

**Comment by kamranbhutto** [comment]
> 
> 
> > > Being deleted on the online demo it works :
> > > ![image](https://user-images.githubusercontent.com/5265663/92126211-cbcaec00-edf7-11ea-884c-b96487f95bc0.png)
> > > As you can notice.
> > > ![image](https://user-images.githubusercontent.com/5265663/92126136-b48bfe80-edf7-11ea-9a60-5d0e496330e5.png)
> > > In order for us to take a closer look at your installation, consider renewing your support. Feel free to reopen this thread anytime when it will happen.
> > > Kind Regards.
> > 
> > 
> > okay today i download your code update after i check and see whats new and i send you later updates OK
> 
> ![Screenshot_3](https://user-images.githubusercontent.com/3133422/92233353-91ca1a80-eec9-11ea-907b-ea94b93f9308.jpg)
> today i download update NexoPOS 3.x same i see problem Delete is not working

i download Fresh database  after your Delete is not working why every thing is new
