### ISSUE TITLE
Item Purchase Code

### ISSUE THREAD

**Issue by kamranbhutto** [nexopos/v3-issues#350]
Item Purchase Code:
0dfae282-54d4-4ba1-869f-29fcec7b1bc6

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Invalid Issue Form
