### ISSUE TITLE
Can't update an order after putting on HOLD

### ISSUE THREAD

**Issue by fjacebal** [nexopos/v3-issues#351]
**Username** : 
griot.digital

**Describe the bug**
When an order is set to HOLD is not possible to update the order (neither adding new product nor paying)

**To Reproduce**
In the POS:
Click on the products / Click on HOLD
Searching the order in the HOLD menu / selecting the order / edit the order
If: I'm adding a new product: click on the product / Hold / Put on hold > ERROR
If: click on Pay / Pay > ERROR

I get this: 
Uncaught TypeError: Cannot read property 'addEventListener' of null at pos.cash-out.js:2
pos:4564 Report has been send
/rest/nexo/order/2/36?store_id=4:1 Failed to load resource: the server responded with a status of 501 ()
/rest/nexo/order/2/38?store_id=4:1 Failed to load resource: the server responded with a status of 501 ()
DevTools failed to load SourceMap: Could not load content for https://***/public/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Expected behavior**
To update the order

**Environment (please complete the following information):**
CMS 3.1.4
NexoPOS v3.15.42
Gastro v2.3.103 (tested with and without)
PHP: Tested 7.1, 7.2, 7.3
10.2.33-MariaDB

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "griot" on [Nexo Platform](https://platform.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by fjacebal** [comment]
Cause is not "griot", it's griot.digital 

Please, check it carefully

**Comment by Blair2004** [comment]
Hi, after further test on this we haven't been able to reproduce that issue. We'll need to check your system in detail to find out what might cause that issue. Please reach me on WhatsApp for live assistance on this.

**Comment by Blair2004** [comment]
closed for inactivity
