### ISSUE TITLE
Sales bill state "In progress" 

### ISSUE THREAD

**Issue by mani-mani14691** [nexopos/v3-issues#352]
Dear sir ,

Please find   attached in progress screenshot.
![inprogress](https://user-images.githubusercontent.com/71064266/92698853-80ba5700-f36a-11ea-98f9-ad34ed298905.JPG)

Some bills state "in progress"  , why in progress comming and  how to slove this ?

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Please consider filling a valid issue as suggested in our tutorial. This will ensure commonly asked questions are answered 

https://nexopos.com/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items
