### ISSUE TITLE
Custom SMS Gateway

### ISSUE THREAD

**Issue by freefugga** [nexopos/v3-issues#354]
**Username**:  freefugga

**Is your feature request related to a problem? Please describe.**
The current integrated SMS gateways are way too costly for people like us in India. We get SMS Packages for 6 times cheaper than current rate on Twilio and BulkSMS. Check pricing of India on msg91.com

**Describe the solution you'd like**
Consider a custom payment gateway field so that all of the users can use their local gateway with ease. Screenshot attached for reference.

**Describe alternatives you've considered**
There can be no alternative to this. Either you add the gateway yourself or leave the fields for the user to allow them to add their own favorite gateway.

**Additional context (optional)**
Screenshot Attached from UltimatePOS. I have been using it for a year successfully. All my messages gets delivered. They use custom gateway only. Please add this as soon as possible. I'll also provide the relevant code file if you want from UltimatePOS.
![Capture](https://user-images.githubusercontent.com/71607226/93733981-21273b80-fbf5-11ea-9d08-cbb0cfea3962.JPG)

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "freefugga" on [Nexo Platform](https://platform.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by Blair2004** [comment]
We don't further plan to improve NexoPOS 3.x that will be considered on NexoPOS 4.x
