### ISSUE TITLE
Discount not working , it's showing calculator formats

### ISSUE THREAD

**Issue by mani-mani14691** [nexopos/v3-issues#355]
**Username** : 

stepinpos

**Describe the bug**
We have two installation system

1. Only pos system - discount working fine.
2 . Pos with gastro system - discount not working,it's showing calculator formats

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. screenshot added

**Environment (please complete the following information):**
 - NexoPOS: v3.14.70
 - Gastro (if installed) [ v2.3.61]
 - PHP version [ 7.2]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
![dak discount](https://user-images.githubusercontent.com/71064266/93747300-1f20a500-fc14-11ea-85ab-d77ab309bbac.JPG)
![pos discount screen](https://user-images.githubusercontent.com/71064266/93747306-221b9580-fc14-11ea-87fd-e4986d6fdd3f.JPG)

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Provide" on [Nexo Platform](https://platform.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "Provide" on [Nexo Platform](https://platform.nexopos.com).
                    Note that, maybe the issue is not well formatted as well, please consider reading [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/). 
                    Regards.

**Comment by nexopos** [comment]
Hi, i've reviewed your account on [Nexo Platform](https://platform.nexopos.com), it seems like you no longer have valid licences. 
                Please note that in order to receive support and updates, your licences (purchase code) need to be renewed on CodeCanyon.

**Comment by Blair2004** [comment]
Not proven
