### ISSUE TITLE
My account 

### ISSUE THREAD

**Issue by Thomas23-ws** [nexopos/v3-issues#356]
**Username** : pollock Thomas 
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "pollock" on [Nexo Platform](https://platform.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by Thomas23-ws** [comment]
This is my login details thomaspollard57@gmail.com
Password Framer72!! Then I tried changing the email with kelvinkesh9@gmail.com and change some settings but I have my bitcoin wallet did I lost my account

**Comment by Blair2004** [comment]
Closed for not having a readable format.
