### ISSUE TITLE
This is my login details thomaspollard57@gmail.com

### ISSUE THREAD

**Issue by Thomas23-ws** [nexopos/v3-issues#357]

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Thomas23-ws** [comment]
> 

Please how can I get my bitcoin

**Comment by Blair2004** [comment]
Closed for not having a readable format.

**Comment by Blair2004** [comment]
For information, this is not a repository for nexo.io
