### ISSUE TITLE
Kniv

### ISSUE THREAD

**Issue by Thomas23-ws** [nexopos/v3-issues#359]
Shh GH

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "" on [Nexo Platform](https://platform.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by Thomas23-ws** [comment]
Scam site

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).
