### ISSUE TITLE
Missing validation on item add page

### ISSUE THREAD

**Issue by umair975** [nexopos/v3-issues#361]
**Username** : 
umair975

**Describe the bug**
no error when sku is missing or space in barcode

**To Reproduce**
add product write barcode with space. it will accept but on POS it will give error on adding product to order
also add item without sku or barcode and save. it will not save but wont give any error.

**Expected behavior**
error highlighting the field.

**Comment by Blair2004** [comment]
Hi, 
issue proven, as we cannot ask people to fill barcode, we'll rather make sure it avoids the issue you faced while loading the item from the POS.
