### ISSUE TITLE
the partially paid orders(paid and unpaid amount) are not showing in detailed sales report - Its is very important and Emergency

### ISSUE THREAD

**Issue by mani-mani14691** [nexopos/v3-issues#363]
**Username** : 
stepinpos

**Describe the bug**

    the partially paid orders are not showing in detailed sales report.
    In sales paid and Unpaid amount not showing detailed sales report.
    is there a way to find how many orders i have received partial payment against the orders"

**To Reproduce**
1. Go to 'Reports '
2. Click on 'Detailed reports'
4. See error  :  the partially paid orders(paid and unpaid amount) are not showing in detailed sales report 

**Expected behavior**
I have more sales order some paid and unpaid amount  done . but its not showing detailed reports . Its is very important and Emergency.  

**Screenshots**
attached screenshot

**Environment (please complete the following information):**
 - NexoPOS: v3.15.51
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version 7.2
 - MySQL version 5.6
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
![two reports screenshot](https://user-images.githubusercontent.com/71064266/103461128-f4c9a200-4d41-11eb-8859-64bf147ab3be.JPG)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS 3.x - Extendable PHP Point of Sale</td>
                                <td>2021-11-26 04:12:15</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2021-03-24 14:14:00</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-06-11 10:39:55</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2021-03-24 14:14:00</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2021-03-27 13:11:52</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS 3.x - Extendable PHP Point of Sale</td>
                                <td>2021-11-26 04:12:15</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, 

Thank you for submitting this request.

As you might be aware already, we're no more likely to provide improvement to NexoPOS 3.x. The current report as it has been made was intentionally set to not count partially paid orders on the report. As this is an improvement, you're invited to hire a developer for helping you adjust the system in the way you desire. 

We remain available to guide your developer into the files he needs to adjust or if he has any other related questions.

Kind Regards.
