### ISSUE TITLE
Printing in dine-in as image

### ISSUE THREAD

**Issue by mahmoud-Elshahawy** [nexopos/v3-issues#369]
**Username** :  
penta

Describe the bug
after enable converting the receipt as image when i try to print the receipt from nps print button or register button from dine in tables it print the receipt without converting so the Arabic items are printed in symbols.

To Reproduce
1. Go to dine in in pos screen
2. Click on register print button from any opened table

Expected behavior
print the receipt in an image form as items are in Arabic language .

Environment (please complete the following information):
 - NexoPOS: [3.15.31]
 - Gastro (if installed) [2.3.106]
 - PHP version [7.2]
 - MySQL version [5.6]
 - Devise used (desktop browser).

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Hum... it seems like we cannot understand well your issue. If you still face issue understanding that, you're invited to read [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/).

**Comment by nexopos** [comment]
Sorry, this thread has exceeded the maximum modification allowed. This thread will now be closed, but you still have the capacity to create a new one.
