### ISSUE TITLE
Error on Item list 

### ISSUE THREAD

**Issue by jalaj-mohan** [nexopos/v3-issues#376]
**Username** : 
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.
my nexopos
username : cognify.mail@gmail.com

Nexopos
link : http://breadstory.in/cognifypos
username : demopos
password : demopos@123

**Describe the bug**
showing this error on **Item list** option page

ity: 8192

Message: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

Filename: models/Nexo_Products.php

Line Number: 58

Backtrace:

File: /home/vdtecno/public_html/breadstory/cognifypos/application/core/Tendoo_Exceptions.php
Line: 281
Function: include

File: /home/vdtecno/public_html/breadstory/cognifypos/application/core/Tendoo_Loader.php
Line: 374
Function: _error_handler

File: /home/vdtecno/public_html/breadstory/cognifypos/application/core/Tendoo_Loader.php
Line: 374
Function: require_once

File: /home/vdtecno/public_html/breadstory/cognifypos/application/modules/nexo/controllers/items.php
Line: 34
Function: model

File: /home/vdtecno/public_html/breadstory/cognifypos/application/modules/nexo/controllers/items.php
Line: 389
Function: crud_header

File: /home/vdtecno/public_html/breadstory/cognifypos/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Route/Route.php
Line: 119
Function: call_user_func_array

File: /home/vdtecno/public_html/breadstory/cognifypos/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php
Line: 267
Function: renderRoute

File: /home/vdtecno/public_html/breadstory/cognifypos/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php
Line: 52
Function: routeRequest

File: /home/vdtecno/public_html/breadstory/cognifypos/application/modules/nexo/controllers/stores.php
Line: 232
Function: start

File: /home/vdtecno/public_html/breadstory/cognifypos/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Route/Route.php
Line: 119
Function: call_user_func_array

File: /home/vdtecno/public_html/breadstory/cognifypos/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php
Line: 267
Function: renderRoute

File: /home/vdtecno/public_html/breadstory/cognifypos/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php
Line: 52
Function: routeRequest

File: /home/vdtecno/public_html/breadstory/cognifypos/application/controllers/Dashboard.php
Line: 280
Function: start

File: /home/vdtecno/public_html/breadstory/cognifypos/index.php
Line: 315
Function: require_once

**To Reproduce**
1. Go to **inventory**
2. Click on **itemlist**
3. Scroll down to 
4. See error on top

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: 3.17.1
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version 7.4
 - MySQL version 82
 - Devise used (desktop browser-crome)

**Additional context**
Problem is arising because i change my hosting space and updated the latest version of nexopos as well as i updated server php version 5.6 to 7.4

**Comment by Blair2004** [comment]
Hi, Fixed with the upcoming release
