### ISSUE TITLE
No Tax on Receipt

### ISSUE THREAD

**Issue by araufqazi** [nexopos/v3-issues#379]
**Username** : 
arqinc
arauf.qazi@gmail.com 

**Describe the bug**
I have 2 registers on my system. When i place an order from one register but pay for that order throuth another register, the taxes do not show up on the receipt.

**To Reproduce**
1. Open Waiter Register 
2. Create an order and send it to the kitchen 
3. Open Main Register.
4. Go to ready orders and fetch the order from the list
5. Make the payment and receipt will pop up
6. See error 

**Expected behavior**
There should be a clear breakdown of taxes which ever register i use to place rhe order

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: v3.17.6
 - Gastro: v2.3.109
 - PHP version: 7.4.11
 - MySQL version: 10.1.48-MariaDB
 - Devise used: Desktop Browser 

**Additional context**

**Comment by Blair2004** [comment]
Hi, 
Note that your support has actually expired on all of your licenses. To receive help, consider renewing the license for NexoPOS 3.x at least. 

Kind Regards
