### ISSUE TITLE
Gastro french .po file error

### ISSUE THREAD

**Issue by kxygol** [nexopos/v3-issues#38]
**Username**
kxygol

**Describe the bug**
Error
```sh
File gastro\views\templates\table_selection.php line 134
<h4><?php echo sprintf( __( '**Duration : <strong>%s</strong>**', 'gastro' ), '{{ duration( session.starts, tendoo.date ) }} ' );?></h4>
```
Gastro French .po file translate wrong format
```sh
English source text: Duration : <strong>%s</strong>
French Translate: Depuis <strong>%s</strong> Pour </strong>%s</strong>
```
**Screenshots Error**
![3](https://user-images.githubusercontent.com/12599903/43034612-368c8e02-8d12-11e8-8e59-6c7f12ee00d1.jpg)

**To Reproduce**
1. when you already have customer dine-in at table 1
2. and you click button dine-in at checkout/pos screen
3. choose table 1 and you will see error like in screenshot.

**Environment (please complete the following information):**
- NexoPOS: 3.12.14
- Gastro: 2.3.14
- PHP version 7.1.18
- MySQL version: mariaDB 10.1.33
- Devise used: desktop browser, android smartphone

**How to fix**
change french translate like english source format
```sh
etc: Durée: <strong>%s</strong>
```

**Notes**
I still find lots of typo like this in .po file, and this one make error.
i found this typo because i'm using fr.po file to translate to indonesia.

**Comment by Blair2004** [comment]
Thank you for this. The issue will be fixed for the version 3.12.16
