### ISSUE TITLE
No Activate SMS Button 

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#4]
Hello ,

No activate SMS button to send invoice via SMS, no button available in checkout page please see the screenshot below ---
![ascapture](https://user-images.githubusercontent.com/32275898/41865837-ebd44224-78cb-11e8-862b-e98c55a8a466.PNG)

![222capture](https://user-images.githubusercontent.com/32275898/41865619-45feb15e-78cb-11e8-96d1-e4d0407d60ff.PNG)

**Comment by nexopos** [comment]
Have you activated the module SMS ?

**Comment by vishalwalia1** [comment]
yes i did

**Comment by Blair2004** [comment]
Going to investigate on this.
