### ISSUE TITLE
It does not allow access to users.

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#40]
**Username**
israelga

**Describe the bug**
It does not allow access to a registered user.

**To Reproduce**
1. Go to http://domain.com/sign-in
2. I enter the access data and password.
3. Error message.

Image of the error https://www.screencast.com/t/eLxeLhnx4

**Expected behavior**
That users can use NEXOPOS

**Screenshots**
https://www.screencast.com/t/eLxeLhnx4

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser).

**Additional context**

**Comment by israelga** [comment]
Now it has allowed me to access, but it does not allow me to access the ATM. Report this error: https://www.screencast.com/t/mmnqp8avX8

**Comment by Blair2004** [comment]
Hi
back to complete a review on this. I would like to know. What is the role of the user which is restricted to access to the Dashboard ?

**Comment by israelga** [comment]
Shop Manager

**Comment by israelga** [comment]
When will the issue of user access be solved?

**Comment by israelga** [comment]
I just updated but the problem is not solved, I have tried with different roles but it does not allow access.

**Comment by Blair2004** [comment]
Have you tested a fresh installation or have you tested with your old database. Since from our side (fresh installation) it's okay.

**Comment by israelga** [comment]
Hi.

With the update 3.12.18 does not allow you to correctly access users.

**Comment by Blair2004** [comment]
Can you make a video on what that happen (starting with a fresh installation) Thank you.
