### ISSUE TITLE
Supporting Multiple Register in a LAN

### ISSUE THREAD

**Issue by sandisurya** [nexopos/v3-issues#41]
**Is your feature request related to a problem? Please describe.**
I have 3 Register PC and each of it connected with IP Thermal Printer, I setup NexoPos & Gastro in my Servers and all of my Register are using the same DB
 
For printing, I bought 3 licenses of your Nexo Print Server and install it on each Register, it works for sometimes, but randomly in random Register PC, the printer list are gone so it can't print. I have to logout and login again and its started to print again.

**Describe the solution you'd like**
Please make Nexo Print Server capable of handling multi Register in LAN

**Comment by Blair2004** [comment]
This feature has been implemented on 3.12.17
