### ISSUE TITLE
Issue : Supply invoice is not change total amount

### ISSUE THREAD

**Issue by awdbox1** [nexopos/v3-issues#43]
**awdbox**
username on Nexo : https://api.nexopos.com/register. 

**awdbox1**
username on www.codecanyon.net

If I went to adjustment of quantity and change item quantity , 
the total amount in " Supply invoice " is not changing

**To Reproduce**
1. Go to 'supplies'
2. Click on 'option'
3. Scroll down to 'supply invoice'
4. check the Quantity and Total is not is not equal

![capture](https://user-images.githubusercontent.com/40467347/43350552-50630930-9219-11e8-935f-d2f1619997b3.JPG)

**Environment ():**
 - NexoPOS: [v3.12.8]
 - PHP version [5.6.30]
 - MySQL version [5.6.39-cll-lve - MySQL Community Server (GPL)]

 - Devise used (desktop browser, chrome browser).

**Comment by Blair2004** [comment]
Hi,
the stock adjustment doesn't change the quantity of the supply. But register the operation on the product history. The Stock Taking summary just display what has been supplied and how many quantity has been supplied. You can change the quantity supplied directly by editing the supply entry, and that will affect the total quantity here.

Hope that make any sense for you.

**Comment by Blair2004** [comment]
Closed due to inactivity.
