### ISSUE TITLE
Merge and Split Problems

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#44]
Merge Problems
We merged 2 tables for example TABLE A and TABLE B, we want to be TABLE B merged with TABLE A, but we havent checkout yet! There are still customers on the TABLE A. We want to make a new order to TABLE A, But when we go to TABLE A, we see that TABLE A seems avaliable and  has no orders, only  when we choose the TABLE A and When we add some product, we can see all orders belong to TABLE A.

[merged problems video.zip](https://github.com/nexopos/v3-issues/files/2238289/merged.problems.video.zip)

Split Problems
We cannot split with one item. For example, you make an order with the same item 3 times. The system cannot allow to make a split. We need to add different items to be able to split.I think that it s not a good thing.

[split problems video.zip](https://github.com/nexopos/v3-issues/files/2238286/split.problems.video.zip)

Please download and see what is the problem.

**Comment by Blair2004** [comment]
Thank you for submitting this issue. We'll investigate on this.

**Comment by Blair2004** [comment]
However, for splitting, It only works if items are different. We'll see if it's possible to split based on the quantity.

**Comment by scilang** [comment]
Thank you good luck on you my friend

**Comment by scilang** [comment]
My Friend, is there any progress about problems?

**Comment by Blair2004** [comment]
The merge problem has been fixed. We're looking ahead to se ehow we can implement the improvement of the split feature.
