### ISSUE TITLE
edit register error, can't save config on NP3.12.17

### ISSUE THREAD

**Issue by sandisurya** [nexopos/v3-issues#45]
**Username**
sandisurya

**Describe the bug**
Updated to NP 3.12.17, but when I tried to configure register in order to print to my printer for each register it gave an error

**To Reproduce**
1. Access Store
2. Register - Register List
3. Edit Register
4. See error :
A PHP Error was encountered
Severity: Notice
Message: Undefined property: stdClass::$type
Filename: views/edit.php
Line Number: 136
Backtrace:
File: C:\xampp\htdocs\application\modules\grocerycrud\views\edit.php
Line: 136
Function: _error_handler

File: C:\xampp\htdocs\public\modules\grocerycrud\grocery_crud\themes\bootstrap\views\edit.php
Line: 1
Function: include_once

File: C:\xampp\htdocs\application\libraries\Grocery_CRUD.php
Line: 2780
Function: include

File: C:\xampp\htdocs\application\libraries\Grocery_CRUD.php
Line: 1785
Function: _theme_view

File: C:\xampp\htdocs\application\libraries\Grocery_CRUD.php
Line: 4494
Function: showEditForm

File: C:\xampp\htdocs\application\modules\nexo\controllers\registers.php
Line: 114
Function: render

File: C:\xampp\htdocs\application\modules\nexo\controllers\registers.php
Line: 225
Function: crud_header

File: C:\xampp\htdocs\application\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Route\Route.php
Line: 119
Function: call_user_func_array

File: C:\xampp\htdocs\application\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php
Line: 267
Function: renderRoute

File: C:\xampp\htdocs\application\vendor\pecee\simple-router\src\Pecee\SimpleRouter\SimpleRouter.php
Line: 52
Function: routeRequest

File: C:\xampp\htdocs\application\modules\nexo\controllers\stores.php
Line: 217
Function: start

File: C:\xampp\htdocs\application\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Route\Route.php
Line: 119
Function: call_user_func_array

File: C:\xampp\htdocs\application\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php
Line: 267
Function: renderRoute

File: C:\xampp\htdocs\application\vendor\pecee\simple-router\src\Pecee\SimpleRouter\SimpleRouter.php
Line: 52
Function: routeRequest

File: C:\xampp\htdocs\application\controllers\Dashboard.php
Line: 280
Function: start

File: C:\xampp\htdocs\index.php
Line: 283
Function: require_once

**Expected behavior**
We want to enable the new features in NP in order to support multi register with multi printer support in LAN

**Screenshots**
screenshots-> ![2018-07-30_16-25-33](https://user-images.githubusercontent.com/41579628/43389189-403e889c-9415-11e8-8a84-e88847171060.jpg)

**Environment (please complete the following information):**
 - NexoPOS: 3.12.17
 - Gastro : 2.3.16
 - PHP version : 7.2.7
 - MySQL version : 5.6
 - Devise used : Desktop browser, XAMPP

**Additional context**

**Comment by Blair2004** [comment]
Hi, can you consider switching to php 7.1

**Comment by sandisurya** [comment]
Ok, I will test it now with PHP 7.1.19, and will let you know...

**Comment by Blair2004** [comment]
While using PHP 7.1 we don't have any issue. 
![image](https://user-images.githubusercontent.com/5265663/43392875-e77de266-93ec-11e8-97bf-e787d5cb24ab.png)

**Comment by sandisurya** [comment]
Fixed by Vishal... what a great Support, Thanks !!!
