### ISSUE TITLE
Does not allow to Edit the products

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#49]
** Username **
israelga

** Describe the error **
It DOES NOT allow to edit the products once created, a 404 error appears.

**To play**
1. Go to inventary
2. Click on the list of items
3. Click on edit product
4. Error 404

** Expected behavior **
That allows you to edit the product

** Screenshots **
https://www.screencast.com/t/lZOe6doQaQOK

** Environment (complete the following information): **
- NexoPOS: [p. 3.12.18]
- PHP version [p. 7.1]
- MySQL version [5.6]
- Designed used (desktop browser).

** Additional context **

**Comment by Blair2004** [comment]
Hi, 
we've yet provided a solution for this issue. What you have to do is to replace the following file : 
applications/modules/nexo/routes-array.php by this file https://raw.githubusercontent.com/nexopos/v3-issues/master/routes-array.php

**Comment by Blair2004** [comment]
The fix has been merged for the next version.
