### ISSUE TITLE
Print not working at the time of checkout

### ISSUE THREAD

**Issue by webumer** [nexopos/v3-issues#50]
webumer

Describe the bug
I’m using nexoPrint server.
And using multiple kitchen option.
When order enter into system, press button to kitchen, print goes for kitchen. 
Then order complete, I go to checkout, press checkout, receipt is not printing at that time. 
If I press print button, it’s not using nexoPrint, it’s shows browser pop up for print.

To Reproduce
1. Go to 'Open POS'
2. Add items to POS
3. Press To Kitchen 
4. Kitchen print Came out
5. Go to dine in
6. Press Checkout table or press print
7. Print not came out

Expected behavior
With NexoPrint server, kitchen print working fine, but normal bill not working

Environment 
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop Chrome, POS system).

Additional
Same problem with reports prints.

**Comment by Blair2004** [comment]
This issues has been fixed on the upcoming version of Gastro.
