### ISSUE TITLE
Number in receipt NPS cant read

### ISSUE THREAD

**Issue by kxygol** [nexopos/v3-issues#52]
**Username**
kxygol

**Describe the bug**
Number in bold can't read, 6 like 8

**Screenshots**
![font](https://user-images.githubusercontent.com/12599903/44018430-599244d8-9f0e-11e8-960d-37bd864e8129.png)

**Environment (please complete the following information):**
 - NexoPOS: 3.13.1
 - Gastro: 2.3.18
 - PHP version : 7.0
 - MySQL version 5.6
 - Devise used (desktop browser, smartphone)

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

**Comment by Blair2004** [comment]
The current configuration of Nexo Print Server, doesn't allow such modification for the meantime.
