### ISSUE TITLE
daily report based on qty sold

### ISSUE THREAD

**Issue by sandisurya** [nexopos/v3-issues#53]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
A new report for forecasting

**Describe alternatives you've considered**
This report will be used for tomorrow forecast, which food shall I prepare more for tomorrow

**Additional context**
Sample Report screenshot will be like this, we used to do it manually using excel pivot
![image](https://user-images.githubusercontent.com/41579628/44388117-7fcee680-a551-11e8-9814-618c43472e81.png)

**Comment by sandisurya** [comment]
Hi Blair, 
Sorry for the bad format, I have fix my comment in a proper way ... :)

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.
