### ISSUE TITLE
NPS option and NPS port

### ISSUE THREAD

**Issue by kxygol** [nexopos/v3-issues#54]
Feature Request: 

- Please add Nexo Print Server has option to print paid receipt 2 times ( 1 for customer, 1 for cashier)
- change NPS port from 3236 to port that most of VPS or Hosting open that port. because my vps block unusual port and can't open it. (can you make this as option, so i can input port number myself)

thank you

**Comment by Blair2004** [comment]
NPS doesn't goest to internet. At most it goes within a local network.

**Comment by kxygol** [comment]
ok thank you
