### ISSUE TITLE
Other users can not access

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#57]
**Username**
israelga

**Describe the bug**
The program does not allow access to other users created as cashiers, shop manager ... etc.

**To Reproduce**
look at the video
https://www.screencast.com/t/hsJi3HRmEI

**Expected behavior**
The program must let users access.

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.13.4]
 - PHP version [e.g. 7.1]
 - Devise used (desktop browser).

**Additional context**
Report of this problem more than 30 days ago. After several updates it is still not fixed.

**Comment by Blair2004** [comment]
Hi, 
the video doesn't show the screen entirely. I cannot set the error thrown while opening the register.

**Comment by israelga** [comment]
Watch the video: https://www.screencast.com/t/60Q83UNyWTNQ

**Comment by Blair2004** [comment]
What is the role of fatima ?

**Comment by israelga** [comment]
Now shopmanager, but before I tried it as a cashier and it did not work either

**Comment by Blair2004** [comment]
We've fixed permission for the cashier and the admin you should expect the fix on the next update. Thank you for your commitment.
