### ISSUE TITLE
Hide the rest of the stores at the cashiers

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#58]
**Is your feature request related to a problem? Please describe.**
israelga

**Describe the solution you'd like**
When an cashier accesses the program in advanced mode it can see all the business that the Admin has registered in the program, that information should be hidden.The cashier should only see the businesses to which he has access, but not those he does not have access to.There is the easy mode that reflects it in this way. Would not it be better and prettier if the screen was always in easy mode?The advanced mode does not have any interesting functionality in this case.

**Describe alternatives you've considered**
The cashier should only see the businesses to which he has access, but not those he does not have access to.

**Additional context**
Video: http://recordit.co/SB0tx1CjGw

**Comment by Blair2004** [comment]
Hi, we've updated that. We've restricted the access to the store table list to the administrator and the master user. The cashir has now only access to a view which shows the store where he only have access to .

![image](https://user-images.githubusercontent.com/5265663/44613065-65716300-a806-11e8-9186-bf3b86499c57.png)

**Comment by israelga** [comment]
Ok, perfect.
