### ISSUE TITLE
Problem when i select table

### ISSUE THREAD

**Issue by sergiotranchino** [nexopos/v3-issues#6]
username: amtcloud 

When insert the product and select a table i have this error

" PHP Error was encountered
Severity: Warning

Message: sprintf(): Too few arguments

Filename: templates/table_selection.php

Line Number: 136

Backtrace:

File: /web/pos/application/modules/gastro/views/templates/table_selection.php
Line: 136
Function: sprintf

File: /web/pos/application/core/Tendoo_Loader.php
Line: 1090
Function: include

File: /web/pos/application/core/Tendoo_Loader.php
Line: 621
Function: _ci_load

File: /web/pos/application/modules/gastro/controllers/RestaurantController.php
Line: 61
Function: module_view

File: /web/pos/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Route/Route.php
Line: 119
Function: call_user_func_array

File: /web/pos/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php
Line: 267
Function: renderRoute

File: /web/pos/application/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php
Line: 52
Function: routeRequest

File: /web/pos/application/controllers/Dashboard.php
Line: 280
Function: start

File: /web/pos/index.php
Line: 283
Function: require_once"

![schermata 2018-07-02 alle 17 23 00](https://user-images.githubusercontent.com/40768330/42172547-97d2b092-7e1c-11e8-9568-f1261f352e68.png)

**Comment by Blair2004** [comment]
Which language are you using ?

**Comment by sergiotranchino** [comment]
I traduce the po file in italian
