### ISSUE TITLE
Testing Oxen Bot

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#61]
**Username** : 
admin

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hello World. I'm oxen bot.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "13" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "13" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "13" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "17" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "admine" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, after having reviewed your account, we've not been able catch any licences.
                                Please note that, it's required to have a licence on your account, in order to receive updates and support. 
                                [Click here](https://api.nexopos.com/dashboard/profile/envato-licences/add) to add a new licence to your Nexo Platform account.
                                Regards.

**Comment by nexopos** [comment]
Hi, here is the status of your licences.

                                | ID | Application | Expire | Status | 
                                |------------------------------------|
                                | 1 | NexoPOS | 2018-08-28 01:06:04 | not-used

**Comment by nexopos** [comment]
Hi, here is the status of your licences.
| ID | Application | Expire | Status | 
                                |------------------------------------|
| 1 | NexoPOS | 2018-08-28 01:06:04 | not-used |

**Comment by nexopos** [comment]
Hi, here is the status of your licences.
| Tables        | Are           | Cool  |
                                | ------------- |:-------------:| -----:|
                                | col 3 is      | right-aligned | $1600 |
                                | col 2 is      | centered      |   $12 |
                                | zebra stripes | are neat      |    $1 |
                                
                                | ID | Application | Expire | Status | 
                                |------------------------------------|
| 1 | NexoPOS | 2018-08-28 01:06:04 | not-used |

**Comment by nexopos** [comment]
<p>Hi, here is the status of your licences.
| ID | Application | Expire | Status |
|------------------------------------|
| 1 | NexoPOS | 2018-08-28 01:06:04 | not-used |</p>

**Comment by nexopos** [comment]
<strong>Hello World</strong>

**Comment by nexopos** [comment]
<table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Test</td>
                                                <td>Test</td>
                                                <td>Test</td>
                                                <td>Test</td>
                                            </tr>
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Test</td>
                                                <td>Test</td>
                                                <td>Test</td>
                                                <td>Test</td>
                                            </tr>
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                        <td>1</td>
                                        <td>NexoPOS</td>
                                        <td>2018-08-28 01:06:04</td>
                                        <td>not-used</td>
                                    </tr>
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                        <td>1</td>
                                        <td>NexoPOS</td>
                                        <td>2018-08-28 01:06:04</td>
                                        <td>not-used</td>
                                    </tr>
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                        <td>1</td>
                                        <td>NexoPOS</td>
                                        <td>2018-08-28 01:06:04</td>
                                        <td>not-used</td>
                                    </tr>
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "maikolfamilia18" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "maikolfamilia18" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "maikolfamilia18" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                        <td>16195010</td>
                                        <td>NexoPOS</td>
                                        <td>2018-08-28 01:06:04</td>
                                        <td>not-used</td>
                                    </tr>
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "kxygol" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "kxygol" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                        Please note that you can choose between the following format : 
                            - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                            - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                        You might consider updating your issue and use the right version format. 
                        Regards.

**Comment by nexopos** [comment]
Hi, after having reviewed your account, we've not been able catch any licences.
                                Please note that, it's required to have a licence on your account, in order to receive updates and support. 
                                [Click here](https://api.nexopos.com/dashboard/profile/envato-licences/add) to add a new licence to your Nexo Platform account.
                                Regards.
