### ISSUE TITLE
Testing OxenBot 1

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#63]
**Username** : 
mahmoodi2

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                        <td>16195010</td>
                                        <td>NexoPOS - Extendable PHP Point of Sale</td>
                                        <td>2018-05-31 17:44:59</td>
                                        <td>not_used</td>
                                    </tr>
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your account on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>ID</td>
                                                <td>Application</td>
                                                <td>Support Expire</td>
                                                <td>Status</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                        <td>16195010</td>
                                        <td>NexoPOS - Extendable PHP Point of Sale</td>
                                        <td>2018-05-31 17:44:59</td>
                                        <td>not_used</td>
                                    </tr>
                                        </tbody>
                                    </table>

**Comment by nexopos** [comment]
Hi, after having reviewed your account, we've not been able catch any licences.
                                Please note that, it's required to have a licence on your account, in order to receive updates and support. 
                                [Click here](https://api.nexopos.com/dashboard/profile/envato-licences/add) to add a new licence to your Nexo Platform account.
                                Regards.

**Comment by nexopos** [comment]
Hi, after having reviewed your account, we've not been able catch any licences.
                                Please note that, it's required to have a licence on your account, in order to receive updates and support. 
                                [Click here](https://api.nexopos.com/dashboard/profile/envato-licences/add) to add a new licence to your Nexo Platform account.
                                Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "mahmoodi2" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "mahmoodi2" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "mahmoodi2" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "mahmoodi2" on [Nexo Platform](https://api.nexopos.com).
                            You might consider updating your issue and mention your username. 
                            Regards.
