### ISSUE TITLE
POS Stuck after genrating 2nd order

### ISSUE THREAD

**Issue by dhruvikpatel** [nexopos/v3-issues#66]
when i create 1st order in Pos it will work perfectly.then i generate 2nd order so when i check out 2nd order it will stuck and order is not completed.then i have to refresh page than again it work great for 1st one but for 2nd same thing will happen.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
