### ISSUE TITLE
Client Computer not printing on the kitchen

### ISSUE THREAD

**Issue by elvessisante** [nexopos/v3-issues#67]
**Username** : elvessisante
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
I have nexopos print server install on the server computer 
when i use server kitchen print is working
but when i use another workstation on the same network kitchen printer is not working(not printing)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by elvessisante** [comment]
Yes i define http://192.168.1.9:3236 note the system is installed on the under domain 

![image](https://user-images.githubusercontent.com/28305520/44784792-75d36600-ab97-11e8-8ab3-cf9cfa07947f.png)

**Comment by Blair2004** [comment]
No worry about the domain. The most important here is the following.
Normally Nexo Print Server should be installed on the POS machine (where the printer is connected). 
Now the IP defined on the settings should be the IP of the POS machine.
Is that the actual case of your achitecture ?

**Comment by elvessisante** [comment]
i have print server i call.. on the print the all printer is installed also the nexo print

the IP define is the print server 

then i have 2 client pos on the same network (no nexo print installed) but printer driver install also
but when i start the testing kitchen printer is not printing but when i use the server is working there

**Comment by Blair2004** [comment]
We would first make sure all the computer are connected on the same network.. the best config is that they should match the same IP range.
If you're on Windows, i would like you to open the command line and type the following command : 
`ipconfig`

That should print a result that you can post here.

**Comment by Blair2004** [comment]
You'll be contacted privately so that we can have a review on your system using Teamviewer.

**Comment by elvessisante** [comment]
i will send anydesk to you

**Comment by elvessisante** [comment]
Ok i send to your private no. already
