### ISSUE TITLE
Problem when select merge order and click on checkout

### ISSUE THREAD

**Issue by sergiotranchino** [nexopos/v3-issues#7]
username: amtcloud

when i select in options "Merge Order" if i select one or i merge orders the button checkout don't work
![schermata 2018-07-02 alle 17 24 14](https://user-images.githubusercontent.com/40768330/42172603-c5940706-7e1c-11e8-8e13-b15e3ad25826.png)

**Comment by sergiotranchino** [comment]
You have news?

**Comment by Blair2004** [comment]
We've proceeded to a review of your request, and we weren't able to face your issue. Here is the details of our environement : 
NexoPOS : 3.12.13
Gastro : 2.3.12

Please consider providing more informations of your system. We might need to have an access to your enviroment as well.

**Comment by Blair2004** [comment]
Hi, still waiting for these inforamtions.

**Comment by sergiotranchino** [comment]
What information do you need?

>

**Comment by Blair2004** [comment]
Your environment details : 
NexoPOS Version,
Gastro Version

**Comment by sergiotranchino** [comment]
Nexo v3.12.8

Gastro v2.3.11



Il giorno ven 6 lug 2018 alle ore 14:47 Blair Jersyer <
notifications@github.com> ha scritto:

**Comment by Blair2004** [comment]
Well, we'll publish an update, and you'll review if the issue persist. for now the issue will be closed.

**Comment by sergiotranchino** [comment]
I updated. I keep having problems with the checkout in merge order

Il giorno sab 7 lug 2018 alle ore 22:48 Blair Jersyer <
notifications@github.com> ha scritto:
