### ISSUE TITLE
I can't finish sell correctly

### ISSUE THREAD

**Issue by luisvillegasce** [nexopos/v3-issues#72]
**Username** : 
luisvillegasce

**Describe the bug**
I can't finish sell correctly because an error occurs  (The payment could not be made.)

**To Reproduce**
1. Go to /dashboard/nexo/pos
2. Click to add any item
3. Click to pay
4. See error (The payment could not be made.)
5. In the dashboard the sale is shown as successful

**Expected behavior**
 The sale is made correctly, and the pos is updated to continue taking orders

**Screenshots**
https://www.youtube.com/watch?v=tEd7YO6tclg

**Environment (please complete the following information):**
 - NexoPOS: 3.13.4
 - Gastro 2.3.19
 - Localhost server Laragon Full 3.4.0
 - PHP version 7.1.20
 - MySQL version 5.7.19
 - Devise used desktop browser

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Hi, please can you send your system details at contact@nexopos.com ?

**Comment by Blair2004** [comment]
Hi, we're still waiting for your details. Once submitted, please let us know.
