### ISSUE TITLE
Problem when Edit Categories

### ISSUE THREAD

**Issue by efaustor** [nexopos/v3-issues#74]
**Username** : efaustor

**Describe the bug**
I have this problem when I enter to this page: nexopos/dashboard/nexo/categories

**To Reproduce**
The system shows me this error: The request returned the following message : Route not found: "/nexopos/dashboard/nexo/categories/"
Code : 404

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-02-09 07:12:43</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, it seems like you've not yet added NexoPOS licence on your profile on Nexo Platform. Please consider adding it : http://api.nexopos.com/dashboard/profile/envato-licences/add
The support you're requested cover NexoPOS Domain. 

Thank you.

**Comment by Blair2004** [comment]
Hi, only Gastro licence has been added to your profile. Consider adding all the licence of our products that you've purchased here : http://api.nexopos.com/dashboard/profile/envato-licences/add

Thank you.
