### ISSUE TITLE
Table selecting error in Gastro

### ISSUE THREAD

**Issue by harrisarshad76** [nexopos/v3-issues#75]
Hi,

I am getting errors while adding dine in order, Table option not showing even we have add tables in backend. Please check screen shot and advise. Area is also added
![img20180904010804](https://user-images.githubusercontent.com/42948656/45002330-163de600-afef-11e8-94e3-c80bb6c5c636.jpg)
![img20180904010827](https://user-images.githubusercontent.com/42948656/45002368-6157f900-afef-11e8-8b35-a160762d3fdc.jpg)

Thanks

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Hi, please while posting an issue, please make sure to use the provided template. This issue doensn't provide the required information to handle your issue. 

We're closing.
