### ISSUE TITLE
Table and Area not showing

### ISSUE THREAD

**Issue by harrisarshad76** [nexopos/v3-issues#76]
**Username** : 
chharris
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Hi, I am getting errors while adding dine in order, Table option not showing even we have add tables in backend. Please check screen shot and advise. Area is also added**

**To Reproduce**
1. Go to 'POS'
2. Click on 'Dine in and select table'
3. Scroll down to 'nothing showing'
4. See error (Check screenshot)
![img20180904010804](https://user-images.githubusercontent.com/42948656/45002461-230f0980-aff0-11e8-921d-0b52113f4cfb.jpg)
![img20180904010827](https://user-images.githubusercontent.com/42948656/45002462-23a7a000-aff0-11e8-9d34-da932841bc3d.jpg)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-03-01 13:02:17</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-09-30 00:00:00</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, please next time you fill the error form. Make sure to fill all the required information. Your issue is not complete. We might however need to access to your system and review what's going on. You can however tell us how you've installed Gastro ? From the dashboard or by uploading with the FTP ?

**Comment by Blair2004** [comment]
We've not been able to get an answer from you. You can however re-open the issue if that persist. 
Closing.
