### ISSUE TITLE
Nexo print out on the kitchen

### ISSUE THREAD

**Issue by elvessisante** [nexopos/v3-issues#77]
**Username** : elvessisante
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
printing problem not printing kitchen item
![whatsapp image 2018-09-06 at 3 57 16 pm](https://user-images.githubusercontent.com/28305520/45158959-28d23e00-b1ee-11e8-9e25-2ec700dc6e32.jpeg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2018-08-15 13:00:58</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-12-07 23:49:32</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2018-08-15 13:01:49</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Please consider providing more information about your environment : PHP version, MySQL, modules and so on. Thank you.

**Comment by elvessisante** [comment]
![image](https://user-images.githubusercontent.com/28305520/45159334-2a503600-b1ef-11e8-8ec2-96937758dfae.png)
![image](https://user-images.githubusercontent.com/28305520/45159365-3805bb80-b1ef-11e8-89eb-ee76eb11dc6f.png)

**Comment by Blair2004** [comment]
You're using a old verison of NexoPOS & Gastro. Can you please update and check if the issue persist ?

**Comment by elvessisante** [comment]
i cannot update because the system is modified

**Comment by elvessisante** [comment]
7.2 php
Mysql 5.0

**Comment by nexopos** [comment]
if you have updated the script, you might read the section "Updating customized projet" :https://nexopos.com/faq/

**Comment by elvessisante** [comment]
what do you mean about updating customized project?

**Comment by Blair2004** [comment]
You project is has been customized by you and is not then supported by us.
