### ISSUE TITLE
Gastro module: Unknown character set: 'utf8_general_ci

### ISSUE THREAD

**Issue by ChaDye** [nexopos/v3-issues#8]
I have following error when installing Gastro online
A Database Error Occurred
Error Number: 1115
Unknown character set: 'utf8_general_ci'

Gastro module doesn't work

**Comment by Blair2004** [comment]
You're issue will be reviewed. Thank you for submitting.

**Comment by Blair2004** [comment]
fixed with https://github.com/Blair2004/gastro/commit/ad83580a022306aba3cec6ea77a6f3043d99868b
