### ISSUE TITLE
Feature : Notifiy users once their pickup order is ready

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#80]
**Username:** Blair2004
**Is your feature request related to a problem? Please describe.**
It's not related to an issue. But the purpose is to improve the system.

**Describe the solution you'd like**
If the users place an order from Nexo Store, we should implement a feature which let him know when his meal is ready so that he can come and pick that to the store.

**Describe alternatives you've considered**
The restaurant might have his own system to notify the users. However having that on the system, might make the process more faster.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
