### ISSUE TITLE
NexoStore Bug

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#81]
I have a fatal error installing plugin I said in private but no answer

I fix the issue to rename the folder nexostore to NexoStore and classes to Classes

because after activated the plugin we getting fatal error that view not found .

please review that . thanks

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Allright

**Comment by nexopos** [comment]
The issue should have been fixed so far.
