### ISSUE TITLE
Chrome desktop app for offline POS

### ISSUE THREAD

**Issue by harjanto-jadin** [nexopos/v3-issues#82]
With poor internet connection it is really risky for running online POS

Is it possible to have such as chrome desktop app which can work offline and will sync the database when reconnected to internet ?

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Hi, 
that's something we're planning but not with the version 3. NexoPOS 4 will offer that feature.

**Comment by harjanto-jadin** [comment]
we are looking forward to hear a good news about the new ver.4 release, any hints ?

**Comment by Blair2004** [comment]
This ideas is hold for our upcoming development. We'll think more about this implementation.
