### ISSUE TITLE
Not able to see product on pos screen

### ISSUE THREAD

**Issue by infinity2882** [nexopos/v3-issues#83]
**Username** : sandeep
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
I am not able to see and search product in gestro pos screen

**To Reproduce**

**Expected behavior**

**Screenshots**
.
![screenshot 5 1](https://user-images.githubusercontent.com/43368104/45679021-5b1c5d80-bb55-11e8-9425-c9b04824199b.png)

**Environment (please complete the following information):**
 - NexoPOS  v3.13.4  
 -  Gastro  v2.3.19
 - PHP version [ 7.2]
 - MySQL server version [5.6.21]
 - Devise used (desktop- local).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-03-05 09:27:39</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2019-03-05 09:00:23</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
Hi, have you checked wether the item are : 
- Available for sale ?
- Physical and had stock provided ?

**Comment by Blair2004** [comment]
How is that going so far ?
