### ISSUE TITLE
Cashier Payment Problem

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#84]
When we make a payment and then check in at the control panel, nothing seems to be paying about. Please check.
[cashier payment problem video.zip](https://github.com/nexopos/v3-issues/files/2404497/cashier.payment.problem.video.zip)

**Comment by Blair2004** [comment]
Ok, thank you for submitting this issue, Note that the issue should follow the provided template. We've however watched the video and noticed that the dashboard of the cashier is not updated.

We'll review that.

**Comment by Blair2004** [comment]
We've reviewed the issue from our side, and we've noticed that the Cashier Dashoard is updated after a sale. We're wondering if that might be possible to check the issue from your side.
![image](https://user-images.githubusercontent.com/5265663/45927612-d1daa180-bf2d-11e8-8da3-e7a99a6b5c23.png)
