### ISSUE TITLE
half and half payment problems?

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#87]
When we make half and half payment I mean we make 25 $ a payment. I want to pay 10 bugs cash...
the rest balance by credit card but payments doesnt show seperately... 

this problem has resolved before but It reappeared. I added a video you can check...
[bandicam 2018-09-21 11-21-19-300.zip](https://github.com/nexopos/v3-issues/files/2404536/bandicam.2018-09-21.11-21-19-300.zip)

please check and resolve.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Can you provide more informations about your system ? 
A Screenshot of the module list might be more helpful.

**Comment by scilang** [comment]
![screencapture-siparisuyg-site-dashboard-modules-2018-09-21-13_00_24](https://user-images.githubusercontent.com/35400199/45874783-6adab280-bd9e-11e8-9977-b6d0811ab4f7.png)

thats the modle list..

**Comment by Blair2004** [comment]
The explanation has been provided here https://github.com/nexopos/v3-issues/issues/86#issuecomment-423810658
