### ISSUE TITLE
Cashier Payment Problem #84

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#88]
When we make a payment and then check in at the control panel, nothing seems to be paying about. Please check.
[cashier payment problem video.zip](https://github.com/nexopos/v3-issues/files/2404844/cashier.payment.problem.video.zip)

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Duplicate of https://github.com/nexopos/v3-issues/issues/84
