### ISSUE TITLE
Feature : Allow order meal to be collected individually

### ISSUE THREAD

**Issue by Blair2004** [nexopos/v3-issues#89]
**Is your feature request related to a problem? Please describe.**
There is a feature on Gastro which let the waiter collect an order from the POS. We've checked the Waiter Screen availabel outside the POS, which should provide the same feature as what is available on the POS. The issue is that feauture the state of the entire order (collect all items) instead of doing that separately.

![collect a meal gastro](https://user-images.githubusercontent.com/5265663/45965632-e9468700-c020-11e8-85fc-fdb5d950b0f6.png)

**Describe the solution you'd like** 
A solution for this should be to implement more control over the waiter screen available on the dashboard to collect each item individually.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
