### ISSUE TITLE
Import of clients.

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#9]
I would like Nexopos to have a functionality to import clients. If you have used another POS program and you have entered all the customer data, then if you change to Nexopos you will want to include all the data of your clients again.

In this case, a customer import function is necessary.

Imagine you have 1000 clients, do you know how much work it is to introduce them by hand?

I hope you have this functionality in mind.

**Comment by Blair2004** [comment]
Implemented : https://github.com/Blair2004/nexopos/commit/2faf0644901c994f68f9b5056cf49c3ef2fc7823
