### ISSUE TITLE
is ıt possible to show vat including prices in gastro dashboard ?

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#91]
I think that the taxes are being transferred to the gastro dashboard is wrong

I added a screehshot how it has to be.

![ekran alintisi-2](https://user-images.githubusercontent.com/35400199/46008174-b3f37500-c0c4-11e8-87ed-b3d63731f10f.PNG)

Thank you...

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
