### ISSUE TITLE
discounts do not appear on the dashboard screen

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#92]
Username : scilang

1- When I add a discount the order, unfortunately Discount doesnt appear on the dashboard screen.
2- When you want to add a discount, there is an error in the discount screen. This problem occurs when we translate into Turkish.

I've added a few screenshots to give you a better understanding of the topic

![ekran alintisi-4](https://user-images.githubusercontent.com/35400199/46008909-b6ef6500-c0c6-11e8-87ef-a340b31d5f3d.PNG)

![ekran alintisi](https://user-images.githubusercontent.com/35400199/46008886-ac34d000-c0c6-11e8-8ba3-c426ea68e9cf.PNG)

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Thank you we'll review that more deeper.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.
