### ISSUE TITLE
GLOBAL TURNOVER AND RECEIVABLES don't work regular

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#94]
I've some trouble about Dashboard tools GLOBAL TURNOVER AND RECEIVABLES don't work regular when I want to delete cache, It has no effect. but when I go to cpanel and restart PHP FPM global turnover and receivables instantly clear up. when I continue to make an order, Global order and receivables are showing previous values.. please give me an idea what I am supposed to do this problem. I talked with the hosting company, but they couldn't help with PHP FPM. This option doesnt deactivate or remove.. Thank you best regards.

I added the conversation I make with Host Service

Dear Hasan, this is to be inform you that it is not possible to stop php-fpm service on server as it is one of the core services of server.

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
Hi, thank you for your issue. Please for your upcoming issues. Make sure to use the provided template. 
Thank you.

**Comment by Blair2004** [comment]
We're still looking ahead to see why you have this issue with that module.
