### ISSUE TITLE
Partials Orders doesnt seems in dashboard

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#96]
Partials Orders amounts does not seems in dashboard and cahier dashboard.

![9](https://user-images.githubusercontent.com/35400199/46129240-b11c8f80-c23e-11e8-90d5-520ce6e07b0c.PNG)
![10](https://user-images.githubusercontent.com/35400199/46129241-b1b52600-c23e-11e8-9206-12407e5228f9.PNG)

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/46620249-1fedc880-cb1c-11e8-9621-7d1ad593bea0.png)
![image](https://user-images.githubusercontent.com/5265663/46620254-267c4000-cb1c-11e8-86f2-fbe227454639.png)
We've reviewed the issue. From our side the cashier dashboard is updated. Now you need to have this in mind : The partial payment only shows what has been paid from the total due amount, not the total value of the order.
