### ISSUE TITLE
Issue : Partial Payments Problems

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#99]
1-Partial Payments still doesn't appear and another problem occurred. When you closed the orders as a partial Payments seem double.

2-Partial Payments still doesnt appear in cashier dashboard.

3-Turkish translation in cashier dashboard is wrong. It must be like this " Full orders / Tamamlanan Ödemeler, Partials Orders / Kısmi Ödemeler , Unpaid Orders Ödenmeyi Bekleyen

![ekran alintisi1](https://user-images.githubusercontent.com/35400199/46213183-97637100-c340-11e8-98a0-ed75eafb6bac.PNG)
![ekran alintisi2](https://user-images.githubusercontent.com/35400199/46213185-97fc0780-c340-11e8-9650-87adbf27bfa9.PNG)

**Comment by Blair2004** [comment]
Thank you for these notes

**Comment by Blair2004** [comment]
We've fixed the translation. can you provide more information about the next image ?

**Comment by scilang** [comment]
It s very simple to understand, if you make a payment in Nexopos you will see.  When you closed the orders as a partial Payments seem double in dashboard.

**Comment by Blair2004** [comment]
Hum, after testing i don't believe there is an error. Please consider the following image.
![screenshot-nexopos go-2018 10 01-08-25-31](https://user-images.githubusercontent.com/5265663/46275192-fea53f00-c553-11e8-9e86-ed867fac1ab4.png)

**Comment by scilang** [comment]
if you think that there is not error. sorry It s my mistake. I hope that
you dont have to apologize later..

Blair Jersyer <notifications@github.com>, 1 Eki 2018 Pzt, 10:28 tarihinde
şunu yazdı:
